### ISSUE TITLE
Improve external js + css organisation

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#329] opened 2016-02-15 10:01 UTC
These days we often find ourselves adding new js libraries and css stylesheets.

They need to go in a more or less standard file structure layout for the project and this can take some time to download, extract and manually place the files in the right folder. This process is cumbersome and error prone.

There's a better solution to this by combining bower and grunt. Bower.json is already in the project. Installing new libs can be faster by using bower install. One extra plugin in Gruntfile is needed to copy the library's js, css and images to the correct place.

https://github.com/yatskevich/grunt-bower-task

**Comment by jekkos** [comment] 2016-02-15 10:01
Was looking into this tomorrow got something basic setup, will hopefully refine later today

**Comment by daN4cat** [comment] 2016-02-15 11:03
Great idea, indeed I've spent quite some time to understand what is what and not sure I've done right with the couple of things for bootstrap I've added.
Thanks for looking into this.

**Comment by daN4cat** [comment] 2016-02-15 14:44
Current Bootstrap dependencies to be added:

- bootswatch themes: https://github.com/thomaspark/bootswatch
- jasny/bootstrap enhancements: https://github.com/jasny/bootstrap
- smalot/bootstrap-datetimepicker: https://github.com/smalot/bootstrap-datetimepicker

**Comment by jekkos** [comment] 2016-02-15 15:00
Yes indeed the bootstrap themes can be added through bower, will give that a try later today.

**Comment by daN4cat** [comment] 2016-02-15 15:07
Yes, got the point, I just listed the known dependencies to easy the job :-)

**Comment by jekkos** [comment] 2016-02-15 22:06
I've stashed my work in another branch taken from bootstrap-UI. A couple of things might need to be sorted out first. 

* bowerized projects are imported using bower.json now. These include jquery + plugins, bootstrap themes and plugins
* regular 'legacy' js plugins without bower support and applications specific code will still be in js folder.
* javascript is concatenated, first all bower modules and then the app specific js
* minified js will stay in the dist/ folder and ship with the repo. If one wants to use debug mode ?debug=true the use

    bower install && grunt

* TBD: themes folder should just include a dependency on a different bootswatch-dist bower theme. In this case we might want to add a new bower.json file to each theme folder. When running bower install in that folder the necessary css + js will be downloaded and then the loader can override the default flatly layout.

Remaining issues: 
* Currently thickbox is broken (was planning to replace it with bootstrap dialog anyway) due to CI complaining about invalid chars (prolly an &)
* Tablesorter seems to be broken as well

**Comment by daN4cat** [comment] 2016-02-16 09:31
Is tablesorter issue confirmed?

**Comment by jekkos** [comment] 2016-02-16 09:40
Not completely sure, I had a quick look but as the table only contained one row I'm not certain that sorting should have been enabled.

**Comment by jekkos** [comment] 2016-02-16 09:40
Maybe in the old version table sort was disabled for one row as well

**Comment by daN4cat** [comment] 2016-02-16 13:10
I'll check.

**Comment by jekkos** [comment] 2016-02-16 22:44
Also the login page needs to include both jquery and bootstrap. Will see if there's some kind of workaround for that.

**Comment by odiea** [comment] 2016-02-16 22:46
@jekkos  Thanks for all the work. Hope you are enjoying this major upgrade too.

**Comment by jekkos** [comment] 2016-02-16 22:49
yes kind of cool to see that old ugly ui finally go away :)

**Comment by daN4cat** [comment] 2016-02-16 22:56
Worth a beer celebration.... of course Belgian (too many to chose!)

**Comment by daN4cat** [comment] 2016-02-16 22:57
The old UI was like the 0 in comment... couldn't stand to it anymore!

**Comment by jekkos** [comment] 2016-02-17 09:18
Hehe indeed, I just didn't feel up to this job alone. More motivating to work together on these things.

For the new modals I will try to leave the original links as they were. I'll write some boilerplate that binds the links to the BootstrapDialog js code. Then it's just a matter of adding some attributes to define url and dialog title.

**Comment by daN4cat** [comment] 2016-02-17 12:41
WRT login, not sure we need that much js. But I'll have a look.

**Comment by daN4cat** [comment] 2016-02-17 13:48
By the way, what about CI being part of bower? Does that make sense?

**Comment by jekkos** [comment] 2016-02-18 22:54
Only thing in login page is a js focus on the username field. Bootstrap css is needed as well. Will have a look if I can inject bower templates using grunt in that header as well.

**Comment by jekkos** [comment] 2016-02-18 22:58
I did a quick couple of tests and all seems good in the (ospos) universe.

Good reminder on the css files. I think I'll need some kind of minification task for that beside the current js setup. You'll have to load everything using bower for the time being.

**Comment by daN4cat** [comment] 2016-02-18 23:13
Yes bootwatch/flatly bootstrap.css is needed indeed in login.

**Comment by jekkos** [comment] 2016-02-19 07:37
So the idea is to add two final files to the repo, which are the minified css and js. For development you'll need to install the source with bower. I'll look into adding the minified css now to make the app work again without using debug=true

**Comment by jekkos** [comment] 2016-02-19 08:46
I have adapted the build to generate minified css now, but having one missing stylesheet so not completely there yet. Will finish off later today. 

I have also removed the import statements in ospos.css. Print stylesheets will use media queries (which does not require to declare the type in the tag anymore, handy if all is minified into one file). Also page load speed should be better with all assets shrinked.

**Comment by daN4cat** [comment] 2016-02-19 09:35
#328 and this topic are mixing up a bit...

I installed and run bower and it's working since the bower_component dir is created.
We should temporary commit that dir to github until we create the minified css.

That said bootstrap.css is the standard one so we need to import flatly one.

**Comment by daN4cat** [comment] 2016-02-19 09:48
grunt doesn't work, I get a "Error: Cannot find module 'load-grunt-tasks'

**Comment by jekkos** [comment] 2016-02-19 09:59
DId you run 
    npm install

?

**Comment by daN4cat** [comment] 2016-02-19 11:08
you mean bower? yes that's sorted as discussed.. or do I need to install something else?

**Comment by daN4cat** [comment] 2016-02-19 11:10
btw, I'm running npm install only and recheck.

**Comment by daN4cat** [comment] 2016-02-19 11:28
it seems that after npm install things are working now.

**Comment by daN4cat** [comment] 2016-02-19 11:31
Re my comment about bower_component dir, I recall that. No it's not possible because it pulls in all the packages.

Indeed we need to get the min.css for dist. I'll wait for that addition to happen.

**Comment by jekkos** [comment] 2016-02-19 11:55
Indeed we should just add the min.css. I have an adapted build I did those changes this morning, but some part is still missing in the final result. Think it's better to omit the sources and have them installed only when doing development in the app. The debug=true flag should be set in a cookie so that it remains valid throghout a dev session. This is currently not the case yet

**Comment by daN4cat** [comment] 2016-02-19 12:58
OK, thanks for the work.

**Comment by jekkos** [comment] 2016-02-19 18:06
Css minification should be ok now. I had to add some tweaks for the bootswatch flatly as they have omitted the css file in their  bower.json main attribute. If any issue then let me know.

**Comment by jekkos** [comment] 2016-02-19 18:07
Ok shit I accidentaly did a forced update on the other branches as well.

**Comment by jekkos** [comment] 2016-02-19 18:08
I guess master and bootstrapUI branches are fine. Don't know if there was anything new in develop/2.4?

**Comment by daN4cat** [comment] 2016-02-19 18:49
I'll check it later.

**Comment by odiea** [comment] 2016-02-19 19:05
Bootstrapui looks good. Small issues with login, Employee and barcode forms but overall looks great. I did not check any functionality.

**Comment by daN4cat** [comment] 2016-02-19 19:11
grunt requires 'npm install grunt-contrib-cssmin' now (installed)

**Comment by daN4cat** [comment] 2016-02-19 19:18
yep, login is not right... let me check what's wrong and see if I can fix.

**Comment by daN4cat** [comment] 2016-02-19 19:25
the issue is the following: `<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />`

**Comment by daN4cat** [comment] 2016-02-19 19:39
since bootstrap.css disappeared the min.css does not work....

also the main page style is not right, footer disappeared...

oh dear :-(

**Comment by odiea** [comment] 2016-02-19 20:27
I think your both doing a great job. This is quite a task. Thanks and I am sure when it's finished others will thank both of you too.

**Comment by daN4cat** [comment] 2016-02-19 21:09
@odiea do you see the grey footer in your installation?

**Comment by odiea** [comment] 2016-02-19 21:11
No not on any of the pages nor do I see any text from the footer

**Comment by odiea** [comment] 2016-02-19 21:21
It also appears that the entire page refreshes and not just the container. It's a bit annoying.

**Comment by odiea** [comment] 2016-02-19 21:34
The page refresh appears to be a windows firefox issue. Pale moon, IE,  chrome and firefox on Ubuntu look ok.

**Comment by daN4cat** [comment] 2016-02-19 21:41
OK, found the reason why things got upside down, but @jekkos needs to fix it properly.
This doesn't fix login though.

using ?debug=true I found that this is the correct list of css and correct order:

```
		<!-- start css template tags -->
		<link rel="stylesheet" type="text/css" href="css/autocomplete.css"/>
		<!-- <link rel="stylesheet" type="text/css" href="css/barcode_font.css"/> -->
		<link rel="stylesheet" type="text/css" href="css/general.css"/>
		<link rel="stylesheet" type="text/css" href="css/invoice.css"/>
		<!-- <link rel="stylesheet" type="text/css" href="css/invoice_email.css"/> -->
		<link rel="stylesheet" type="text/css" href="css/popupbox.css"/>
		<link rel="stylesheet" type="text/css" href="css/receipt.css"/>
		<link rel="stylesheet" type="text/css" href="css/register.css"/>
		<link rel="stylesheet" type="text/css" href="css/reports.css"/>
		<link rel="stylesheet" type="text/css" href="css/tables.css"/>
		<link rel="stylesheet" type="text/css" href="css/ospos.css"/>
		<link rel="stylesheet" type="text/css" href="css/ospos_print.css"/>
		<!-- end css template tags -->

```

above list reflects the import that used to be in ospos.css and have been moved out.

barcode.css and invoice_email.css are causing issues and ospos.css needs to be last as probably there are clashes with style definitions. We should clean up and understand why.

**Comment by daN4cat** [comment] 2016-02-19 23:35
ok, I fixed the css issues and changed the grunt script to generate min.css with the correct sequence.

However something still doesn't look completely right to me about topbar icon size and font, but I'll fix it later.

login.php is still not ok, but I believe jekkos wanted to fix it so I leave that to him.
I'm my opinion it's better to separate the opesourcepos.min.css from bootstrap flatly .css.
In case somebody wants to use CDN they most likely prefer to fetch bootstrap stuff independently.
But thta just my thought.

**Comment by daN4cat** [comment] 2016-02-19 23:36
I also added bootstrap-select but not used yet.

**Comment by odiea** [comment] 2016-02-20 00:10
It looks ok to me but the icons should be centered not offset left or right.

**Comment by odiea** [comment] 2016-02-20 00:32
The tax % holder needs to be longer. It accepts the number but it does not show on the forms properly. It only shows 2 numbers.

**Comment by odiea** [comment] 2016-02-20 00:34
I agree with you on the Bootstrap.css being a separate file. I did enjoy using the style.css because It was easier to work with.

**Comment by odiea** [comment] 2016-02-20 02:32
login.css changed width from 100 to 92 and it back to where it was

input[type="text"],input[type="password"]{
  width:92%;
  background:#fff;
  margin-bottom:4%;
  border:1px solid #ccc;
  padding:4%;
  font-family:'Open Sans',sans-serif;
  font-size:95%;
  color:#555;
}

**Comment by jekkos** [comment] 2016-02-20 09:03
@odiea good point, this needs to be added back again as well.

**Comment by jekkos** [comment] 2016-02-20 09:03
at first these styles were causing issues in the minified because it had the login included for the rest of the app. This kind of screwed up layout in other pages.

**Comment by jekkos** [comment] 2016-02-20 09:05
@daN4cat does the order of inclusion change the layout itself here? I'll try to see if it does any difference after putting these removed style definitions back in login.css

**Comment by jekkos** [comment] 2016-02-20 09:07
@daN4cat It would be good indeed to have a separate minified bootstrap.css which can then be included in the login page only. Same for jquery js.

**Comment by daN4cat** [comment] 2016-02-20 12:12
@jekkos the order changes parts of the layout indeed. I changed the grunt file to reflect what used to be in the old opspos.css import.
As already said, we should split out bootstrap (flatly) min.css and then login.php has bootstrap + login css and everything should be back to what it used to be.
Please don't change other parts of the css internals before having setup things properly.

@odiea style.css from flatly moved to ospos.css, it's all in there.
However style.css could be used for templating. That was something I wanted to look into later since the templating is not supported completely and properly at the moment.
I wanted to get it working with flatly as default first.

**Comment by daN4cat** [comment] 2016-02-20 12:14
With the order of css, probably ospos.css should be all set !important to override things no matter of the order.
Or I should cross check all css files that are not coming from plugins to understand what's wrong.
But ospos.css and osposprint.css need to be last because they act like style.css.

**Comment by jekkos** [comment] 2016-02-20 14:02
I tihnk the problem was that login and invoice_email were included in the minified result and that they weren't there before. I wanted to try and define this in the inverse order which makes more sense.

I know that for js it does matter in which order you load files, but I'm not sure whether it's the same for css.

**Comment by jekkos** [comment] 2016-02-20 14:03
http://stackoverflow.com/questions/5902858/order-of-prioritization-when-using-multiple-contradictory-css-files

maybe only in case there are duplicated style definitiions but not sure if this applies to the css present in the project

**Comment by daN4cat** [comment] 2016-02-20 15:25
Yes, probably there are but spotting and debugging takes time.

**Comment by jekkos** [comment] 2016-02-20 20:26
Ok currently I'm not seeing any other issues in comparison with the version that has the order explicilty defined. You mind me pushing this part?

@odiea could you perhaps check on my server if there's any difference I didn't spot?

**Comment by odiea** [comment] 2016-02-20 20:43
Your server appears to be the same as the 1 I downloaded. It still has the same issues that I wrote about earlier. login form ,Config barcode form, Employee form all require additional work.

**Comment by jekkos** [comment] 2016-02-20 20:47
Ok so no more extra regressions with respect to @daN4cat's last modification? I'll just take it from there then.

**Comment by daN4cat** [comment] 2016-02-21 16:09
@jekkos there is still an issue.

The font style & size is different between .min and ?debug=true. The latter is the correct one that I tuned.
You can see it in the topbar, menu bar and etc.

**Comment by daN4cat** [comment] 2016-02-21 16:12
it's the font, with min it's Arial and with ?debug=true is Lato. Let me see if this can be fixed

**Comment by daN4cat** [comment] 2016-02-21 16:18
Something goes wrong in minifying bootstrap.css probably.

Correct one:

```
font-family
Lato, 'Helvetica Neue', Helvetica, Arial, sans-serif
**"Lato"**, "Helvetica Neue", Helvetica, Arial, sans-serif        body
```

Wrong one:

```
font-family
Lato, 'Helvetica Neue', Helvetica, Arial, sans-serif
**Lato**, "Helvetica Neue", Helvetica, Arial, sans-serif        body
```

**Comment by daN4cat** [comment] 2016-02-21 17:30
OK, I run grunt and I found that the cssmin reports a `Ignoring remote @import of "https://fonts.googleapis.com/css?family=Lato:400,700,400italic" as no callback given.`

That's probably the issues and why the font is "dropped".

**Comment by daN4cat** [comment] 2016-02-21 20:02
With my commit I fixed the font style and login issues:

* moved bootstrap.css out of opensource.min.css
* modified grunt script:
  * to copy bootstrap-dist (flatly) bootstrap.min.css to dist/
  * add correct css files to header.php and logih.php
  * added md5 (cachebreak) to bootstrap.min.css
* added bootstrap-select to bower (and in package.json)

js minification is untouched and seems working fine to me.

Templates get just the opensrouce.min.css but not the bootstrap.min.css because needs to be the templated one.
Therefore a manual addition is required in the templated themes (I will submit an example to spacelab later).

**Comment by jekkos** [comment] 2016-02-21 20:23
Thanks for looking into it, didn't find the time yet this weekend. WIlll continue prolly tomorrow on  my way to work

**Comment by jekkos** [comment] 2016-02-21 20:24
Good spot on the font. This was bugging my local dev when I didn't have an internet connection. Guess it'll be better to include that font directly.

**Comment by daN4cat** [comment] 2016-02-21 20:30
ok, fixed spacelab as well as an example of templating things with the new setup.

**Comment by daN4cat** [comment] 2016-02-21 20:31
@jekkos the current configuration will do in my opinion, please check if something needs to be adjusted (minot) but I hope we don't need to change too much about this story now.

Maybe the template part can be better but for the time being one person can live with the way it is.

**Comment by jekkos** [comment] 2016-02-22 10:50
I'm happy that we have the build working now, but not completely satisfied. One thing I would like to improve is addition of the repo's private js to the script tags using bower. Following steps could be done to improve further. 

* declaring the directory 'js' as a dependency in the main bower.json. 
* then another bower file should be added to the js folder, defining which files to copy
* bower_concat will be sufficient and we'll be able to omit the concat:js step
* wiredep will replace the tags:js step

But maybe this isn't the most important thing now as I'd like to advance the UI improvements first.

**Comment by daN4cat** [comment] 2016-02-22 13:34
Basically you want to have all js scripts in js for debug purposes and not depend on bower_components for.

**Comment by jekkos** [comment] 2016-02-22 13:38
No the only difference will be that wiredep will inject both the js in our project + the js imported by the declared plugins.. Just a matter of keeping the number of grunt plugins limited and make bower manage all of our files. 

This means we won't need extra concat step for our own js files as the bower mechanism can do it all at once

**Comment by daN4cat** [comment] 2016-02-22 13:54
ok, an optimisation (so it sounds to me), functionality result will be the same as it is now.
Maybe you can experiment in a private branch and submit when working 100%, but as you said after we have sorted other things like UI & jQuery update.

**Comment by jekkos** [comment] 2016-02-22 22:48
I've added .bowerrc postinstall hook. Grunt will now run automatically after a bower install.

Also when I regenerate the headers for the template, then a relative path is found in the template's header Not sure why this is but think it will break the includes.

**Comment by daN4cat** [comment] 2016-02-27 10:38
I've changed a rule in Gruntfile.js to fix the double inclusion of bootstrap.js.

**Comment by jekkos** [comment] 2016-02-27 17:23
Ok good job, my idea of this whole build was to avoid spending too much time on these kind of problems..

**Comment by daN4cat** [comment] 2016-02-27 17:35
Understood, what I meant is that you might have a better idea about how to solve the issue. I really don't get how come two scripts are pulled with different versions.

**Comment by daN4cat** [comment] 2016-03-07 22:06
There is a duplicate of bootstrap.js left when not using the min (e.g. ?debug=true). That needs to be solved in the grunt script.

**Comment by daN4cat** [comment] 2016-03-13 11:47
I tried to find a way to remove the duplicate bootstrap.js but it seems that I'm not successful with Grunt scripting on that.

Also we need to fix the issue with the templates that are not getting updated correctly.

**Comment by jekkos** [comment] 2016-03-16 12:27
Also the jquery.js is still missing from the login page, might be better to import it directly.

**Comment by daN4cat** [comment] 2016-03-16 14:45
Is that needed?

**Comment by jekkos** [comment] 2016-03-16 15:20
There still is a js error on the login page, $ is undefined.

**Comment by daN4cat** [comment] 2016-03-16 16:07
Ok, I didn't check that. I'll do next days.

**Comment by jekkos** [comment] 2016-03-23 17:50
Still one open issue as noticed by @odiea in #413

**Comment by daN4cat** [comment] 2016-03-25 20:57
Login issue is sorted using standard javascript to set the focus on the username input on window load.

I close this thread as I believe it's now all sorted. There is still the complete template support but there is a dedicated issue for that (#409).

**Closed by daN4cat** 2016-03-25 20:57 UTC
Labels: enhancement
