### ISSUE TITLE
Takings or overview sort still a little buggy.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#139] opened 2015-09-09 14:21 UTC
Scenario I log into ospos sales and I want to see how yesterdays sales
 went. I use the calendar,choose a date and it displays the info but with no sort. I
 refresh the page. No change. I found if a new sale is not added sorting does not work.

**Comment by jekkos** [comment] 2015-09-09 17:33
I just did a quick retest and can't reproduce. So nothing happens once you click the column headers after selecting a date range?

If you have lots of sales then you have to wait for the spinner in the search field to stop before sorting will work.

**Comment by odiea** [comment] 2015-09-09 20:49
The overview is pressed before any day sales are entered. The date range selection shows for the current date. I then select a new date range for the previous day or week. All Tickets showed ok but the table sorting feature did not show. I usually see the sort icon by the selection name but when this happens there is nothing there until I enter a new sale for that day.

**Comment by odiea** [comment] 2015-09-12 11:14
Changing this fixed the issue I was having. It was 1
//Only init if there is more than one row
	if($('.tablesorter tbody tr').length > 0)
	{

**Comment by jekkos** [comment] 2015-09-13 21:15
Ok thanks, I see what's causing this now.

This check was added to stop the sorter init if there were no rows in the table at all. I found that this bug appears once you load up an empty table and then use the search functionality to look for items, which will fill it up at that point. So in that case sorting should be initialized because it wasn't done because of the initial empty table.

**Comment by jekkos** [comment] 2015-09-14 08:31
Should be fixed now in the commit referenced here.

**Closed by jekkos** 2015-09-14 08:31 UTC
Labels: bug
