### ISSUE TITLE
Search with customer name in sales Taking not working.

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#654] opened 2016-06-15 05:56 UTC
At least for me it is not working. Can anybody check and confirm ?

**Comment by gfxgee** [comment] 2016-06-15 06:12
it works for me.

**Comment by RamkrishnaMondal** [comment] 2016-06-15 06:20
Is it latest master ?  It is working on a 20 days old version but not in latest version.

**Comment by gfxgee** [comment] 2016-06-15 06:23
i just download this version now, the search is working

**Comment by RamkrishnaMondal** [comment] 2016-06-15 06:26
ok .... i 'll re download and try..... thanks for your feedback.

**Comment by RamkrishnaMondal** [comment] 2016-06-15 07:27
Downloaded and tested..... search with customer name in taking page NOT working.

**Comment by RamkrishnaMondal** [comment] 2016-06-15 07:31
![screenshot from 2016-06-15 13 00 05](https://cloud.githubusercontent.com/assets/14151032/16071498/40da59cc-32f9-11e6-9db1-0a5b8e81222b.png)

**Comment by odiea** [comment] 2016-06-15 11:45
It appears the only thing being searched for is pos numbers. Nothing else seems to work .

**Comment by onyema3** [comment] 2016-06-15 11:59
Odiea Invoice number you mean?

**Comment by odiea** [comment] 2016-06-15 12:03
That also does nothing. The only search that appears to be working is when you type in pos plus the receipt number.

**Comment by odiea** [comment] 2016-06-15 12:15
I tried a different setup. Filtering appears to be working on both cash and invoices. If you enter an Invoice number into the search box it will find that number. The only issue is you have to get out of takings and then back into takings before any other rows will show again.

**Comment by jekkos** [comment] 2016-06-15 14:13
Got this bug fixed on my local laptop on the train this morning. I tried to push but that didn't work so I'll do that again once I ride back from work.

**Comment by jekkos** [comment] 2016-06-15 15:19
I did a fix for this there was an error 500 indeed.

**Comment by jekkos** [comment] 2016-06-15 15:19
Should be fixed now

**Comment by odiea** [comment] 2016-06-15 20:37
Takings is now searching customer names ok but after you remove the search the tables do not refresh.

**Comment by jekkos** [comment] 2016-06-16 15:46
I'm unable to reproduce this currenty.. after searching and deleting characters again all sales show up as it should.

If it searches for a name then it should search for anything as there's no real difference in the code in handling the search text, it just asks the query to run again if any character changes.

Could you check in firefox inspector -> network tab if there's an http status 500 for sales / search url? 
And if yes maybe paste the contents here.

**Comment by daN4cat** [comment] 2016-06-16 17:20
I tested this and there is something strange indeed, but different from other description.

You can search by customer name, but when you remove the search term from the search box you don't see back the full list. However if you search another customer name it's selected and if you remove the second term you see the view of the 1st customer that was searched.

Really weird.

**Comment by likozhang** [comment] 2016-06-18 13:07
https://github.com/jekkos/opensourcepos/pull/671

**Comment by daN4cat** [comment] 2016-06-18 13:15
Adds a space between first name and family name.

Your fix is not right I'm afraid.

**Comment by likozhang** [comment] 2016-06-18 13:18
where querry for select the name ?

**Comment by likozhang** [comment] 2016-06-18 13:22
i found the querry at cotroller and this result for you brother

![snapshot_2016-6-18_20-21-8](https://cloud.githubusercontent.com/assets/6987941/16171140/47368c5a-3592-11e6-82ff-e603e128b3ef.jpg)

i found space in database
i think wrong is when create a name

**Comment by likozhang** [comment] 2016-06-18 13:23
yeah i found that, try to double space when search

**Comment by likozhang** [comment] 2016-06-18 13:36
i was check my code, i feel that code wrong fatally

**Comment by daN4cat** [comment] 2016-06-18 13:47
You sure you are not mixing up issues here. What is the problem you are reporting to do with the original issue?

**Comment by likozhang** [comment] 2016-06-18 13:57
i find the error, i try to rename the customer name, and error gone??

**Comment by daN4cat** [comment] 2016-06-19 10:34
The problem is that the search box in bstable doesn't allow you to add a space when inputing `first_name` and then `last_name` to further narrow down the list

**Comment by daN4cat** [comment] 2016-06-21 21:50
@jekkos what about this bug?

**Comment by jekkos** [comment] 2016-06-22 06:07
Bootstrap table does indeed seem to trim spaces after a short delay  if there's no other word typed after the first.. but that should yield any different behavior in the server side search result set

**Comment by jekkos** [comment] 2016-06-22 06:10
I can't really reproduce this either when I search for a name and wipe it out again, all previously rows just reappear

**Comment by odiea** [comment] 2016-06-22 11:37
I must have @daN4cat  issue. I load takings with a date range and all is ok. I enter a name and all is ok. I clear the name and nothing shows. I can renter a different name and the rows for that person show. I remove that name and either I get 1 random row or nothing shows until I leave or refresh or enter a different name in search.

**Comment by daN4cat** [comment] 2016-06-22 11:56
Yes, that's what I see as well.

**Comment by jekkos** [comment] 2016-06-22 12:36
Ok weird i did test this scenario this morning both with a small and large number of sale records. Could one perhaps check the requests in the inspector to see if the search query is corectly sent to the server? Maybe just a screen cap of the params and results tab when this error occurs?

**Comment by odiea** [comment] 2016-06-22 13:00
So here is the screen shot when the issue is showing. I also included a txt file showing what I could prior to the issue if it has any bearing on this issue.

![2016-06-22 06_57_03-](https://cloud.githubusercontent.com/assets/10962177/16267377/b0b4f386-3846-11e6-887b-6e8f2bf08c59.png)
[errors.txt](https://github.com/jekkos/opensourcepos/files/327879/errors.txt)

**Comment by jekkos** [comment] 2016-06-23 06:51
@odiea thanks for the screencap already, however what I really need to know is the parameters and response of the search queries. Will try again myself to reproduce now.

**Comment by daN4cat** [comment] 2016-06-23 09:35
@jekkos 

- selected last 30 days transactions (many visible)
- search for a user Bob:

> search?search=bob&order=asc&limit=20&offset=0&start_date=2016-05-25&end_date=2016-06-23&filters%5B%5D=

- result: 

> {"total":1,"rows":[{"sale_id":"144","sale_time":"28\/05\/2016 14:35:38","customer_name":"Bob Smith","amount_tendered":"\u00a3448.00","amount_due":"\u00a3448.00","change_due":"\u00a30.00","payment_type":"Debit Card 448.00","invoice_number":"","invoice":"","receipt":"<\/span><\/a>","edit":"<\/span><\/a>"},{"sale_id":"-","sale_time":"Total<\/b>","amount_tendered":"\u00a3448.00<\/b>","amount_due":"\u00a3448.00<\/b>","change_due":"\u00a30.00<\/b>"}],"payment_summary":"
> Debit Card: \u00a3448.00<\/div><\/div>"}

- clean search box:

> search?search=&order=asc&limit=20&offset=0&start_date=2016-05-25&end_date=2016-06-23&filters%5B%5D=

- result:

> {"total":0,"rows":[],"payment_summary":"
> <\/div>"}
>

**Comment by jekkos** [comment] 2016-06-23 10:19
OK So it's a server side problem. I have a suspicion that it might be related to this commit ad1b3aeaac2b6c76a4b7ff4bfc6f51910ea9e446

**Comment by daN4cat** [comment] 2016-06-23 10:44
@jekkos I'm afraid it cannot be since this issue is dated 15th June and was already visible and that change was 4 days ago (19th June).

For instance see:

> odiea commented 8 days ago
> Takings is now searching customer names ok but after you remove the search the tables do not refresh.

**Comment by daN4cat** [comment] 2016-06-23 10:52
Instead of that, are we sure that in a ajax call we don't have the items temp table available and that's why it might work in some case and not in others?

In search there is: `$this->Sale->create_sales_items_temp_table();` I don't have time to check now what's called when doing the table refresh or similar...

**Comment by jekkos** [comment] 2016-06-23 11:18
OK I didn't check the timeline here. I'll throw my debugger at it later today and will have a deeper look then.

**Comment by daN4cat** [comment] 2016-06-24 17:52
@jekkos have you got somewhere with this?

**Comment by jekkos** [comment] 2016-07-05 06:34
Just tried to reproduce this to no avail. I checked the generated queries and in both cases I don't see a difference

**Comment by jekkos** [comment] 2016-07-05 06:37
**on inital load**
`SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-07-01' AND '2016-07-05'
GROUP BY `sale_id`
 LIMIT 25`

**with search string**
`SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-07-01' AND '2016-07-05'
AND   (
`customer_last_name` LIKE '%Bob%' ESCAPE '!'
OR  `customer_first_name` LIKE '%Bob%' ESCAPE '!'
OR  `customer_name` LIKE '%Bob%' ESCAPE '!'
OR  `customer_company_name` LIKE '%Bob%' ESCAPE '!'
 )
GROUP BY `sale_id`
 LIMIT 25`

**after clearing search**
`SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-07-01' AND '2016-07-05'
GROUP BY `sale_id`
 LIMIT 25`

**Comment by daN4cat** [comment] 2016-07-05 13:07
I will try to collect the query dumps this eve to countercheck.
I know it's difficult but we are in at least two strong users in getting this, so something must be different somewhere.

I was like the story of generate_language.php some months ago.

I will even recheck DB and PHP version, maybe @odiea you can add your setup info too?

**Comment by jekkos** [comment] 2016-07-05 16:53
Tricky issue indeed. This might have something to do with the number of sales I have in my db. In my last test there weren't more than 8.

**Comment by daN4cat** [comment] 2016-07-05 19:08
My versions:

- Apache Version	2.4.18
- PHP Version		5.5.36
- Linux CentOS	2.6.32

**Comment by daN4cat** [comment] 2016-07-05 20:14
Here we go with my logs:

**searching last 7 days:**

SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-06-29' AND '2016-07-05'
GROUP BY `sale_id`
 LIMIT 20

**searching customer Frank:**

SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-06-29' AND '2016-07-05'
AND   (
`customer_last_name` LIKE '%frank%' ESCAPE '!'
OR  `customer_first_name` LIKE '%frank%' ESCAPE '!'
OR  `customer_name` LIKE '%frank%' ESCAPE '!'
OR  `customer_company_name` LIKE '%frank%' ESCAPE '!'
 )
GROUP BY `sale_id`
ORDER BY `sale_date` DESC

**removing the customer name**

SELECT `sale_id`, `sale_date`, `sale_time`, SUM(quantity_purchased) AS items_purchased, `customer_name`, `customer_company_name` AS `company_name`, SUM(subtotal) AS subtotal, SUM(total) AS total, SUM(tax) AS tax, SUM(cost) AS cost, SUM(profit) AS profit, `sale_payment_amount` AS `amount_tendered`, SUM(total) AS amount_due, (sale_payment_amount - SUM(total)) AS change_due, `payment_type`, `invoice_number`
FROM `ospos_sales_items_temp`
WHERE `sale_date` BETWEEN '2016-06-29' AND '2016-07-05'
AND `sale_id` = '46'
GROUP BY `sale_id`
 LIMIT 20


As you can see I get a spurious sale_id = 46. Now I'll try to go back from Sale model up to Controller to see where that comes from.

**Comment by daN4cat** [comment] 2016-07-05 20:20
Please note that as browser I use Chrome under Windows.

**Comment by daN4cat** [comment] 2016-07-05 20:45
OK, fixed.

**Comment by odiea** [comment] 2016-07-05 20:45
Windows 10
XAMPP
5.5.19 
[PHP: 5.5.19]

Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.5.19
•Database client version: libmysql - mysqlnd 5.0.11-dev 
•PHP extension: mysqli Documentation

Server type: MySQL
•Server version: 5.6.21 - MySQL Community Server (GPL)
•Protocol version: 10
•User: root@localhost
• Server charset:  UTF-8 Unicode (utf8)

**Comment by daN4cat** [comment] 2016-07-05 20:53
I believe this is now fixed, see my latest commit to master.

**Comment by daN4cat** [comment] 2016-07-05 21:12
The issue was that a NULL search was passed in is_valid_receipt, which was looking up an invoice with NULL field. The first sale with no invoice was returned as valid receipt id and so messing up things.

The usual !empty is better than isset.

**Comment by jekkos** [comment] 2016-07-05 21:20
Ok I guess I can't retest cuz it was already working fine :dancers:

**Comment by daN4cat** [comment] 2016-07-05 21:24
Which php version do you use?

**Closed** 2016-07-06 13:04 UTC
Labels: bug
