### ISSUE TITLE
Upgrade script from 2.3.2 giving errors

### ISSUE THREAD

**Issue by onyema3** [jekkos/opensourcepos#629] opened 2016-06-09 10:58 UTC
I have been running ospos ver 2.3.2 for sometime now and decided to upgrade to 3.0.0
While running the database upgrade scripts the i got error on the 2.4 to 3.0.0
![screen shot 2016-06-09 at 11 46 20 am 1](https://cloud.githubusercontent.com/assets/12876751/15927387/5d976b00-2e39-11e6-81a6-a58eb9570bbd.png)
Am i doing something wrong.
Please help

**Comment by daN4cat** [comment] 2016-06-09 11:06
It looks like you probably never run `2.3.1_to_2.3.2.sql` script.
So you must be on 2.3.2 without having ever ran that script.

Try running that first and of course `2.3.2_to_2.3.3.sql` and `2.3.4_to_2.4.sql` after that before you run `2.4_to_3.0.sql`

**Comment by onyema3** [comment] 2016-06-09 11:24
@daN4cat I just tried running 2.3.1_to_2.3.2.sql and it threw up this error
![231 to232](https://cloud.githubusercontent.com/assets/12876751/15928137/0bd57c4a-2e3d-11e6-9f40-d6f118f23193.png)

**Comment by daN4cat** [comment] 2016-06-09 13:35
You cut the error from your picture.

**Comment by onyema3** [comment] 2016-06-09 13:46
Error
SQL query:


INSERT INTO `ospos_app_config` (`key`, `value`) VALUES 
('barcode_content', 'id'),
('barcode_first_row', 'category'),
('barcode_second_row', 'item_code'),
('barcode_third_row', 'cost_price'),
('barcode_num_in_row', '2'),
('company_logo', ''),
('barcode_page_width', '100'),      
('barcode_page_cellspacing', '20'),
('receipt_show_taxes', '0'),
('use_invoice_template', '1'),
('invoice_default_comments', 'This is a default comment'),
('invoice_email_message', 'Dear $CU, In attachment the receipt for sale $CO'),
('print_silently', '1'),
('print_header', '0'),
('print_footer', '0'),

('print_top_margin', '0'),
('print_left_margin', '0'),
('print_bottom_margin', '0'),
('print_right_margin', '0'),
('default_sales_discount', '0'),
('lines_per_page', '25'),
('show_total_discount', '25');
MySQL said: Documentation

**Comment by onyema3** [comment] 2016-06-09 13:48
MySQL said: Documentation

#1062 - Duplicate entry 'barcode_content' for key 'PRIMARY'

**Comment by onyema3** [comment] 2016-06-09 13:50
Error
SQL query:

INSERT INTO ospos_app_config (key, value) VALUES
('barcode_content', 'id'),
('barcode_first_row', 'category'),
('barcode_second_row', 'item_code'),
('barcode_third_row', 'cost_price'),
('barcode_num_in_row', '2'),
('company_logo', ''),
('barcode_page_width', '100'),

('barcode_page_cellspacing', '20'),
('receipt_show_taxes', '0'),
('use_invoice_template', '1'),
('invoice_default_comments', 'This is a default comment'),
('invoice_email_message', 'Dear $CU, In attachment the receipt for sale
$CO'),
('print_silently', '1'),
('print_header', '0'),
('print_footer', '0'),

('print_top_margin', '0'),
('print_left_margin', '0'),
('print_bottom_margin', '0'),
('print_right_margin', '0'),
('default_sales_discount', '0'),
('lines_per_page', '25'),
('show_total_discount', '25');

MySQL said: Documentation

#1062 - Duplicate entry 'barcode_content' for key 'PRIMARY'

**Comment by daN4cat** [comment] 2016-06-09 16:29
Anyway, you should have done now so what if continue to upgrade with the other scripts?
Ignore the errors and keep going one after the other and see at the end if 3.0 works fine or you get errors.

**Comment by onyema3** [comment] 2016-06-09 16:46
Everything seems to be working except reports. When i try to generate any report i get this error
![screen shot 2016-06-09 at 5 44 20 pm](https://cloud.githubusercontent.com/assets/12876751/15938170/f8e8fbf2-2e69-11e6-95d8-0f79db71a44d.png)

**Comment by daN4cat** [comment] 2016-06-09 17:42
Run this from phpMyAdmin : ```
ALTER TABLE `ospos_receivings_items`
    ADD COLUMN `receiving_quantity` int(11) NOT NULL DEFAULT '1';
```

**Comment by onyema3** [comment] 2016-06-09 18:03
@daN4cat Thanks. It solved the report issues.
Upon more testing i noticed that if i goto takings and try to print a receipt more errors
![screen shot 2016-06-09 at 7 00 17 pm](https://cloud.githubusercontent.com/assets/12876751/15940604/a73bf196-2e74-11e6-8d79-c7f85814ae42.png)
and when i try to add a new customer errors pop up too
![screen shot 2016-06-09 at 7 00 51 pm](https://cloud.githubusercontent.com/assets/12876751/15940621/be1b0a5a-2e74-11e6-9c89-e630abeccd72.png)
Any help will be appreciated.
Thanks alot.

**Comment by daN4cat** [comment] 2016-06-09 18:13
have you run 2.4 to 3.0 upgrade with no issue?

Because it looks like this did hapen: 

> ALTER TABLE `ospos_customers`
>  ADD COLUMN `discount_percent` decimal(15,2) NOT NULL DEFAULT '0.00';

**Comment by onyema3** [comment] 2016-06-09 18:16
Still having issues with 2.4 to 3.0 upgrade 
![screen shot 2016-06-09 at 7 15 25 pm](https://cloud.githubusercontent.com/assets/12876751/15941097/a719adbe-2e76-11e6-9f78-b54457c13d52.png)

**Comment by daN4cat** [comment] 2016-06-09 18:26
It doesn't make sense to me.

The error you get it's because that field is missing in the table. 
Have you check the table to see the field is really there?

**Comment by onyema3** [comment] 2016-06-09 18:29
It's there...
![screen shot 2016-06-09 at 7 28 44 pm](https://cloud.githubusercontent.com/assets/12876751/15941523/7abd02b4-2e78-11e6-88a8-7cc1f6879447.png)

**Comment by daN4cat** [comment] 2016-06-09 18:42
Try to reload but we all upgraded and it's fine, so not sure what's wrong with your setup.

**Comment by onyema3** [comment] 2016-06-09 18:49
That means i'm stuck with version 2.3.2

**Comment by onyema3** [comment] 2016-06-09 19:05
@daN4cat 
I removed  lines 33 to 34 and lines 38 to 44 in the 2.4 to 3.0 upgrade scripts and it ran well.
Only issue i can see now is that when i goto Store config, General, Database Backup i get this error instead of a backup of the database
A PHP Error was encountered

Severity: Runtime Notice

Message: Only variables should be assigned by reference

Filename: controllers/Config.php

Line Number: 279

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 279
Function: _error_handler

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 136

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 137

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 138

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 139

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 140

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/masterss/system/core/Exceptions.php:272)

Filename: helpers/download_helper.php

Line Number: 141

Backtrace:

File: /Applications/MAMP/htdocs/masterss/application/controllers/Config.php
Line: 289
Function: force_download

File: /Applications/MAMP/htdocs/masterss/index.php
Line: 315
Function: require_once

PK���HK���*WQ	ospos.sql��oG�%��?Ewـ{�U��?�����Y򥨹��$Jj�ܡH-Iy�����8Y�Q��]%�uo�<wge�"�02#�ǉ��տ�N��{r<{~z���鋓����NgW7�n^�}���������_��W_=:y������ώ~�������W��__}�������m������^�m�۫ٯg�o~9�����ofO��Ξ�x��[��=�����?�<���䯳?�u��|�o��fv����O��������w�G���xr:{�����ǧ�t�n����������㧧����o�����/GO^?�}��������̓og��z��է������_lߟ]��l����?Ͼ���������������O�ξ;{{������?>�{r������_�����o������v{y�>���;���ίon_^_��}�7g���W׿��w�gu�������ξ�˛�nݷ-��{��^n�������os��n��/����ȯ���ox�������X����x��j{qq������{�q˻�����~�����n����tvqN3w�-o��Wo������.�����~o9�n���+ܵ���o��{��Q�����T���7W>�]�M:�t}�q{v9{t~���������b{3{r�e�����W������\���||�EƓOz���yp/��}��t}��|��˷�7��.�{~��m���9N�~��>���p���B����P��<� ��.��]~��.�Yu��lq�߬��o���o���o���o���o�aŻ��g��Ç?���.�w/?^�3��������٧�ۗ7gp�/�z��室���g�xY�������N�����~f~o�}�k�7����ξ,��~�;���7\�ou���\\�?�o������~�����/���`�/��痿^!Z»I��3}@�#���/�73�����י��_����(����"�u?����z�?��v��rvv{{���Qf��lg��7����3����N�����_��c\�]������˾��%�����K�;(e�E�������_l\�}>����>Υ����v{�ş������c��CB��qu�N�}���\]2z[��rU/֛/���x^���E��������K�Q�,�DƂo�����玾�/۳�w��.��n���K���{� �����̈����|Iz�ou{���>.���[d�w��x��旫������*�o��7��vW�g���?�����������7go>]�:�ٯ�'���4��o�����M���Ͼ�O\oo?]_"��8#��t{s�Eߑa��R��]�����囋Oo��ÿ�1޺����ۛ�7ۏgƮ�?~�E����*m����1�������Og��������拾-����D���;�~���5���� �r�{������ŧ_�F��+�+�66�|r����k�_�kk�/`WA��������fx!�.v�MU��@v�M��m������Ky_o������������c�.ȃ��tV�n/���������O]����W��X�uQ[&��Pu?�������X�3�va|��o�qC�T���V� _���S4��еi�6������w{Y�r����?<�M��ݾ��|r��!�8�!�q{����:?�ZH�$�ώ>R�����_�Mc;��������_������pu�vg��; �AY�բZ��?����]�����co�G:9����� �߲�g򳢝���n��V~�ϯ.]�)�ӽ�~�����������C�t�u��l?���ʯ���-�䇔߹���\�~H�m�&W�i������Ǡ�/�Ϗ?��ۍ��>�����d�� ��2r�?d��-~Hi�?�Sxq���c�O�_cr /N5���SM�ũ���+)<���ӿ�N���u�,&غ���z�u��o�L�XEn�⇜�[_L��/�n�Vr�H�uc2J$^��ޞ���^�E���ыc�CN��3��O'ǧ�~��O�'���0{r��t�V�ŏ�O>��=L�=~���O�L���ڽL�?{r���ש���TG����d�:Y����d�CF����N?��}�N}�⇌�!���R�e��X��Sȇ�ыc�7�~q��I������XT����m�z�X�o����g��o^o�ͻ��wr'���ݝ|�7���s�i�|],���UuP��r�v�y�n��go� �����4 �N>��{�={����.߾+�VU�:;�Wջ��M��@>�{�Ƶ��姜�]l_~/�߭V��쬬V�����u�c�G���W���ݾ9�~����/�����W����t��W3��7�g>��(A���	ج�/O�x����ǟ���|�@?�<����^>~ q��W���'9�^�%M��X�����c3}r�ߴ��]~�����7uj:b�����>������O�.���}�I�;��2��G��#�������� �C�"/v�0���?��v��.OE�͛��;�#/�����c"�\N��/K����v7����o���]��.%�٦!w��o>}�x!C�#�Ⱦ�O}���߽���*S��g������v�]}�NqWߴ #�����.�oF��7�z����#�Tqw�7F��w���]�Nq��|�ۜ#������N�w��Ǻ�;a�]��{w�߼ #���aĝ~��]�k�����y�.E����X��nQ�B}�Q}����v��דH J������j����N�w������>��������+䕨�G}^�����ݪ`�������k��j���kj�F�i�K��o���7%�K�Z�?_��ȏ )Q:�)�s���:	������;����䎭S?*/o�E`��6� (���NI�XV�Ϩ��K����P�Կ�����?ɍh��9���hO@�nM�J@Cy^�km�~���ju�R��g��̞�� �ջٿ{i/�7��Z���IR��! 0�A\��C�h?�����|�������p�W�z�q�g������}{>]���(}UA�ϖX��^}��Gi�����8����.>�N2��	����]����u� ��9���'���O�^7�J�G�Y���:8�NΗf��F%���!���+8/r%��~oHQ�����:,6�2�)�-ܹ�ʬ}(:^Z��땺>�H�sl����O(�>��%1�x���&O88t2 *��d� y�V�Y�$������{ط�g���v� a��s- ��ȮS���ˮ����H���tHbX b����u��!qL7�+��e"�Czr��/*�*�� [M�Y���>���t;C��~'�L!`�e��f���=�P{(W��<��Ã��楘'�J;��m�{�J1Px�v���M �9��>���g)���(��DL����~H�$�s ��)|�5�S*���� BΪO!��2m��S�ۄ���(T	Bd����!k!�pF�8��~�6M��������!��	#�w�(R���,��)_�88<��=���2��P�<�|�-`��8����R*2����w*�Ʉ=��2:��!�3�ׂS����}�xLú+/�S��b��S%~�L�4�ò���/���"$lX��N܆��_��hMۗ���y)��C��M��X��H�i���Cv��l����PN�=�|+��S��|'ҕ���C���X _5_�-��ļ7a�zsXJ#�xG�?�-�%�~MaZ�\3�9���:�r?r��f؍0�M������=�|�>Y(|n߲|����5Zx ��Gk��g"��	�

**Comment by daN4cat** [comment] 2016-06-09 21:11
I would restart from scratch, running this as first:

Run this from phpMyAdmin :

> ALTER TABLE ospos_receivings_items
> ADD COLUMN receiving_quantity int(11) NOT NULL DEFAULT '1';

and then all the other scripts one after the other and see if everything goes right.

**Comment by daN4cat** [comment] 2016-06-09 21:18
One extra thing.... when you move to 2.4, have you changed the configuration of your DB to be 

> $db['default']['dbdriver'] = 'mysqli';

**Comment by onyema3** [comment] 2016-06-09 21:20
No, How do i do that?
Another thing i noticed right now is that the messages menu is missing. Its only in store config
![screen shot 2016-06-09 at 10 19 09 pm](https://cloud.githubusercontent.com/assets/12876751/15946800/53607d96-2e90-11e6-880b-6173e1bdff40.png)

**Comment by daN4cat** [comment] 2016-06-09 21:20
In general check the new configuration template when moving to the newer version starting with 2.4.

Also make sure you don't have old controllers and models in the same directory of the new code otherwise you get mix ups. The new code needs to go to a new dir.

**Comment by daN4cat** [comment] 2016-06-09 21:23
in application/config make sure to use the new config.php and database.php starting with 2.4.
Copy over the settings you had in the old, but keep the new files layout, just replace the values.

**Comment by daN4cat** [comment] 2016-06-09 21:25
But for sure the database backup doesn't work because of the old driver.

**Comment by onyema3** [comment] 2016-06-09 21:25
Basically what i did was to take the new masters 3.0.0 and installed it and try to the database from my 2.3.2 installation to it?

**Comment by onyema3** [comment] 2016-06-09 21:41
I would restart from scratch, running this as first:

Run this from phpMyAdmin :

ALTER TABLE ospos_receivings_items
ADD COLUMN receiving_quantity int(11) NOT NULL DEFAULT '1';
and then all the other scripts one after the other and see if everything goes right.

Followed this approach, all the upgrade scripts ran without issues.
The problem now is that database backup from store config still comes up with the error above and message menu missing like the above attached file

**Comment by daN4cat** [comment] 2016-06-09 21:57
And the configuration is correct with mysqli (pay attention to the final i)

**Comment by onyema3** [comment] 2016-06-09 22:03
Yes it is

**Comment by daN4cat** [comment] 2016-06-09 22:18
Message menu is a question of permissions.

Maybe you should check that your account has all the permissions, that might be another reason for some of the issues.

**Comment by onyema3** [comment] 2016-06-09 22:22
Message menu back with permission, only problem left is the database backup from store config

**Comment by daN4cat** [comment] 2016-06-10 07:47
You shouldn't have had the permission issue with Messages because this is in the upgrade script:

> INSERT INTO `ospos_permissions` (`permission_id`, `module_id`) VALUES
>  ('messages', 'messages');
>  
> INSERT INTO `ospos_grants` (`permission_id`, `person_id`) VALUES
>  ('messages', 1);

unless you are using a different user than the default admin.

**Comment by daN4cat** [comment] 2016-06-10 07:53
About the DB backup issue, that line is a straight call to the support to do the backup:

>     		$prefs = array(
> 				'format' => 'zip',
> 				'filename' => 'ospos.sql'
>     		);
>     		 
>     		$backup =& $this->dbutil->backup($prefs);

so it must be to do with your setup and you need to debug and find out what's wrong.
I don't use windows and MAMP. Maybe somebody else can help here?

**Comment by daN4cat** [comment] 2016-06-10 07:56
About the Takings and edit of the sale, is that the only thing you cannot edit? I mean can you edit Customers, Giftcards, Items, Item Kits and etc?

You need to open an firebug / Inspector window to understand what kind of error you get that it's preventing the editing.

One thing you should check is the Stock Location in Store Config, is that showing OK?
For instance, can you go to Items and open inventory forms with no issue? The one with the log should show Stock locations in a dropdown.

**Comment by onyema3** [comment] 2016-06-10 12:14
The permission problem was because i was using another user account.
I'm still investigating what the problem is. Every other form works except editing a sale in takings and still have the backup issue too.
Thanks so much for your help so far

**Comment by daN4cat** [comment] 2016-06-10 12:22
Give a try disabling the invoice support from Store Config and see if that makes any kind of difference in Sale editing.
Earlier I mentioned the location but then I better checked and sorry there is nothing like that in that form.
Actually is the payment list that is used.

Try and edit a new sale and not something old to see if that makes a difference.

**Comment by onyema3** [comment] 2016-06-11 01:16
did that and nothing changed

**Comment by daN4cat** [comment] 2016-06-11 08:48
OK, to understand what type of error you get from Takings, go on the edit icon and right click with your mouse, now select open in a new window and instead of the modal dialog box you should get the view without styling. If there is any error you should able to see.

The url in the new tab should look like: https://<web server>/<my path>/sales/edit/12

**Comment by onyema3** [comment] 2016-06-11 09:10
this is what i get
![screen shot 2016-06-11 at 10 09 29 am](https://cloud.githubusercontent.com/assets/12876751/15984258/b29d3114-2fbc-11e6-8237-6bf63bf7c5d1.png)

**Comment by daN4cat** [comment] 2016-06-11 09:18
OK, can you please check if you have the file application/views/sales/form.php?

**Comment by onyema3** [comment] 2016-06-11 09:23
Yes, I can see form.php

**Comment by daN4cat** [comment] 2016-06-11 09:39
That cannot be wrong, you must have something strange with your setup.
Are you sure you didn't copy new code over old code and you have a completely clean setup with anything unusual?

That form is called like this: 		`$this->load->view('sales/form', $data);`

It's a straight call.

**Comment by daN4cat** [comment] 2016-06-11 09:49
Other thing you could do is make a new install in a new database and compare the structures "old upgraded to latest" with "fresh new install".

**Comment by onyema3** [comment] 2016-06-11 09:58
I'll do that but I'm surprised that this is having issues

On Jun 11, 2016 10:50 AM, "FrancescoUK" <notifications@github.com> wrote:
>
> Other thing you could do is make a new install in a new database and
compare the structures "old upgraded to latest" with "fresh new install".

**Comment by daN4cat** [comment] 2016-06-11 10:02
If you press F12 on Google Chrome you should get the Inspector window when you get in that error page, what error do you see.

But besides this debug steps you need to understand what's different with your setup as I cannot get it from remote.

**Comment by jekkos** [comment] 2016-06-11 11:01
Could be a file permission problem on your server? At least it looks like your form contents is not loaded properly, think you should check apache error logs to see what went wrong

**Comment by onyema3** [comment] 2016-06-11 11:44
@jekkos what am i to look out for in the apache log
![screen shot 2016-06-11 at 12 42 03 pm](https://cloud.githubusercontent.com/assets/12876751/15984873/2350a160-2fd2-11e6-8183-81174fad07e5.png)
The only thing i noticed when i try to edit a sale are these lines
[Sat Jun 11 10:06:51 2016] [notice] child pid 61039 exit signal Segmentation fault (11)
[Sat Jun 11 10:06:54 2016] [notice] child pid 61056 exit signal Segmentation fault (11)
[Sat Jun 11 10:06:56 2016] [notice] child pid 61054 exit signal Segmentation fault (11)
[Sat Jun 11 10:06:58 2016] [notice] child pid 61055 exit signal Segmentation fault (11)
[Sat Jun 11 10:07:01 2016] [notice] child pid 61050 exit signal Segmentation fault (11)
[Sat Jun 11 10:07:46 2016] [notice] child pid 61067 exit signal Segmentation fault (11)
[Sat Jun 11 10:07:48 2016] [notice] child pid 61047 exit signal Segmentation fault (11)
[Sat Jun 11 10:07:50 2016] [notice] child pid 61043 exit signal Segmentation fault (11)
[Sat Jun 11 10:07:57 2016] [notice] child pid 61045 exit signal Segmentation fault (11)
[Sat Jun 11 10:08:29 2016] [notice] child pid 61071 exit signal Segmentation fault (11)
[Sat Jun 11 10:09:32 2016] [notice] child pid 61066 exit signal Segmentation fault (11)
[Sat Jun 11 12:33:57 2016] [notice] child pid 61111 exit signal Segmentation fault (11)
[Sat Jun 11 12:33:59 2016] [notice] child pid 61112 exit signal Segmentation fault (11)
[Sat Jun 11 12:35:00 2016] [notice] child pid 61065 exit signal Segmentation fault (11)

**Comment by onyema3** [comment] 2016-06-11 11:53
@daN4cat This is what the inspect window looks like..
![screen shot 2016-06-11 at 12 52 17 pm](https://cloud.githubusercontent.com/assets/12876751/15984929/7d775142-2fd3-11e6-846b-399460cd7c3d.png)

**Comment by daN4cat** [comment] 2016-06-11 12:11
I wouldn't that this issue is due to the BC math library that is missing in your server.

Also what's the error_log in the ospos application dir saying?

**Comment by daN4cat** [comment] 2016-06-11 12:11
And what version of MySQL and PHP do you use?

**Comment by onyema3** [comment] 2016-06-11 12:18
Php 5.3.29, apache 2.2.29
I did a clean install and still same issues with takings and database backup
On Jun 11, 2016 1:11 PM, "FrancescoUK" <notifications@github.com> wrote:

I wouldn't that this issue is due to the BC math library that is missing in
your server.

Also what's the error_log in the ospos application dir saying?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/629#issuecomment-225357084>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMR7z0rcY-DnJ2YmgGwy_A43a2FSu20aks5qKqXagaJpZM4Ix2o8>
.

**Comment by daN4cat** [comment] 2016-06-11 12:29
and error_log?

By this is an issue with your setup, not OSPOS anymore. So I close.

**Comment by daN4cat** [comment] 2016-06-11 13:27
You need php 5.5 at least, might still be fine with 5.4 but that was in the read me. I assumed you read it.

**Comment by daN4cat** [comment] 2016-06-11 13:28
You need php 5.5 at least, might still be fine with 5.4 but that was in the read me. I assumed you read it.

**Comment by onyema3** [comment] 2016-06-11 13:33
Yes I read the read me file
On Jun 11, 2016 2:27 PM, "FrancescoUK" <notifications@github.com> wrote:

You need php 5.5 at least, might still be fine with 5.4 but that was in the
read me. I assumed you read it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/629#issuecomment-225361706>,
or mute the thread
<https://github.com/notifications/unsubscribe/AMR7zyKoKCDfe6G-fwIM0Pz88-k3SWGpks5qKrfcgaJpZM4Ix2o8>
.

**Comment by onyema3** [comment] 2016-07-31 04:54
$prefs = array(
          'format' => 'zip',
          'filename' => 'ospos.sql'
      );

      $backup =& $this->dbutil->backup($prefs);

The above always throw up error but with a slight change everything works
      $prefs = array(
          'format' => 'zip',
          'filename' => 'ospos.sql'
      );

      $backup = $this->dbutil->backup($prefs);

**Comment by daN4cat** [comment] 2016-07-31 10:24
Ok, probably that's due to php version.

**Comment by onyema3** [comment] 2016-07-31 13:36
Oh I see.
Thanks for all your help

**Comment by odiea** [comment] 2016-07-31 13:44
$backup =& $this->dbutil->backup($prefs); What is the purpose of & in this code?

**Comment by onyema3** [comment] 2016-07-31 14:12
That's for admin backup

**Comment by odiea** [comment] 2016-07-31 14:28
https://www.codeigniter.com/userguide3/database/utilities.html#usage-example appears to have eliminated the & in it's code now.
// Load the DB utility class
$this->load->dbutil();

// Backup your entire database and assign it to a variable
$backup = $this->dbutil->backup();

// Load the file helper and write the file to your server
$this->load->helper('file');
write_file('/path/to/mybackup.gz', $backup);

// Load the download helper and send the file to your desktop
$this->load->helper('download');
force_download('mybackup.gz', $backup);

**Comment by daN4cat** [comment] 2016-08-01 07:32
@onyema3 @odiea thanks for the help with figuring out the root cause of this issue, I should have spent a bit of more time to check CI3 upgrades better.
It's fixed and in master now. If no issue after your test we can close.

**Comment by onyema3** [comment] 2016-08-01 08:39
Fixed

**Closed** 2016-08-01 10:45 UTC
Labels: bug
