### ISSUE TITLE
Quote Register Mode Deducting from Item 

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1354] opened 2017-06-23 12:29 UTC
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
OSPOS VERSION 3.1.0 commit hash:4f5ad57
MySQL version is 5.6
PHP version is at least 5.6

OS: WINDOWS

### Actual behaviour
When using the quote register mode in sale page the system deducts from the item in stock which is not supposed to be since am only preparing a quotation  

### Steps to reproduce the issue

**Comment by odiea** [comment] 2017-06-23 17:04
It also appears now when you suspend a sale it removes it from Inventory and after you unsuspend it and cancel the sale it does not return it back into the Inventory. This is a normal sale that has been suspended. No quote or Invoice attached to it.

**Comment by SteveIreland** [comment] 2017-06-24 20:42
I'm assuming that everyone agrees that quotes should not affect inventory.  However, that brings up an interesting little twist since I'm dealing with work orders.  A product added to a work order SHOULD reserve/reduce inventory since the item will be used to satisfy the job.  On another note I've been instructed to NOT remove work orders from the system. Normally I would since a work order and quote is, as far as OSPOS is concerned, essentially the same pre-sale stage in the workflow. 

So for this fix, if the mode is "work order" then I will continued to affect inventory.  If the mode is quote then inventory will not be affected.

**Comment by odiea** [comment] 2017-06-24 21:09
Are you now adding another feature "work order"? I think Quotes should not change Inventory Items.

**Comment by SteveIreland** [comment] 2017-06-24 21:50
Yes.  I'm still wondering what the rules should be for  work orders since they can be in progress for weeks and inventory can be consumed at any point in the life  of the work order.  Reality can be a bit complex so I'm going to go ahead and change both to not affect inventory.

**Comment by daN4cat** [comment] 2017-06-26 04:56
I merged @SteveIreland's fix, please check and confirm it's all fixed and no regressions.

**Comment by daN4cat** [comment] 2017-06-26 07:29
@ebenezery4 could you please test and confirm it's now fixed?

**Comment by ebenezery4** [comment] 2017-06-27 01:22
Ok fixed!

**Closed** 2017-06-27 05:21 UTC
Labels: bug
