### ISSUE TITLE
Zip Code in Customer no longer does an auto search.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1471] opened 2017-08-13 20:52 UTC
I down loaded the current unstable version and it appears that the auto find and fill for Customer Zip code no longer functions

**Comment by daN4cat** [comment] 2017-08-13 21:05
@jekkos it could be that the upgrade of jquery to 2.1.4 had an impact on nominatim.autocomplete.js. So far that's the only issue we found and if you could fix it it would be great to close 3.1.0.

**Comment by jekkos** [comment] 2017-08-14 08:26
Ok indeed probably due to that.. this code is not the most simple but will have a look

**Comment by jekkos** [comment] 2017-08-15 22:01
Should be fixed in latest build

**Comment by jekkos** [comment] 2017-08-16 16:44
Was wondering, so now the fix contains only original js source, no more minified version. Maybe we should add a default apache rewrite rule to use ?debug=true in development mode.. so then we don't need to rebuild the minified from the source once a change is done...

But this rewrite rule should then be disabled again by the  build itself

**Comment by daN4cat** [comment] 2017-08-16 21:01
If you are a developer I guess you rebuild your stuff, right?

**Comment by jekkos** [comment] 2017-08-16 21:10
Yes actually, another possibility is adding grunt watch on the js source. It then monitors files for changes and rebuilds once something changes. Or a git post update hook could do as well..

**Comment by odiea** [comment] 2017-08-16 21:21
In my case all I do is download the current zips and test them. I choose not to install composer or other needed files for the github repository.

**Comment by jekkos** [comment] 2017-08-16 22:31
Ok makes sense as endusers will probably also do it that way

**Comment by daN4cat** [comment] 2017-08-17 13:10
BTW this nominatim function still cannot find the correct ZIp/Post code in London. I type my home address post code and no results.
I remember we had a problem like that in the past but then it was fixed?
@odiea does it ring a bell to you? Does it work fine in the US?

**Comment by odiea** [comment] 2017-08-17 13:20
It currently appears to be just working on numeric zip codes. SW1A 1AA Buckingham palace did not show anything. What I recall was it would show 2 or 3 of the same location and that was eventually fixed..

**Comment by jekkos** [comment] 2017-08-18 14:15
So works like before or is there still a regression?

**Comment by odiea** [comment] 2017-08-18 14:28
I think this feature only works with US zip codes.

**Comment by odiea** [comment] 2017-08-18 15:10
I changed localisation to en-gb and country code to gb and it worked on zip codes.

**Comment by daN4cat** [comment] 2017-08-18 17:25
Let me check again then...

**Comment by daN4cat** [comment] 2017-08-18 19:32
Check and I have en_GB and gb but still doesn't find any known to me post code.

**Comment by daN4cat** [comment] 2017-08-19 10:14
I checked few web posts and this nominatim thing works partially, many have problems with addresses in the UK. So not sure this will ever work at least in the short term.
I also taken a query and added ?debug=1 to get a dump from nominatim, and despite passing the correct ?countrycodes=gb the internal query uses "be":

> ["country_code"]=> string(2) "be"

**Comment by daN4cat** [comment] 2017-08-19 10:17
Maybe the reason of the GB being in Belgium is because I remember at the time I used to live in Brussels that GB was a supermarket chain. Probably there are still POIs marking GB supermarkets...
just speculating, because when I go to the web site and perform a search I get a GB in Ghent Belgium!

**Comment by jekkos** [comment] 2017-08-27 12:50
Hm ok I just had a brief look and after setting countrycode to gb, it does seem to search for addresses in the uk. It does look like the output format changed a bit, as you said I do see some POI information being returned from time to time.

maybe I need to refine the query further and check how the contract specifications were changed

**Comment by jekkos** [comment] 2017-08-29 20:51
I don't really think the search is  broken as it is now, and won't consider this critical enough to stop us from releasing 3.1. Other opinions? Otherwise I'll change the milestone.

**Comment by odiea** [comment] 2017-08-29 20:52
Works good enough for me.

**Closed** 2017-08-29 21:44 UTC
Labels: bug
