### ISSUE TITLE
Bug (?): Error when creating a new item without image

### ISSUE THREAD

**Issue by marteserede** [jekkos/opensourcepos#36] opened 2015-02-15 16:20 UTC
When I create a new item and do not select an image, it does not work.
Does it maybe has something to do with the fact, that _handle_image_upload() is always called and that there is no check whether $_FILES['item_image'] is empty or not?
Or is something with my setup wrong?

**Comment by jekkos** [comment] 2015-02-16 07:15
can you see what the response from the server in firebug/chrome console when creating the item? In my case it seems to work fine.

**Comment by marteserede** [comment] 2015-02-16 13:13
Funnyly it only happens if I choose Indonesian as the language.
First I get the error that the language file upload_lang.php was not found, so I created it, then I get the error message "upload_no_file_selected".
I tried it now a couple of times changing the language, enterin the exact same data and always getting the error "upload_no_file_selected".

**Comment by jekkos** [comment] 2015-02-17 09:43
this problem occurs because the upload helper explicitly loads an upload language file. This file should be present in the system languages folder but currently is not. I have created most of the missing langauge folders in system now and added the upload_lang (in english tho) in there. Currently I don't really see a better workaround for this except for overriding the load() function in Lang.php itself.

**Comment by jekkos** [comment] 2015-02-17 09:45
It looks like CI was designed to have just one language at the time in memory and fallback to english might be a bit hard to implement. However I did a patch now that will just return the language label line with a (TBD) appended to show the users that the translation is not present (and hopefully motivates them to add it and send me some pull requests)

**Comment by jekkos** [comment] 2015-02-17 10:16
shoud be fixed in 40eef74aa0ad953a4ae1eaaefa726cf469ea3536

**Closed by jekkos** 2015-02-17 10:16 UTC
Labels: bug
