### ISSUE TITLE
Sales receipt not working

### ISSUE THREAD

**Issue by asakpke** [jekkos/opensourcepos#237] opened 2015-11-20 17:09 UTC
Sales receipt not working after finishing sales or opening it from reports :(
After debugging I comes to the point that bar code generation is making problem. I don't know how to fix. 

![pos sales receipt error](https://cloud.githubusercontent.com/assets/7318102/11306342/f22b5250-8fd2-11e5-853b-e58f5212ceb7.png)

**Comment by cpl2015** [comment] 2015-11-20 17:20
If invoice is working, try this
Download a fresh copy and replace the the views/sales/receipt.php file with downloaded one.

**Comment by jekkos** [comment] 2015-11-23 08:14
Can anyone reproduce this in the latest version?

**Comment by odiea** [comment] 2015-11-23 13:02
No. I have not seen this problem for quite a while. Maybe he didn't get a good download or do a proper upload.

**Comment by jekkos** [comment] 2015-11-23 14:31
Ok so this is probably due to a modification done locally. Try to reset the git repository and database and check if the error persists.

**Comment by jekkos** [comment] 2015-11-27 07:47
Will close this issue for now as it can't be reproduced

**Closed by jekkos** 2015-11-27 07:47 UTC
