### ISSUE TITLE
Having problem setting up the system

### ISSUE THREAD

**Issue by endangurura** [jekkos/opensourcepos#243] opened 2015-11-30 19:53 UTC
I'm having problems in setting up the opensourcepos system. On Apache webserver, the receipt and invoice views are not working, they are showing a blank page, and no error is displayed even in apache error.log the only thing that looks like an error is in access.log "GET /sales/receipt/1 HTTP/1.1" #500 8073 "http://lcalhost/sales/manage". I tried to set it up using nginx too, the invoice and receipt views are working but it has its own issues a 500 internal server error.  GET http://localhost:8000/items/view/-1/width:450/random:1448912295408 500 (Internal Server Error)         opensourcepos.min.js?rel=cb9e5b15ec:6 (line 6 of minified version or line 8434 the full version: xhr.send( ( s.hasContent && s.data ) || null );). This is causing the modal view (new and import forms) to display and empty modal window. Can someone help me to figure out what's going wrong here.
Thanks.

**Comment by odiea** [comment] 2015-11-30 21:25
Did you do any modifications to the program prior to uploading it. What system are you using linux or Windows. There was another issue like this reported but it cannot be reproduced. So any helpful info on your side would be much appreciated.

**Comment by endangurura** [comment] 2015-11-30 21:34
I didn't do any modification, I just followed the installation instructions. I'm using Linux. To reproduce it, you can try to upload to any LAMP server or LEMP server.

**Comment by odiea** [comment] 2015-11-30 21:38
What Linux server. I currently have it running on Ubuntu server version 14.04.3 and have no issues.

**Comment by jekkos** [comment] 2015-12-01 09:39
Good point, translations might cause issues from time to time, especially if special characters aren't properly escaped in javascript (which is probably the issue here).

**Comment by endangurura** [comment] 2015-12-03 13:37
I tried it on a couple of Linux distros, Gentoo and FreeBSD with Nginx they all have the same javascript issues. Centos and Ubuntu desktop 14.04.3 with Apache They also have same issues of 500 internal server error on GET localhost/opensourcepos/index.php/sales/complete.  I tried it on a VPS with Ubuntu LAMP it worked perfectly, so I was wondering what might be the difference between the Ubuntu server on the VPS and the local desktop version installation that is making it to break. For translation I'm using the english version.

**Comment by jekkos** [comment] 2015-12-03 13:51
Could you post the exact server respones for the status code 500?

**Comment by endangurura** [comment] 2015-12-03 13:58
There's no error log in the error.log, the only thing that shows that there's a problem is the access.log and the web console.
127.0.0.1 - - [03/Dec/2015:16:54:01 +0300] "POST /opensourcepos/index.php/sales/complete HTTP/1.1" **500** 1134 "http://localhost/opensourcepos/index.php/sales/add_payment" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0"

**Comment by jekkos** [comment] 2015-12-03 14:48
Can you check in the browser if there's anything else returned from the server?

Try to use chrome developer tools or firebug to get the full response for this request.

**Comment by endangurura** [comment] 2015-12-03 22:49
XHR Loaded (complete - 500 Internal Server Error - 69.65700000000652ms - 703B)
http://192.168.1.9/sales/complete?comment=
Object {startedDateTime: "2015-12-03T22:34:03.045Z", time: 69.65700000000652, request: Object, response: Object, cache: Object…}cache: Object__proto__: Object__defineGetter__: __defineGetter__()arguments: nullcaller: nulllength: 2name: "__defineGetter__"__proto__: ()<function scope>__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()connection: "14935"pageref: "page_17"request: ObjectbodySize: 8cookies: Array[1]headers: Array[13]headersSize: 957httpVersion: "HTTP/1.1"method: "POST"postData: ObjectqueryString: Array[0]url: "http://192.168.1.9/sales/complete"__proto__: Objectresponse: Object_transferSize: 703bodySize: 0content: Objectcompression: 0mimeType: "text/html"size: 0__proto__: Objectcookies: Array[1]headers: Array[7]0: Objectname: "Date"value: "Thu, 03 Dec 2015 22:34:02 GMT"__proto__: Object1: Object2: Object3: Objectname: "Set-Cookie"value: "ci_session=a%3A4%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%226d8f3a5aa53d61c8e4810ebbb5429a00%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A11%3A%22192.168.1.5%22%3Bs%3A10%3A%22user_agent%22%3Bs%3A103%3A%22Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F47.0.2503.0+Safari%2F537.36%22%3Bs%3A13%3A%22last_activity%22%3Bi%3A1449182026%3B%7D30d83646f044aae4d880dc067477d5906e8da365; expires=Sat, 02-Dec-2017 22:34:03 GMT; Max-Age=63072000; path=/"__proto__: Object4: Object5: Object6: Objectlength: 7__proto__: Array[0]headersSize: 703httpVersion: "HTTP/1.0"**redirectURL: ""status: 500statusText: "Internal Server Error"**__proto__: ObjectstartedDateTime: "2015-12-03T22:34:03.045Z"time: 69.65700000000652timings: Object__proto__: Object

**Comment by jekkos** [comment] 2015-12-04 09:02
Is this the complete error message? Might be better to make a screencap?

**Comment by endangurura** [comment] 2015-12-04 18:36
![screenshot from 2015-12-04 21-31-49](https://cloud.githubusercontent.com/assets/6840268/11597797/068c2f42-9acf-11e5-8bfc-15435443ca49.png)

**Comment by jekkos** [comment] 2015-12-07 11:44
There's no real useful information in there. You mention issuing a GET on /complete in sales controller, this won't work as only data can be posted to that method. Maybe try to attach a debugger to the php server to see where the error is thrown.

**Comment by daN4cat** [comment] 2015-12-30 13:38
I see no progress since a month, should we close? There were no other reports of similar issues.

**Comment by jekkos** [comment] 2016-01-01 16:18
I couldn't reproduce this either, so I'll close it for now.

**Closed by jekkos** 2016-01-01 16:18 UTC
Labels: question
