### ISSUE TITLE
Issue or question about Receipts and invoices

### ISSUE THREAD

**Issue by pablos1rvent** [jekkos/opensourcepos#541] opened 2016-05-10 08:29 UTC
Hello guys

I'm working hard on this project (Sales Manager for my Shop) and I have a issue that maybe can be dangerous for my business project.

In Spain, we have a law that says "All the receipts and invoices printed must be saved in the server for almost 4 years". Okey, all right there.

The problem comes when I modify a customer or a item, this save and the Invoice with the Receipt saves with the new info. The thing is that I can't have 2 different receipts or invoice about the same sale.

If a customer bought a item with 100€ and I change the price to 120€, when he wants again the invoice, he is gonna get the receipt with the 120€ item.

I hope you can understand me,

Greetings.

**Comment by RamkrishnaMondal** [comment] 2016-05-10 17:31
Have you tested it ? It will not change to 120, just try yourself.

**Comment by daN4cat** [comment] 2016-05-10 17:56
Once you issue a receipt or invoice, it's issued. No change later outside some small fixing.

It's better to return the sale and issue a new one if the change is bigger (e.g. change of total)

**Comment by pablos1rvent** [comment] 2016-05-10 19:58
@RamkrishnaMondal Okey I wrong in the explanation xD

The thing is when I change the name of the customer or the name of the item, don't stay, changes if I change the customer or the name of the item. But the price remains. That's pretty good. 

Is there any way to fix that?

Thanks! @daN4cat

**Comment by odiea** [comment] 2016-05-10 20:02
You might consider suspending the Sale until your customer can make up his or her mind about what they want to purchase. Just a thought.

**Comment by pablos1rvent** [comment] 2016-05-10 20:04
@odiea That would be great, but that's not work for me. 
Here: https://demo.phppointofsale.com/
I think is OSPOS but a better version (200$ for the code, they are crazy), and they can edit a sale.

What is your opinion about this?

**Comment by pablos1rvent** [comment] 2016-05-10 20:08
@odiea You don't understand me.

I want to save the name and the info of the customer in the SQL when the receipt or the invoice is printed, but if I change the name of the customer, the invoice or the receipt does not change and stay with the old name. I don't know if you understand me, but Is a little strange to explain here.

**Comment by odiea** [comment] 2016-05-10 20:13
I do understand. The database is setup to use a unique Sale id number. Only 1 sale can have that number and that is why you cannot change a receipt or Invoice in OSPOS. Currently there is no option to do that. Yes you can buy PHPPOS and possibly change it to your hearts content. I do not know what their restrictions are. They have paid programmers doing the work. OSPOS is all volunteer work done by programmers helping out the community.

**Comment by pablos1rvent** [comment] 2016-05-10 20:16
@odiea Yeah, I agree, I was asking if there is possible to do that, if is not possible, okey.

**Comment by odiea** [comment] 2016-05-10 20:19
You can ask Jekkos if you can pay him to add that feature and then donate it back to the community.

**Comment by pablos1rvent** [comment] 2016-05-10 20:22
@odiea Thanks for the advice, I would consider to do that ^_^
Anyways this issue is different from the other lol

**Comment by odiea** [comment] 2016-05-10 20:24
I do get lost with all the question and issues lately.

**Comment by pablos1rvent** [comment] 2016-05-10 20:24
@odiea Don't worry, you are doing a great job asking me :D

**Comment by bkrajendra** [comment] 2016-05-10 22:13
one question, who is the creator of OSPOS?
PHPPOS looks same as OSPOS and the owner there says he is the creator of it.
What's the real story?

**Comment by odiea** [comment] 2016-05-10 22:29
I believe He was one of the original programmers. He then split off to PHPPOS. After that you can see who contributed if you open the Copy file in the main directory.

**Comment by daN4cat** [comment] 2016-05-11 03:27
Everything was in Github, I still have copy of the original as a fork and the only one with all the history.
Then pappastech kept going as open source under OSPOS name and PHPPOS became a commercial distribution.
Nowadays the two diverged so there is just a common root and some common code e similar functionality but with the time common parts will be less and less.

**Comment by jekkos** [comment] 2016-05-11 10:54
I never really found the original github copy. Actually I started off with what was on sourceforge at that time (which didn't include any of the original history). Might be nice to restitch the repo back together to put it back in place.

**Comment by jekkos** [comment] 2016-05-11 10:54
@daN4cat Would you mind to share a copy of that code with me?

**Comment by daN4cat** [comment] 2016-05-11 12:28
@jekkos it's in github visible under my name

**Comment by daN4cat** [comment] 2016-05-11 12:31
BTW it's too old, we went already off track. I just planned to check the MailChimp part but it needs updating anyway.

**Comment by bkrajendra** [comment] 2016-05-11 12:37
Yes im also using this earlier from sourceforge. But then recently found this github repo.
I hope there should not be any copyright issue.

**Comment by daN4cat** [comment] 2016-05-12 21:02
The copyright issue with OSPOS is only if you don't respect the current copyright, which means that if you scrap away other people's work and name to place your name on it the you have a problem.

I stating this because we already had few cases of people taking the code, removing names and copyright and place their company name on it and pretend it's theirs.

**Comment by jekkos** [comment] 2016-05-13 08:13
@daN4cat I know that this kind of practice occurs often. Is there anything we can do in terms of enforcing copyright on those rebranded installs?

**Comment by daN4cat** [comment] 2016-05-13 08:24
I will investigate what is doable.

**Comment by daN4cat** [comment] 2016-05-13 15:44
This discussion looks a duplicate of #542

**Closed by daN4cat** 2016-05-13 15:44 UTC
Labels: question
