### ISSUE TITLE
When adding a new item

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#147] opened 2015-09-14 21:14 UTC
It appears I lost the drop down list for item name when I go to add new item. All other lists work ok. This happens with IE,google,and pale moon but not Firefox. Is there something in Firefox that retains the items name. I can see in the code that there is no suggestion for name.

**Comment by jekkos** [comment] 2015-09-15 20:06
Is this in the item popup box itself? In that case it will rather be a browser bug as to my knowledge there's no autocomplete code for item name in the edit form

**Comment by odiea** [comment] 2015-09-15 20:33
When I add a new item (Firefox is my browser of choice) Firefox apparently retains the recent names I put in so it appears that there is a drop down list for Item Name. The orb does not show like in Category.

**Comment by daN4cat** [comment] 2015-09-16 14:28
Shall we close this as not a bug or invalid?

**Comment by odiea** [comment] 2015-09-16 14:34
Yes Please do.

**Closed** 2015-09-16 16:41 UTC
