### ISSUE TITLE
PDF Email Issue

### ISSUE THREAD

**Issue by saurabh261187** [jekkos/opensourcepos#494] opened 2016-04-21 14:50 UTC
Can someone shed some light on why the Email reciept is looking all messed up ? What are the basic checks I should do to rectify this.

![image](https://cloud.githubusercontent.com/assets/15091342/14713341/60340b54-07fe-11e6-9c4f-24e82f044df4.png)

**Comment by daN4cat** [comment] 2016-04-21 15:05
Duplicate of #442.

Please check existing issues before opening a new one. By the way that's invoice not receipt over email. Receipt over email is fine as I fixed in #442. Invoice not, and needs an owner.

**Closed by daN4cat** 2016-04-21 15:05 UTC
Labels: duplicate

**Comment by saurabh261187** [comment] 2016-04-21 15:19
Hello daN4cat ,
Thanks for the reply. This is the PDF Invoice that is attached to the Email reciept.
Do I replace the three files : 
application/views/sales/receipt.php
application/views/sales/receipt_email.php
css/receipt.css
to sort this problem ?

**Comment by daN4cat** [comment] 2016-04-21 15:33
My fix is for 3.0.0, so not sure which version you use.

**Comment by daN4cat** [comment] 2016-04-21 15:36
And by the way, as said the invoice over email is not fixed. So what you reported is that problem.

**Comment by jekkos** [comment] 2016-04-21 15:37
@saurabh261187 You're using a version under development so it's normal that there are bugs present.

There's a direct php view for the invoice. I think it's at sales/invoice_email/<sale_id> check the html/css in that view and try to figure why it's not showing properly.

**Comment by saurabh261187** [comment] 2016-04-21 19:18
I am using version 2.3.4 , earlier versions of ospos released about 2 years back gave an email invoice instead of an attached pdf. How do I go about enabling that ?

**Comment by saurabh261187** [comment] 2016-04-25 12:47
I am now using the latest available version of OSPOS as on today. The PDF attached to the Sales Reciept has some alignment problems. What can be done to rectify this issues ?

![image](https://cloud.githubusercontent.com/assets/15091342/14784170/d43ec168-0b11-11e6-8e50-ceca2b58512d.png)

**Comment by daN4cat** [comment] 2016-04-25 16:34
@saurabh261187 it's better to keep posting in #442 let's not duplicate please.
