### ISSUE TITLE
Possible additions?

### ISSUE THREAD

**Issue by tenkodoy** [jekkos/opensourcepos#996] opened 2016-11-21 11:29 UTC
Could there be expiration dates to products and notifications when they're about to get expired.
Specific sales, purchase reports on specific items or products.
The ability to see the debts the retailer owes it's suppliers?

**Comment by jekkos** [comment] 2016-11-21 12:19
Of course

**Comment by jekkos** [comment] 2016-11-21 12:19
:+1:

**Comment by tenkodoy** [comment] 2016-11-21 12:32
it would be great and complete this powerful project of yours.

**Comment by jekkos** [comment] 2016-11-21 14:40
Sure it will

**Comment by tenkodoy** [comment] 2016-12-05 19:56
I wanted to find out when this possible addition could go in effect. I have shown this to my uncle and he really is interested and wants to use it if only these additions are included. He's opening a pharmacy shop which needs expiration dates especially for the drugs. And he's willing to contribute to the project if only he gets what he needs

**Comment by asakpke** [comment] 2016-12-12 01:00
There's a possibility to add "Custom Field" from 'General' config for expiration date and add expiration date for each item. Then write a item list report on that "Custom Field" in ascending order so that most recent expiring item comes first in the list.

**Comment by jekkos** [comment] 2016-12-12 07:27
Check also #69. Soon there might be some improvements for this functionaliteit. Will let you know once it's ready

**Comment by tenkodoy** [comment] 2016-12-12 07:54
@asakpke that would be nice....but i am an amateur here so if you can give step by step instructions here...twill be great

**Comment by asakpke** [comment] 2016-12-13 13:14
@tenkodoy Please check this attached file, I have done this sometime ago. It's an old version 2.1.3
[POS_2.1.3_03.02.zip](https://github.com/jekkos/opensourcepos/files/648999/POS_2.1.3_03.02.zip)

**Comment by asakpke** [comment] 2016-12-13 13:18
@jekkos I have done this report based on custom1 field in Items table. As this field could be used by different user for different purposes, I have used this as date of expiry. So can you suggest some way to include this report in the main repository?

**Comment by jekkos** [comment] 2016-12-13 13:40
Custom fields will disappear in version 3.1. They will be replaced by a more generic attribute system that allows definition of different data types + config where to show those. A migration script has been made to copy data if it exists.

Currently there are no changes foreseen for reporting but I might consider adding a visibility flag for it.

**Comment by jekkos** [comment] 2016-12-13 13:40
Also see #68

**Comment by jekkos** [comment] 2016-12-28 20:09
Duplicate of #1046

**Closed by jekkos** 2016-12-28 20:09 UTC
Labels: enhancement, needsowner

**Comment by tenkodoy** [comment] 2017-01-08 20:30
I finally got it. and Can now add the expiry date but how do you let it be shown in the view. For example, when you go to columns in Items, you can select columns you want it to be shown but the Expiry date is not part of the custom field
