### ISSUE TITLE
Migrate from old version phppos to ospos

### ISSUE THREAD

**Issue by lutfiajib** [jekkos/opensourcepos#258] opened 2015-12-30 11:02 UTC
I have phppos 11.3 installed
How to migrate to current version?
I dont have any SQL file prior 2.2.1
Anyone can help me?

**Comment by daN4cat** [comment] 2015-12-30 13:25
I assume that with phppos you mean http://phppointofsale.com/.

I don't know which database schema they have, if they have the same tables and so on.
Most likely items, sales, and all basic stuff is the same. But I suspect you would need to do quite some manual work.

I will face something similar soon because I need to migrate a DB from OSPOS 1.1 to the latest 2.3.3.
In my initial tests I exported all the tables content one by one and imported in the new database and table adding the missing columns and renaming what was different.
I'm not sure this is the best way to deal with this, I'm not a big expert of MySQL databases, so my help is probably not the most expert one you might get here.

**Comment by jekkos** [comment] 2016-01-01 15:51
Think this approach is probably the best, export the data and then import it again in the new table structure. You'll need to deal with a couple of issues as well here (add data for new columns eg).

I did something similar some time ago and wrote an sql for this. If you want then I can share it here. It literally copied data from the old database into the new one.

**Comment by jekkos** [comment] 2016-01-01 16:00
I just checked the script and I think it can do more or less what you are looking for, however it requires some modification as it contains a couple of queries for tables that only exist in another branch. It does everything in sql,

So maybe someone can clean it up and the contribute it back so I can add it to the repo?

* query to insert categories has to be adapted
* item_sizes table does not exist in master (remove constraints)

**Comment by jekkos** [comment] 2016-01-01 16:12
I've added the script to the source and did some baisc cleanup. Maybe test a little futher and update where needed. I made it in february 2015 so any changes done to the db layout since then should also be reapplied to this script.

**Comment by jekkos** [comment] 2016-01-02 21:44
Think the create tables can be removed as well. In this case only the inserts copying the actual data are what you need. Just create the schema's from the usual database.sql script.

**Comment by jekkos** [comment] 2016-01-04 16:41
Did an exstra updatre for this script. It's best to create all tables first and add constraints after the data copy is done. MIght be best to split up the initial database.sql script in two parts, one for creating tables and one for adding constraints

* database;sql will then source both script 1 and script 2
* migrate script will source script 1, execute the existing insert/update statements, and then source script 2

**Comment by lutfiajib** [comment] 2016-01-05 00:09
I'm still got difficulties using scripts. But daN4cat is correct. i already done manually:
1 make ospos database
2. remove all constrain from phppos
3. remove all constrain from ospos
4. compare table one by one, and modify phppos table one by one
5. then copy table one by one
especially sales, inventory & receiving tables  have to make sure location_id
people, supplier, employee tables have to copy manually with removing no.1 employee_id
etc.
6. add constrain back to ospos
now our 5 years phppos already move to ospos
live ;-)
thx you all

**Comment by jekkos** [comment] 2016-01-05 06:44
I've updated the script once more, with a little more tweaking all of this can be done in one shot.

**Comment by daN4cat** [comment] 2016-01-05 08:33
I would suggest to disable the constraints not remove, not sure you succeeded in re-adding them without any issue?

I would check the script because it would be handy to have something automatic instead of doing all the manual job.

**Comment by jekkos** [comment] 2016-01-05 10:03
With the new split up the constraints are applied after copying the data. The original init script first inits the tables and then applies the constraints. This changes makes the sql more modular and reusable.

If there's something wrong in the data you will always face errors once you enable or apply the constraints, so  in this case it doesn't matter whether you disable or just add them afterwards

**Comment by daN4cat** [comment] 2016-01-05 10:08
ok

**Comment by jekkos** [comment] 2016-01-07 08:10
There's still a todo in the script, so not sure whether it's completely done in this case. Maybe someone can test on his data and give feedback later.

**Comment by odiea** [comment] 2016-01-07 11:41
I just tried to create a new database from this script and got this error
SQL query: 


-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 08, 2011 at 04:27 PM
-- Server version: 5.1.54
-- PHP Version: 5.3.3

--
-- Database: `pos`
--
SOURCE tables.sql;

MySQL said: Documentation 
 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOURCE tables.sql' at line 14

**Comment by jekkos** [comment] 2016-01-07 11:49
Ok maybe I forgot to say that you need to run this script from the mysql command line, after starting it from the database directory. The web interface won't be able to find the other scripts local to the one being executed.

**Comment by odiea** [comment] 2016-01-07 12:12
So I ran each source separately and it created a database ok. I did not run the phppos migrate.

**Comment by daN4cat** [comment] 2016-01-07 13:42
I would need to give a try since I have an old database I could use.
But not sure the old schema is the same, but maybe the logic is what matters here.

**Comment by jekkos** [comment] 2016-01-22 10:00
Ok some more improvements for this issue in commit 2b70762b7a58c8f9254d18dc577f736ead6d74d6. Would be nice if someone has the chance to test the migrate script.

**Comment by odiea** [comment] 2016-01-22 13:26
When I remove the following lines the database is created with no errors.
-->> This file is autogenerated from tables.sql and constraints.sql. Do not modify directly <<--
--
-- Table structure for table `ospos_app_config`
-- otherwise I receive errors about improper syntax.

**Comment by jekkos** [comment] 2016-01-22 13:41
OK this is a default header that i added to the file, I suppose I'll need to leave a space after the initial comment sequence.

**Comment by odiea** [comment] 2016-01-22 14:01
I do not have a phppos database to migrate this to. I was just testing installation of database.

**Comment by odiea** [comment] 2016-01-22 14:16
@daN4cat is the phppos under your repository a valid installation to check this migrate script with.

**Comment by daN4cat** [comment] 2016-01-22 14:34
I'll check over the week-end, if I manage to find the time.

**Comment by daN4cat** [comment] 2016-01-23 10:46
2 things here:

- the database I have comes from a 1.1 version with tables that I modified. So I will need to adjust the script to make space for my extra fields (or drop them)
- which script am I supposed to run `migrate_phppos_dist.sql` or `phppos_migrate.sql` or both?

**Comment by jekkos** [comment] 2016-01-23 18:17
In this case it's the _dist script which is the one concatenated from tables and constraints. So just running that one should be fine.

**Comment by daN4cat** [comment] 2016-01-24 10:13
OK, I'll see if I can find the time to check this today.

**Comment by daN4cat** [comment] 2016-01-24 23:10
Sorry, I got busy with other stuff I had in mind and therefore had no time to work on the database script.

**Comment by daN4cat** [comment] 2016-01-25 08:17
database.sql error should be fixed by latest jekkos submission

**Comment by daN4cat** [comment] 2016-01-31 16:56
I run `migrate_phppos_dist.sql` against the database I have.

However I get an error as follow:

> Error
> SQL query: Documentation
> 
> --
> -- Dumping data for table `ospos_suppliers`
> --
> --
> -- This migration script should be run after creating tables with the regular database script and before applying the constraints.
> --
> --
> -- Dumping data for table `ospos_customers`
> --
> INSERT INTO  `ospos_customers` (  `person_id` ,  `account_number` ,  `taxable` ,  `deleted` ) 
> SELECT  `person_id` ,  `account_number` ,  `taxable` ,  `deleted` 
> FROM  `phppos`.phppos_customers;
> 
> 
> MySQL said: Documentation
> 
> #1142 - SELECT command denied to user '<removed>'@'localhost' for table 'phppos_customers' 

The problem I see is that there is an assumption on the database name to phppos.

I'll try again renaming my database to be phppos.

**Comment by daN4cat** [comment] 2016-01-31 17:10
Outside a clash with the admin account which I sorted renaming the old admin to php_admin, I've got a new issue

> Error
> SQL query: Documentation
> 
> --
> -- Dumping data for table `ospos_sales`
> --
> INSERT INTO  `ospos_sales` (  `sale_time` ,  `customer_id` ,  `employee_id` ,  `comment` ,  `sale_id` ,  `invoice_number` ) 
> SELECT  `sale_time` ,  `customer_id` ,  `employee_id` ,  `comment` ,  `sale_id` ,  `invoice_number` 
> FROM phppos_sales;
> 
> 
> MySQL said: Documentation
> 
> #1054 - Unknown column 'invoice_number' in 'field list' 

It looks like the invoice_number is expected, but that wasn't part of phppos as far as I remember.
I'll try and fix it and give a new run

**Comment by daN4cat** [comment] 2016-01-31 17:23
invoice_number sorted and fixed in the script.

**Comment by daN4cat** [comment] 2016-01-31 17:25
I got a new error:

> Error
> SQL query:
> 
> --
> -- Constraints for table `ospos_inventory`
> --
> ALTER TABLE  `ospos_inventory` ADD CONSTRAINT  `ospos_inventory_ibfk_1` FOREIGN KEY (  `trans_items` ) REFERENCES  `ospos_items` (  `item_id` ) ,
> ADD CONSTRAINT  `ospos_inventory_ibfk_2` FOREIGN KEY (  `trans_user` ) REFERENCES  `ospos_employees` (  `person_id` ) ,
> ADD CONSTRAINT  `ospos_inventory_ibfk_3` FOREIGN KEY (  `trans_location` ) REFERENCES  `ospos_stock_locations` ( `location_id` ) ;
> 
> 
> MySQL said: Documentation
> 
> #1452 - Cannot add or update a child row: a foreign key constraint fails (`<my database>`.`#sql-7a7_e4b8`, CONSTRAINT `ospos_inventory_ibfk_1` FOREIGN KEY (`trans_items`) REFERENCES `ospos_items` (`item_id`)) 

And this is a nastier issue.... to get where the issue is with this constraint failure

**Comment by daN4cat** [comment] 2016-01-31 22:59
I played around and I've just an issue with the above set of constraints.

**Comment by daN4cat** [comment] 2016-02-01 13:42
I checked vs 2.1.2, the oldest I can find in SourceForge for the OSPOS and I cannot see any invoice in the database.sql.
Therefore I conclude that the fix I made is correct as there was no invoice concept in phppos either.

I still had no time to look into the constraint failure root cause.

**Comment by jekkos** [comment] 2016-02-02 16:46
Yes think you'll need to omit the invoice_number. Regarding the failing constraint, could you check which transaction lines have no entries in the items table?

    select * from ospos_inventory where trans_items not in (select item_id from ospos_items)

**Comment by daN4cat** [comment] 2016-02-02 16:55
I removed the comments because those are specific to my database. Somehow some items entries were deleted in the past and probably due to wrong cvs bulk imports.

I ran a query yesterday evening to spot which ones and I'll use yours but I need to clean the inventory.

I had another constraint issue with a test employee that was manually removed probably 5 years ago and caused another similar issue, that's fixed.

Besides that constraint issue and invocie story the rest was ok from a script point of view. Of course I need to run the database for a test but I wanted first to fix the issues on my database as I'm testing this.

**Comment by daN4cat** [comment] 2016-02-02 16:57
BTW, the script probably needs to remove the admin employee from the newly created ospos to avoid clashes. That's another things I need to fix.

**Comment by jekkos** [comment] 2016-02-02 20:48
Great, at first sight I didn't see another option except for hardcording at least one of the database names. This because you can only reference just one as the current active db.

Didn't see that problem with the admin user but sounds ok to remove it.

**Comment by daN4cat** [comment] 2016-02-04 20:10
I managed to get to an end and do the migration but when I log in with admin I get a message of no permission and etc,

I guess I need now to dig in, but was that script supposed to migrate to 2.3.3/4 or some earlier version?

**Comment by daN4cat** [comment] 2016-02-04 21:34
I also can see that ospos_item_kits has a TODO in the script

**Comment by daN4cat** [comment] 2016-02-04 22:36
TODO sorted and added other parts that were missing like giftcard.
I also removed entries from app_config to allow the copying of preexisting config keys to happen.

It now seems fine and I submit the changes and close this.

**Comment by daN4cat** [comment] 2016-02-04 22:38
there was also a double `INSERT INTO `ospos_stock_locations` ( `deleted`, `location_name` ) VALUES (0, 'stock');` which I removed

**Comment by daN4cat** [comment] 2016-02-04 23:08
Submitted a PR with the fixes for a merge to master.

Once that's done we can close this as I tested as much as I could in terms of script functionality and data migration. Not sure anybody else can test or wants to do it, but we can close.

**Comment by daN4cat** [comment] 2016-02-05 09:09
Updated PR with complete script fixing.

**Comment by daN4cat** [comment] 2016-02-05 17:05
In master

**Closed** 2016-02-05 17:05 UTC
Labels: enhancement
