### ISSUE TITLE
Incorrect subtotal and tax in reports

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#976] opened 2016-11-16 00:13 UTC
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
From latest pull

### Expected behaviour
Values for subtotal and tax may be incorrect.
![2016-11-15 17_09_55-](https://cloud.githubusercontent.com/assets/10962177/20329645/c2cdb156-ab56-11e6-8c36-4f91fc3f9801.png)

### Steps to reproduce the issue

**Comment by odiea** [comment] 2016-11-16 00:21
Here are the totals for Detailed Sales report for the same period of time.
![2016-11-15 17_20_00-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20329837/da389dd2-ab57-11e6-9bf2-6b77d4d69c24.png)

**Comment by daN4cat** [comment] 2016-11-16 09:20
It might be related to the database optimisation work. Need to check and fix.

**Comment by jekkos** [comment] 2016-11-17 09:37
Would be nice to have some testcases for these kind of things in the future..

**Comment by daN4cat** [comment] 2016-11-17 09:51
Yes, but the problem is that there are mistakes in the way things are calculated with the rounding.

I believe I need to write down some examples, use a spreadsheet and compare as I fixed but sums are not matching due to rounding or some other issue that I don't know yet.

**Comment by jekkos** [comment] 2016-11-17 10:52
I've solved some issues with incorrect calculations in those queries in the past. I think at that time it took me quite a bit of time to get it right (there might still be an issue about it here somewhere). Main problem was indeed the rounding strategy and used datatypes in the query, if I remember well

**Comment by jekkos** [comment] 2016-11-17 10:54
Maybe a phpunit test would be good to check whether things work correctly? Don't know if you feel up to that.. Adding support can be done through the install script in bin folder. It should automatically generate a couple of example unit tests that show how to build up such a testcase

**Comment by daN4cat** [comment] 2016-11-17 11:18
You mean using phpunit?
It will probably make sense to have some test suite against the models at least.
Let me see if it's not that much work...

**Comment by jekkos** [comment] 2016-11-17 11:40
Yes indeed.

**Comment by jekkos** [comment] 2016-11-17 13:38
I once installed the depedency through the CI script but didn't commit it.. I'll look into the CI setup if needed. Think this kind of effort will certainly save time in the future (we might be able to spot regressions more quickly!)

**Comment by daN4cat** [comment] 2016-11-17 18:51
This story with taxes is a can of worms....

**Comment by jekkos** [comment] 2016-11-17 20:05
You mean the tax included / excluded thing?It's not that obvious indeed, I remember spending a lot of time on it in the past. I had some complaints from our accountant that calculations weren't precise at some points. Some rounding errors happened at a certain point in this calculation and I had to track it down  by double checking it step by step. Main problem is that mysql is doing the maths here..

**Comment by daN4cat** [comment] 2016-11-17 21:30
It's all fixed, and the issue is with the US double taxation. Not sure how it used to be right before, but I believe it's all fine now.
I need to fix the taxes summary as that is not correct in the table. That was never right even earlier.

The problem with working with this story is that one sale can have multiple items that can have multiple taxes. That was what the temp table was solving and in moving out of that I forgot the complex aggregation.

Last but not least, now the profit is net profit and not gross profit, in the sense that it's total - taxes - cost.

**Comment by jekkos** [comment] 2016-11-17 21:43
Ok I'm merging the datetime filter thing as we speak now. Could this be an issue for the fix you did? It seems there were quite some changes since the PR for this change was  submitted

**Comment by jekkos** [comment] 2016-11-17 21:44
Ok this double tax story isn't one that's used this often. I know there were other long standing bugs in that part even in the sales module not that long ago. So I'm not surprised that maybe it didn't work as expected.

I think that figure for profit  makes more sense indeed. We should take taxes into account.

**Comment by daN4cat** [comment] 2016-11-17 22:03
Yes, if you merge that you'll break what I changed. Please wait...

**Comment by jekkos** [comment] 2016-11-17 22:06
Ok I'll leave that for now, it's not working anyway. Commit first and I'll look afterwards. 
Actually I was working on categories but just got til the point of adding/removing them. I haven't started the implementation in item forms yet. Need to think about some UI shizzle there first.

**Comment by daN4cat** [comment] 2016-11-17 23:15
@odiea something to test. Hopefully I fixed in the correct way.

Sorry non phpunit test yet.

**Comment by daN4cat** [comment] 2016-11-17 23:34
@odiea I need you to test because the US version implies different way of setting prices and taxes so that's something I couldn't test properly.

**Comment by odiea** [comment] 2016-11-18 01:23
Works great. Another fine job. As far as I am concerned the single tax is ok. we usually have to split between state and local.

**Comment by odiea** [comment] 2016-11-18 03:20
In the US at least in Colorado we charge tax on items but not Labor. We do have tax exempt people.

**Comment by daN4cat** [comment] 2016-11-18 09:33
So this is fixed.

I give a bit of more time and if no issue on Sunday I release 3.0.1.

**Comment by daN4cat** [comment] 2016-11-18 09:46
@jekkos I may make the Reports more object oriented as I implemented something to make common parts as first refactoring pass but actually the design is not what I would normally do and like.
It's better to have a base class function getData calling the Select, From, Where, Group protected functions and let the derived classes specialise the functions if needed.
I think I will do that to have a neat and clean design.... that will even implement the Open Close Principle which is a better way to control the change of interface.
I know this is really OO talking...

With regards to OO design, something that I don't really like in OSPOS is the way data extracted from DB is treated.
Instead of generic arrays and function scattered across the layers to extract or manipulate the data fields it would be better to encapsulate the data in an object having the manipulation functions as part of the object.
But that will probably imply quite some work.... thoughts?

**Comment by jekkos** [comment] 2016-11-18 16:01
Yes I agree regarding some parts that design is more procedural and only tied to the imposed MVC structure that CI uses. However some logic could be greatly simplified by using objects which I agree on.

Regarding the ORM part, I'm not completely certain. I have worked a lot with hibernate and found that it is overly complex and costly all due to the fact that the relational and object oriented world don't always easily get along. One can easily map out a result set using object rows and I think that in most cases this lightweight solution is still rather fast and memory efficient

**Comment by jekkos** [comment] 2016-11-18 16:08
What you propose is more a domain driven design approach I think

**Comment by jekkos** [comment] 2016-11-18 16:10
Actually I think that CI wasn't really made with this purpose in mind. If we'd like to pursue this style of programming I think we should consider other frameworks like laravel or symfony2

**Comment by daN4cat** [comment] 2016-11-18 16:37
OOD refactoring done.

I close this.

**Comment by daN4cat** [comment] 2016-11-18 16:55
With regards to other frameworks, well I would probably prefer to implement OSPOS in Java rather than PHP.

**Comment by odiea** [comment] 2016-11-18 22:56
Per your request I enables another tax for Report testing. Here is the receipt.
![2016-11-18 15_27_35-action center](https://cloud.githubusercontent.com/assets/10962177/20449520/1a640bc0-ada7-11e6-9074-9d6f8ecaaa48.png)
Here is what Detailed Sales Report shows.
![2016-11-18 15_51_14-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20449533/36c337dc-ada7-11e6-8cf4-1a8246fb68c6.png)
It appears that Takings is a bit confused. The Amount due is off when a second tax is enabled.
![2016-11-18 15_28_10-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20449545/4f057ad0-ada7-11e6-9105-b8f9bce143f1.png)

**Comment by odiea** [comment] 2016-11-18 23:04
BTW what report does takings use? For me it would be more logical to have Amount Due before Amount Tendered.

**Comment by daN4cat** [comment] 2016-11-19 10:49
OK, more to check....

**Comment by jekkos** [comment] 2016-11-19 12:18
@daN4cat You're right, Java might be best for DDD after all. However the cost to deploy is usually higher. In that case it would need to run on Java container infrastructure which is possible on platforms like AWS or the like. In other cases a VPS will be needed.

In that case I would prefer to use spring data REST and react + reflux as frontend.

**Comment by daN4cat** [comment] 2016-11-19 15:17
@odiea please check the latest code from master, I believe I fixed the wrong Amount Due with multiple taxes and I also swapped Amount Due with Amount Tendered columns (I agree it didn't make sense before.

By the way, Sales taking was probably never right with multiple taxes.

**Comment by daN4cat** [comment] 2016-11-19 15:18
I tested and compared with Sales Details but I prefer more testing.

**Comment by odiea** [comment] 2016-11-19 15:59
Here is Takings.
![2016-11-19 08_48_38-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20456559/2410ac66-ae36-11e6-9cfa-23f6df6ffda5.png)
Here is Detailed Reports. It appears Detailed reports is missing a penny. Other then the penny it is working great.
![2016-11-19 08_55_36-wedidit _ powered by ospos 3 0 1](https://cloud.githubusercontent.com/assets/10962177/20456567/484e55ec-ae36-11e6-9fd6-1526d088960a.png)

**Comment by daN4cat** [comment] 2016-11-19 16:29
@odiea try the latest change in master and see if the rounding issue is solved.

**Comment by daN4cat** [comment] 2016-11-19 17:01
BTW, @odiea , for the summary part is the sequence correct?
Or should it be Total, Subtotal, Tax, Cost and Profit? Or something else?

**Comment by odiea** [comment] 2016-11-19 22:49
For some reason the tax when added in the column is off .01 throwing the total off. I would prefer like on the receipt.
Subtotal
Tax
Total
Cost
Profit
![2016-11-19 15_44_05-new notification](https://cloud.githubusercontent.com/assets/10962177/20458943/8a3924d0-ae6f-11e6-92b6-0d8d18d946d6.png)

**Comment by daN4cat** [comment] 2016-11-19 23:07
Mhhhh I probably need to remove the decimal approximation by line and leave the full value and approximate to the decimal the sum. It's tricky story to get right.

**Comment by odiea** [comment] 2016-11-19 23:10
The other solution would be to drop the second tax completely. I don't think it is really a required tax just a
solution to be able to split the different taxes we have. Does any other US user really need this?

**Comment by daN4cat** [comment] 2016-11-19 23:11
@odiea you could try another thing, but I don't have time now to commit the change, so it's just one line change.
In models/Sale.php line 735 change from:

`$decimals = totals_decimals() + 1;`

to

`$decimals = totals_decimals();`

and give an extra try. If it doesn't work I need to change differently.

**Comment by daN4cat** [comment] 2016-11-19 23:14
Let me know. And tomorrow I'll change the order in the summary. It never looked right to me in that way.

**Comment by odiea** [comment] 2016-11-19 23:17
That was the fix. Now both total and tax amount are showing correctly in Detailed Sales Report. Please go get some rest now. Thanks for all the help.

**Comment by daN4cat** [comment] 2016-11-19 23:21
Ok. I'll fix all tomorrow and we can hopefully close this release.

**Comment by daN4cat** [comment] 2016-11-20 12:21
With latest commit I fixed the tax total rounding issue and I set the order to be subtotal, tax, total, cost and (net) profit across all the reports.

**Comment by daN4cat** [comment] 2016-11-20 12:22
I believe this is now closed. I leave a bit of time for cross testing.

**Closed** 2016-11-21 08:16 UTC
Labels: bug
