### ISSUE TITLE
error in barcode generate

### ISSUE THREAD

**Issue by arkgnan** [jekkos/opensourcepos#485] opened 2016-04-18 08:37 UTC
hi, i got error in barcode generate in items menu. not sure why, been a long time since I last check this feature... barcode still generate in receipt. this is the error after i click generate button in items menu
`A PHP Error was encountered

Severity: Warning

Message: Division by zero

Filename: views/barcode_sheet.php

Line Number: 25

Backtrace:

File: D:\xampp\htdocs\pos9\application\views\barcode_sheet.php
Line: 25
Function: _error_handler

File: D:\xampp\htdocs\pos9\application\core\MY_Loader.php
Line: 22
Function: _ci_load

File: D:\xampp\htdocs\pos9\application\controllers\Items.php
Line: 364
Function: view

File: D:\xampp\htdocs\pos9\index.php
Line: 292
Function: require_once`

**Comment by daN4cat** [comment] 2016-04-18 08:51
I don't see this problem in the latest master (3.0), at least I cannot reproduce with my setup

Please describe the test case specifying:

- web server host OS name and version
- name and version of web server
- PHP version
- language selected and any configuration of OSPOS
- Exact steps to reproduce the issue

If no answer within a week I will close this issue.

**Comment by arkgnan** [comment] 2016-04-18 08:58
of course this is my fault, I forget what I changed in the script, i'll check it up your suggestion

**Comment by arteiro** [comment] 2016-04-18 22:08
Good evening,

What would be the right field for issuing the barcode?
item_code or item_number.

Thank you

**Comment by arkgnan** [comment] 2016-04-19 01:34
ah i know the reason of this issue, as i said before, this is my fault, i
change database structure, especially in field of app_config table

On Tue, Apr 19, 2016 at 5:08 AM, arteiro <notifications@github.com> wrote:

> Good evening,
>
> What would be the right field for issuing the barcode?
> item_code or item_number.
>
> Thank you
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/485#issuecomment-211601063>
>



-- 
Best Regards

Dedi Ananto

**Closed** 2016-04-19 04:44 UTC
Labels: pending
