### ISSUE TITLE
docker windows 10 issue

### ISSUE THREAD

**Issue by sivajik34** [jekkos/opensourcepos#883] opened 2016-09-28 11:42 UTC
### Issue

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:
- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] PHP version is at least 5.5 and not 7.x
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.
### Installation information

Installed docker in windows 10
### Expected behaviour

Application should display in browser.
### Actual behaviour

The 192.168.99.100 page isn’t working
192.168.99.100 is currently unable to handle this request.
HTTP ERROR 500
### Steps to reproduce the issue

docker-compose build 
docker-compose up

**Comment by jekkos** [comment] 2016-09-28 14:42
Are you using master branch? I haven't tested on windows. Normally you should be able to surf to http://localhost and see everything working.

I use these containers all the time so not sure what might be wrong here. Could you post the compose logs here so I can see whether init goes fine.

**Comment by sivajik34** [comment] 2016-09-29 05:35
I'm using Master branch. I think for windows it will assign separate ip address.for example In my system:192.168.99.100


docker ps -l
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                NAMES
efd5afc9136b        opensourcepos_php   "apache2-foreground"   9 minutes ago       Up 2 minutes        0.0.0.0:80->80/tcp   opensourcepos_php_1

Admin@DESKTOP-O87GU72 MINGW64 ~/opensourcepos (master)
$ docker logs efd5afc9136b
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
[Thu Sep 29 05:31:27.648682 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/5.6.26 configured -- resuming normal operations
[Thu Sep 29 05:31:27.648861 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

**Comment by jekkos** [comment] 2016-09-29 06:38
Can you check if the mysql was started properly? Try a `docker ps` withouth the -l to see whether it's running. I suppose that you don't have a mysql installed on your windows itself? It might fail to start if the port is already taken.

**Comment by sivajik34** [comment] 2016-09-29 10:02
docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                    NAMES
55648000209b        opensourcepos_php         "apache2-foreground"     8 minutes ago       Up About a minute   0.0.0.0:80->80/tcp       opensourcepos_php_1
558dd2d43eb9        mariadb:10.0.26           "docker-entrypoint.sh"   8 minutes ago       Up About a minute   0.0.0.0:3306->3306/tcp   opensourcepos_mysql_1
d715d711e1e9        indiehosters/git:latest   "sh"                     10 minutes ago      Up 3 minutes                                 git

**Comment by jekkos** [comment] 2016-10-01 16:33
I will need to take the time to install docker on windows 10, have it in dual boot and see whether I can reproduce

**Comment by daN4cat** [comment] 2016-10-01 16:57
Can we get 3.0.0 last bits fixed before starting this?

**Comment by daN4cat** [comment] 2016-11-06 18:40
What do we want to do with this?

**Comment by jekkos** [comment] 2016-11-06 19:46
I was planning to test and verify on my dual boot machine, but haven't found the time to do that.

**Comment by daN4cat** [comment] 2016-11-08 21:09
Do you want to include this in 3.0.1?

**Comment by jekkos** [comment] 2016-11-08 22:12
@sivajik34  Which docker version are you using on windows? Is it native windows pro 64 bit or the docker toolbox version?

**Comment by jekkos** [comment] 2016-11-08 23:07
I found that the compose starts up without any problem, however there seems to be some network issue with default docker toolbox which does not allow me to reach the login page. However everything in the container seems to be running (as I can use curl to fetch the front page from inside)

**Comment by jekkos** [comment] 2016-11-09 16:31
Not sure whether we need to wait for this. Just go ahead with the release.

**Comment by daN4cat** [comment] 2016-11-09 18:25
@sivajik34 if no replies by end of the week we close this.

**Closed** 2016-11-13 11:43 UTC
Labels: pending
