### ISSUE TITLE
I just got this error after the latest pull.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#271] opened 2016-01-04 21:24 UTC
Parse error: syntax error, unexpected 'if' (T_IF) in C:\xampp\htdocs\tabbed\application\controllers\sales.php on line 21

**Comment by daN4cat** [comment] 2016-01-04 21:57
I can see, there is typo: 		$person_id = $this->session->userdata('person_id');git 

see the git at the end?

**Comment by daN4cat** [comment] 2016-01-04 21:57
try to remove it, I'm testing and then commit a fix.

**Comment by odiea** [comment] 2016-01-04 22:01
I did see that and it eliminated that error but now look at my Register screen.
![2016-01-04 14_59_47-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12101810/fa2014fc-b2f3-11e5-975e-4c5611638f48.png)

**Comment by daN4cat** [comment] 2016-01-04 22:04
I guess that if you grant access to Takings it's sorted, right?

**Comment by daN4cat** [comment] 2016-01-04 22:06
I don't get that problem: 

![image](https://cloud.githubusercontent.com/assets/636048/12101918/6730a008-b32f-11e5-94de-d2ac83349d19.png)

**Comment by odiea** [comment] 2016-01-04 22:08
I do not see any new permissions for takings.

**Comment by daN4cat** [comment] 2016-01-04 22:08
It's the same as reports/sales

**Comment by odiea** [comment] 2016-01-04 22:10
Yes I already have those permissions. I will revert back and see if the problem is still there.

**Comment by daN4cat** [comment] 2016-01-04 22:10
ok, but the spurious git was the root cause of the initial bug you had

**Comment by odiea** [comment] 2016-01-04 22:13
I reverted back to my original and this is how it should look.
![2016-01-04 15_12_13-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/12102077/b4cdf944-b2f5-11e5-8ba1-cde1c8cf0584.png)

**Comment by daN4cat** [comment] 2016-01-04 22:14
OK, I pushed the fix with PR #272 and it's now in jekkos/master.
I'm sure @jekkos doesn't mind this quick one as it's a typo from one of his changes and removes a break with xampp from master.

**Closed** 2016-01-04 22:15 UTC
Labels: bug

**Comment by daN4cat** [comment] 2016-01-04 22:17
For the UI issue, check the changes in application/views/sales/register.php

**Comment by odiea** [comment] 2016-01-04 22:41
The only thing I can figure is it was a bad pull. I downloaded the latest zip and got the pages from there and its all ok now.
