### ISSUE TITLE
Summary Reports Payments

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1045] opened 2016-12-23 02:02 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
Xampp not php 7 or mysql 5.7

### Expected behaviour
Select All. The report shows the correct info.
Select either Sales or Return and nothing shows.

### Actual behaviour
Something should show.

### Steps to reproduce the issue

**Comment by SteveIreland** [comment] 2016-12-23 14:13
I'm a bit paranoid.  Hopefully my changes for MySQL 5.7 didn't accidentally find their way into this installation.  I've had similar experiences in my testing but I've always assumed it was a bug in my changes ... so far I've been proved correct on all accounts.

**Comment by odiea** [comment] 2016-12-23 14:23
No it appears this has possibly been an ongoing issue.

**Comment by SteveIreland** [comment] 2016-12-24 04:11
I took a quick look at this and found that when I changed the `\application\controllers\Reports.php` replacing the first line in function `summary_payments` with the following then the report seemed to be working again.  Before it displayed nothing and after I made the change it started working.  the `sale_type` field needs to be qualified with `sales`

`$inputs = array('start_date' => $start_date, 'end_date' => $end_date, 'sales.sale_type' => $sale_type, 'location_id' => $location_id);`

I hope this is helpful.

**Comment by odiea** [comment] 2016-12-24 11:34
Now if you can find  why changing stock locations does not work it would be fixed..

**Comment by SteveIreland** [comment] 2016-12-24 15:00
@odiea , I'm glad you asked me about the location.  It forced me to take a closer look at the code  and I've concluded that even though my earlier solution for Sales Type seems to work for me (because amazingly it doesn't crash - I'm not sure why not), I don't think that it will result in the correct result in all configurations.

I'm gong to work on a better solution.

Because I'm a newbie I assumed that the sale_type was an attribute of the sales table - not so.  To determine that I will need to modify the SQL statement for payments to look at the sales_items which it currently doesn't do.

Regarding the location question, the way the database is modeled a sale can be for items from multiple stock locations, but payments aren't made for a sale in a specific location ... only for the sale.   So my "solution" would be to remove the location filter for summary payments since from a database perspective payments cannot be filtered by location.

HOWEVER, if the design intent is to filter on orders that include payments for sales where the sale has at least one item from that location (even though the majority of the items could have been pulled from a different location) then the correction is be a bit more complex.

Newbie question:  Is my assumption that a "stock location" can either represent a different store or a different stocking location for a single store correct?

Since I need to look at the sales_items for the sale_type then just for the "internals learning experience" I'll go ahead a propose a solution for both that is a bit more "rock solid".

**Comment by odiea** [comment] 2016-12-24 15:03
Merry Christmas Steve.  Yes = Is my assumption that a "stock location" can either represent a different store or a different stocking location for a single store correct? And thanks for volunteering for this stuff.

**Comment by SteveIreland** [comment] 2016-12-25 02:07
I have a fix for this, but it's not a one liner replacement.  It' a refactor of the getData() function in Summary_payments.php.  Since the Masters of OSPOS are enjoying a well deserved vacation I'll wait until they return to find out if they need me to contribute it via a pull request, but the entire code change is shown below.  So even thought it is a significant rewrite it is isolated to a single function.

It's a change to `...\application\models\reports\Summary_payments.php` and if someone wants to give it a try simply replace the getData function with the following.

```php

    public function getData(array $inputs)
    {

        $w = 'WHERE DATE(salesx.sale_time) BETWEEN ' . $this->db->escape($inputs['start_date']) . ' AND ' . $this->db->escape($inputs['end_date']) . ' ';

        if (!empty($inputs['sale_type']) && $inputs['sale_type'] != 'all')
        {
            error_log('sale_type <> all');
            $w = $w .= ' and salesx.sales_type = ' . $this->db->escape($inputs['sale_type']) . ' ';
        }

        if (!empty($inputs['location']) && $inputs['location'] != 'all')
        {
            error_log('location <> all');
            $w = $w .= ' and salesx.location = ' . $this->db->escape($inputs['location']) . ' ';
        }

            $sql = 'select sales_payments.payment_type, count(*) AS count, SUM(sales_payments.payment_amount) AS payment_amount 
    from ' . $this->db->dbprefix('sales_payments') . ' as sales_payments
    join (select sales_items.sale_id, case when sum(sales_items.quantity_purchased) < 0 then \'returns\' else \'sales\' end as sales_type, sales_items.item_location as location, max(sales.sale_time) as sale_time 
    from ' . $this->db->dbprefix('sales_items') . ' as sales_items 
    join ' . $this->db->dbprefix('sales') . ' as sales 
    group by sales_items.sale_id, sales_items.item_location) as salesx on sales_payments.sale_id = salesx.sale_id '
    . $w
    . ' group by payment_type';

        error_log($sql);

        $payments = $this->db->query($sql)->result_array();

        // consider Gift Card as only one type of payment and do not show "Gift Card: 1, Gift Card: 2, etc." in the total
        $gift_card_count = 0;
        $gift_card_amount = 0;
        foreach($payments as $key=>$payment)
        {		
            if( strstr($payment['payment_type'], $this->lang->line('sales_giftcard')) != FALSE )
            {
                $gift_card_count  += $payment['count'];
                $gift_card_amount += $payment['payment_amount'];

                // remove the "Gift Card: 1", "Gift Card: 2", etc. payment string
                unset($payments[$key]);
            }
        }

        if($gift_card_count > 0)
        {
            $payments[] = array('payment_type' => $this->lang->line('sales_giftcard'), 'count' => $gift_card_count, 'payment_amount' => $gift_card_amount);
        }
        
        return $payments;
    }

```
Enjoy.  And if anyone has any problems with it please let me know.

**Comment by SteveIreland** [comment] 2016-12-25 02:46
I just reviewed the pull requests and noticed that pull/1023 has a change to this same program, so if anyone has that installed then there is a code merge that needs to be carefully done.

**Comment by odiea** [comment] 2016-12-25 11:55
I tried it and the date filter does not appear to be working.
Here is Sales for last 7 days.
![2016-12-25 04_51_11-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21471006/363e4cf6-ca5e-11e6-9577-9519ac72181c.png)
Here is payments for the last 7 days.
![2016-12-25 04_52_47-](https://cloud.githubusercontent.com/assets/10962177/21471012/51557dd4-ca5e-11e6-8e4e-fd9892d54fe8.png)

**Comment by SteveIreland** [comment] 2016-12-25 17:00
@odiea  Okay, thanks for the feedback.  

You know, the request stated that the expected behavior was that "something should show".  I really thought I was done.  :wink  

Seriously though, I was getting some filtering with my limited set of test data and I stole the date filter code from another program I'm pretty sure was working, so assuming it is correct then maybe I have it in the wrong spot.  I'll take a look at that as soon as I have a window of opportunity.

Is the "Count" column supposed to be the count of the number of payments of that payment type or a count of the number of orders paid using that payment type?

**Comment by odiea** [comment] 2016-12-25 17:44
I think part of the issue is it appears it works strictly from the sales_payments table. I would say its a count of sales payments for that period of time. It looks like some joins need to be made to get the location_id to work properly or just eliminate the location_id from the dropdown and keep it set to all. I am no programmer.

**Comment by jekkos** [comment] 2016-12-26 13:05
@SteveIreland Pull request is handy so we can see directly what was changed.. It might be the fact that sale payments are now in their own temporary table, but I need to take a further look before I make any final conclusions.

**Comment by SteveIreland** [comment] 2016-12-27 17:20
I think I'd like to wait on your analysis because I totally missed something if it's pulling data from the temporary table.  I saw the temporary table but I did NOT see where the the sales summary was using it - so if it is then my fix is not the correct solution.

**Comment by jekkos** [comment] 2016-12-27 23:42
I have just tested this code and date filter seems to work at first sight..

**Comment by jekkos** [comment] 2016-12-27 23:44
Only totals don't seem to be correct

**Comment by odiea** [comment] 2016-12-27 23:46
The previous issue was when you change locations or change to sales or returns in the original code.

**Comment by jekkos** [comment] 2016-12-27 23:48
This part seems to work as well now, after applying the proposed patch here..

**Comment by odiea** [comment] 2016-12-27 23:53
I get a table full of all the payments from the beginning of time not the payments for the date period I selected.

**Comment by jekkos** [comment] 2016-12-28 00:17
Hmm might be better if @daN4cat can take a look at this one.. I've quickly looked at the latest code here but not sure why the totals in summary_payments don't correspond to what is shown per payment type.

**Comment by jekkos** [comment] 2016-12-28 00:19
I think that in this case another group by in the common part might be needed as the totals are summed up per payment type in the report itself..

**Comment by jekkos** [comment] 2016-12-28 00:31
Ok I've modified the fix a little bit can you see if that helps? Totals are not yet correct tho.

**Comment by jekkos** [comment] 2016-12-28 00:31
Also for some reason travis-ci keeps failing.

**Comment by SteveIreland** [comment] 2016-12-28 01:19
I noticed that it failed on the mysql5.7 pull request.  So if that is involved then can you detach it?

**Comment by odiea** [comment] 2016-12-28 02:54
Here is detailed sales.
![2016-12-27 19_51_17-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/21512779/0d1d2ba0-cc6e-11e6-83ec-2c78c197cdba.png)
Here is summary payments.
![2016-12-27 19_51_47-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/21512788/1c9cbdca-cc6e-11e6-847a-a51c21199b97.png)
The totals are correct but still shows a life time of tables.

**Comment by daN4cat** [comment] 2016-12-30 14:23
No the fix doesn't work, it's also timing out for me (PHP timeout).

I need to look into this, and most likely create a temp table to filter sale / return and location first. Payment as second step.

**Comment by daN4cat** [comment] 2016-12-30 14:24
Having said that, do we really need this filtering? I mean payment by location? Is that a real use case?

**Comment by odiea** [comment] 2016-12-30 14:29
No we do not .

**Comment by jekkos** [comment] 2016-12-30 14:37
It does not make sense indeed.

**Comment by jekkos** [comment] 2016-12-30 14:38
Payments are done on a complete sale which can contain items from different locations.. surely in this scenario it doesn't make a lot of sense. Or maybe if there's a usecase in which some employees are only allowed to sell from a specific location..

**Comment by daN4cat** [comment] 2016-12-30 16:01
Mhhh there is a bit of a general issue with what is a Sale and what is a Return because based on purchased quantity.
The sum of the purchased quantity per sale should say one or the other, so the filtering is not consistent as it is at the moment.

**Comment by daN4cat** [comment] 2016-12-30 17:33
OK, I will ignore the location filter as that's not applicable here.
The form stays the same just the filter will have no effect and I remove the error.

**Comment by daN4cat** [comment] 2016-12-30 17:55
With regards to Sale & Return that needs to go by line not sum of quantity. I said something not correct earlier. So that needs to be fixed to be consistent across the summary reports.

**Comment by daN4cat** [comment] 2016-12-30 17:58
And here I have a problem again, because payments are per sale not item so what is what?

I feel like I should simply remove from payments this filter story and full stop.

**Comment by daN4cat** [comment] 2016-12-30 18:28
Could you please check my latest commit and see if it's working fine across all the Summary report?

I also removed the location and sale/return from taxes as it's the same as for payments, it does not make sense.

**Comment by odiea** [comment] 2016-12-30 22:24
Other ten a bad pull it looks good.

**Comment by SteveIreland** [comment] 2016-12-30 22:49
I'm happy about the final resolution.  As I mentioned earlier I thought the filter on location seemed to be something that would not likely be used  - especially not by me, but wasn't sure if someone else was dependent on it.

The PHP timeout concerns me though because I don't yet have a sense for the "real world" table sizes.  So can someone share how many records end up being in the sales and sale_item tables by the end of the year?  I'll build a little script for myself that loads up the tables with test data.

**Comment by daN4cat** [comment] 2016-12-30 23:38
I'm testing with a real db replica. Something like 5 years of stock and transactions from a small boutique (20 / 30 sales per day max).

**Comment by SteveIreland** [comment] 2016-12-31 01:37
Thanks!

**Closed** 2016-12-31 20:37 UTC
Labels: bug

**Comment by daN4cat** [comment] 2016-12-31 21:07
OK, good and with this 3.0.2 is closed and I release it.

We can now move on and focus on 3.1.0.

**Comment by jekkos** [comment] 2017-01-01 21:45
@daN4cat Thanks for sorting this out
