### ISSUE TITLE
Sales - 502 Bad Gateway - nginx

### ISSUE THREAD

**Issue by bahcecim** [jekkos/opensourcepos#255] opened 2015-12-21 09:08 UTC
Dear all;

When I tried to use "new installed" software (Ver Version 2.3.2), I am able to enter all windows, except SALES.

System gives "502" error. 

What may cause it?

**Comment by odiea** [comment] 2015-12-21 20:36
Please go here and download the latest version and see if that helps.
https://github.com/jekkos/opensourcepos. No one has been able to reproduce that issue. More info needed. What Language are you using?

**Comment by odiea** [comment] 2015-12-21 20:42
From issue #202 by daN4cat
Well, it sounds like it's your server issue: https://bugs.php.net/bug.php?id=43761&edit=1

Please compile PHP with --enable-bcmath (and do a make distclean before, if needed). BCmath is disabled by default (See Installation section in the bcmath php.net manual pages)

I close this case since it's not an OSPOS issue

**Comment by bahcecim** [comment] 2015-12-22 07:44
Thank you;

I discovered that it was caused from PHP version. 
I changed version and problem solved.

**Comment by odiea** [comment] 2015-12-22 12:12
Thanks for the feedback. Enjoy OSPOS.

**Closed** 2015-12-26 16:17 UTC
