### ISSUE TITLE
No items selected and the bs-table toolbar buttons are active

### ISSUE THREAD

**Issue by freemail624** [jekkos/opensourcepos#1234] opened 2017-04-13 19:02 UTC
Tested with the last version
![2](https://cloud.githubusercontent.com/assets/6794450/25019411/22497e56-2093-11e7-800c-ca4dc689d7bc.jpg)

![3](https://cloud.githubusercontent.com/assets/6794450/25019416/2731aec0-2093-11e7-9320-73490ad3514d.jpg)

![4](https://cloud.githubusercontent.com/assets/6794450/25019420/29a0bb9c-2093-11e7-91e0-837dc16faf0e.jpg)

![5](https://cloud.githubusercontent.com/assets/6794450/25019426/2c0d46ac-2093-11e7-8712-52f465b21278.jpg)

Now no item selected and if someone click delete ,all the items will be deleted
![6](https://cloud.githubusercontent.com/assets/6794450/25019429/2e546ecc-2093-11e7-89c8-c3806b738081.jpg)

![7](https://cloud.githubusercontent.com/assets/6794450/25019431/312047ca-2093-11e7-9659-baaa272be65f.jpg)

![1](https://cloud.githubusercontent.com/assets/6794450/25019466/5abda546-2093-11e7-943b-f32a30556184.jpg)

**Comment by RamkrishnaMondal** [comment] 2017-04-13 20:00
Except last one, you have "DELETED" selected.

**Comment by jekkos** [comment] 2017-04-13 22:51
OK very clear description thanks to the screenshots, might be a bug I guess?

**Comment by SteveIreland** [comment] 2017-04-15 02:45
Would this be an issue that would be more appropriately reported to the wenzhixin/bootstrap-table project?  But I noticed that there are 436 open issues for that project.  So then maybe it should be fixed here?  Just wondering how this works.

**Comment by daN4cat** [comment] 2017-04-15 10:05
@jekkos do you have time to check this bug? I hope you still remember all of this from last year....

**Comment by jekkos** [comment] 2017-04-16 21:27
Yes I'll try to find some time to squash this one so we can get a new version out of the door

**Comment by jekkos** [comment] 2017-04-16 21:29
@SteveIreland well in fact I did some fixes for the bstables project itself last year. It does appear that  this project is in a rather bad (inactive) state.

**Comment by jekkos** [comment] 2017-04-17 10:06
Found another issue, which might have been introduced  in #496 here. After delete item_quantities are reset but inventory is not adapted with the difference brought into account here. This will eventually lead to the sum of differences in inventory not begin equal to the actual quantity at a given time

**Comment by jekkos** [comment] 2017-04-17 11:17
Button enabled state should be fixed now in latest master.

**Comment by daN4cat** [comment] 2017-04-17 11:30
@jekkos please run bower update. I just regen js & css file because of a regression

**Comment by daN4cat** [comment] 2017-04-17 19:45
@freemail624 @RamkrishnaMondal please test can confirm it's fixed. If fine please close this issue.

**Comment by daN4cat** [comment] 2017-04-22 11:10
I tested and this seems to me like it's fixed.

@jekkos I can't remember anymore but was it possible to search a sale by id in Takings? It doesn't look like doable.

**Closed by daN4cat** 2017-04-22 11:10 UTC
Labels: bug

**Comment by jekkos** [comment] 2017-04-22 12:54
I think it should be possible by using POS <sale_id> as search string

**Comment by jekkos** [comment] 2017-04-22 12:55
you can also open the receipt directly by changing the id in the url

**Comment by daN4cat** [comment] 2017-04-22 13:29
you are right, it's POS <sale_id> indeed
