### ISSUE TITLE
other form of payment

### ISSUE THREAD

**Issue by arteiro** [jekkos/opensourcepos#652] opened 2016-06-14 20:43 UTC
There is one other form of payment in Brazil called "fiado" would look like "indebtedness" for a few days ahead, which would be finalized the sale but the debt remains on the customer's name, where you would have to have a screen which could procesar the payment of this debt, without opening the sale. Would?
Thank you

**Comment by nadeem14375** [comment] 2016-06-15 07:31
I am searching for the same, trying to implement POS for a wholesaler, in that case the payment is not done at the time of sale. the customer pay weekly or monthly or whenever he / she can.

The same case with stock receipt, the payment to supplier is made in advance or after receiving, so in both cases customer receipt / supplier payment, we need separate forms so can receive / pay money afterword.
Thanks

**Comment by jekkos** [comment] 2016-06-16 15:53
Think this question is actually duplicate of  #371 and #24

**Closed by jekkos** 2016-06-16 15:53 UTC

**Comment by Ramatsieli** [comment] 2024-03-27 17:44
I know this matter has long been closed, but can anyone that managed to add or modify payment type kindly show me their code where they did so

**Comment by odiea** [comment] 2024-03-27 18:11
2 place you will need to add types. 1. language\your lang\sales. Add the new types there.
2. helpers/locale_helper  search for payment types then add the new types there.  Hope this helps. You will need to reproduce your new types the same as the current types. This will only give you different payment types and nothing else.

**Comment by Ramatsieli** [comment] 2024-03-28 08:51
This really helped so much... And it was very direct and straight forward.. Thank you so much 🙏🏻🙏🏻🙏🏻
