### ISSUE TITLE
Gift Cards won't submit

### ISSUE THREAD

**Issue by ferball** [jekkos/opensourcepos#545] opened 2016-05-10 16:06 UTC
When adding or editing a gift card the "submit" button does not work.  Am i missing something in the form validation?

**Comment by daN4cat** [comment] 2016-05-10 16:12
Version please

**Comment by ferball** [comment] 2016-05-10 17:17
2.4.0

**Comment by RamkrishnaMondal** [comment] 2016-05-10 17:20
Just tested, it's working fine with version 3.0

**Comment by ferball** [comment] 2016-05-10 17:36
were do I download version 3?

**Comment by RamkrishnaMondal** [comment] 2016-05-10 17:38
click on "<> Code" tab above and find "download zip" button on upper right corner.

**Comment by ferball** [comment] 2016-05-10 17:41
Thanks I was bit ignorant thinking the latest version was under the release tab

**Comment by daN4cat** [comment] 2016-05-10 17:59
Please run the db upgrade script 2.4 to 3.0

**Comment by ferball** [comment] 2016-05-11 15:37
Upgraded everything seems fine except I am now getting an "internal server error" when attempting to add gift cards.

**Comment by daN4cat** [comment] 2016-05-11 16:11
What exactly are you inputting as values in the form?

**Comment by ferball** [comment] 2016-05-11 17:47
I enter the name than it auto fills, A gift card number and an amount.  I have tried editing an existing card and just change the amount and get the same error.

**Comment by daN4cat** [comment] 2016-05-12 21:28
I'm afraid I cannot really reproduce it:

![20160512-222555_capture](https://cloud.githubusercontent.com/assets/636048/15231043/c9a9b01e-1890-11e6-9dda-4c66913bb833.gif)

**Comment by daN4cat** [comment] 2016-05-12 21:29
There must be something in specific that you do to reproduce that error.

**Comment by daN4cat** [comment] 2016-05-13 12:22
BTW, are you trying to enter a card number that is already existing or something similar?

**Comment by ferball** [comment] 2016-05-13 15:36
I am not able to edit existing gift cards either.  Is there some sort of form validation that disables the submit button?   I get the pop up window and but submit does not do anything in adding a card or editing.

**Comment by daN4cat** [comment] 2016-05-13 15:48
OK, maybe I should try again but with plain master because indeed I tried with the bootstrap-tables branch

**Comment by daN4cat** [comment] 2016-05-14 09:33
I think it's better to wait for the bootstrap-tables change to be merged in master and then we can test this again.

In bootstrap-tables branch I cannot reproduce this and there is no point to test in master and try to reproduce it when it's fine on the other branch.

**Comment by daN4cat** [comment] 2016-05-19 15:52
@ferball can you please take the latest master and try again? See if with the new tables and code it happens again.

**Comment by ferball** [comment] 2016-05-21 21:46
Still getting an "internal server error" across the bottom of the screen
when I attempt to submit a new gift gard or edit an existing one.

**Comment by daN4cat** [comment] 2016-05-22 10:29
Can you please try from a completely new database installation? It seems you are the only one able to produce and we need to exclude potential root causes as I cannot figure out what could be.

**Comment by ferball** [comment] 2016-05-24 14:55
Clean database install took care of it.  Found some extra fields in a few
tables when bringing my data over, it all seems to be working fine now,
thanks for your work on this.

**Comment by daN4cat** [comment] 2016-05-24 15:03
OK, I was at 99% confidence that it was a problem with your installation.

You need to upgrade your old database to the latest and that's the reason why you have a problem.

Case closed.

**Closed by daN4cat** 2016-05-24 15:03 UTC
Labels: pending

**Comment by ferball** [comment] 2016-05-24 16:31
I have been on the same database updateing since Version 1 so I guess
something was bound to be messed up a lot of nice changes since I first
started using the software.

**Comment by daN4cat** [comment] 2016-05-25 07:49
Maybe you should give a try with a copy of your database and upgrade it using the scripts from the version you have up one by one to the latest to bring it to vs 3.0
