### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#1242] opened 2017-04-16 21:26 UTC
With the tax story merged in master I think it's time to wrap up and iron out the last known bugs.

**Comment by daN4cat** [comment] 2017-04-16 21:29
There is some work to do in re-syncing the language files with Weblate (yet again)

**Comment by bkrajendra** [comment] 2017-04-18 16:40
Ive Update to new tax system build 3.1.0 - 4f5ad57, but i'm not getting tax module menu in menu bar. Am i missing anything?

**Comment by odiea** [comment] 2017-04-18 16:42
Yes. You have to set the permission in Employees.

**Comment by bkrajendra** [comment] 2017-04-18 16:43
Thanks @odiea I was looking for same :) 👍

**Comment by jekkos** [comment] 2017-04-18 17:14
@daN4cat resync is done and in master now. Translators should be notified shortly.

**Comment by daN4cat** [comment] 2017-04-18 17:33
Good good thanks

**Comment by bkrajendra** [comment] 2017-04-18 18:00
Is there any explanation about this new Tax module. I'm not getting it.

Why there is central TAX1 & TAX2 setting? (As ive seen taxes get calculated from Item taxes)
why there are two taxes, cant we just sum up all taxes and have it in  as item TAX
How Tax category works in addition to TAX1 & TAX2.

And finally what is Customer Sales Tax Support?
Sorry to bother you all but you can point me to some resource, I'll go through it!

**Comment by daN4cat** [comment] 2017-04-18 18:15
Read the wiki

**Comment by jekkos** [comment] 2017-04-20 06:34
dotenv support added now in latest master. i've added a bit of explanation to the wiki on how to set it up.

**Comment by daN4cat** [comment] 2017-04-22 16:18
Closed the issue related to printing or not the company name to avoid duplications with logo and committed all the Mailchimp connector work.

**Comment by daN4cat** [comment] 2017-04-22 16:20
We should be good with 3.1.0, we just need @SteveIreland to finish this tax work down to the bit.

**Comment by SteveIreland** [comment] 2017-04-22 20:13
Income producing work has put a bit of pressure on my time this week, but I've been working upgrading sales history as time permits.

So just to review, at this point am I correct in believing that there are no sales tax related issues that need to be addressed that I overlooked?
 
And the only two things you are waiting on me for is first an option to update the new tax fields in `sales_items_taxes` and and  to populate `sales_taxes`.  

Then secondly you need me to update the reports to be based on these new fields (hopefully mitigating the report errors resulting from tax_rounding issues) .... right?

Originally I assumed that this was just limited to updating the two tables and report SQL  But migration could actually involve migrating over to the new sales tax module.  This would involve clearing the tax files on the item files and automatically creating the tax category tables from what exists.  But I don't think this is what anyone is expecting but I just wanted to throw this out to make sure that no one was expecting that .... because that would take a significant bit of effort to work through the complexities.

**Comment by daN4cat** [comment] 2017-04-22 20:55
@SteveIreland work comes first always and of course family life too.
So no worries if you don't have time now, we can wait.

The idea is to have just one tax story and migrate the old to the new with an upgrade.
I guess you can read from config table the existing taxes and create them in your new module and then upgrade all items and sales taxes to point to the new module taxes.
Yes all the rest needs to work with the new tax module.

Hope this makes sense.

I don't see any other issue after you fixed one and I fixed the other introduced by mistake. I juggled your merge whilst working on what I committed today and one file got mixed up.

**Comment by SteveIreland** [comment] 2017-04-22 21:07
Okay, thanks for confirming it for me.  The way things are going at the moment it looks like it will probably be next weekend before I have my first iteration, but I'll try to have it earlier.

**Comment by daN4cat** [comment] 2017-04-23 05:29
It's OK.  If I find the time I'll check how to script the db change. But cannot guarantee I have much time today.

**Comment by daN4cat** [comment] 2017-07-06 20:28
@SteveIreland what's left now from your magic hat? Just the tax category and tax tab in StoreConfig or something more?

**Comment by daN4cat** [comment] 2017-07-06 20:28
@jekkos there are a couple of outstanding issues on you that would be great if you could fix so we wrap up here this 3.1.0 release.

**Comment by daN4cat** [comment] 2017-07-06 20:28
... and then we enjoy the summer!

**Comment by daN4cat** [comment] 2017-07-06 21:40
@jekkos you'll need to resync the language files as some new english strings were added and some changed. So we can get the translations back before we can close 3.1.0.

**Comment by jekkos** [comment] 2017-07-06 22:06
Already enjoying summer for sure.. You're right I need to finish up these issues, will probably do that coming days (have to get back in the 'zone' first)

**Comment by daN4cat** [comment] 2017-07-07 04:53
O'right...

**Comment by SteveIreland** [comment] 2017-07-07 12:28
Don't resync language files just yet.  I'm setting up the tax config panel and that will affect the language files a bit.

**Comment by daN4cat** [comment] 2017-07-07 17:46
@SteveIreland what else do you have in mind to do after that tax configuration story? Not sure there is more to do beside just test what we have, jekkos docker stuff, add a bit of documentation on the wiki for a couple of features.

**Comment by SteveIreland** [comment] 2017-07-07 18:33
For this release I think I can cut it off.  Based on recent requests there is a lot more that needs to be done in the area of taxes ... particularly tax reporting, but I those changes can wait until the next release if you are comfortable with what is there.

**Comment by daN4cat** [comment] 2017-07-07 19:45
I'll check later but probably if there was something else you said you wanted to work but indeed it would be better to cut off here.
There would be more to do on tax side as now there will be 3 different things and I'm worried it will be confusing. Customer tax, tax categories and tax rates... somebody will need to clarify this.

**Comment by SteveIreland** [comment] 2017-07-07 22:02
Taxes?  Clarity?  "To dream, the impossible dream ..."

I think earlier I wanted to address the tax calculation in the reports.  But I'll defer that until after 3.1.0 is published.

**Comment by daN4cat** [comment] 2017-07-08 06:16
Yes tax will need another step with the next release.

**Comment by jekkos** [comment] 2017-07-09 11:50
Ok we can do another iteration afterwards but I find it quite important to have consistent figures in sale / receivings and reports.. so not sure what you mean with addressing tax caluclation in the reports? Is this just a refactoring we're talking about or a functional problem here?

**Comment by jekkos** [comment] 2017-07-09 11:50
@SteveIreland I'll await your approval for language file sync..

**Comment by SteveIreland** [comment] 2017-07-10 03:43
@daN4cat I noticed that some of the cleanup involved changing the sales documents to print taxes with the number of decimal positions specified in the "tax decimals".  For US tax, the tax amounts are required to be printed on the documents with currency decimals and the number of tax decimals is used to refine the intermediate tax calculation per the regulations specified by the regulating tax jurisdiction.

**Comment by daN4cat** [comment] 2017-07-10 04:57
@SteveIreland ok I'll put currency decimals back in receipt and invoice. Not sure if reports can stay with 3 or need to be changed too?

**Comment by SteveIreland** [comment] 2017-07-10 11:31
I'd suggest leaving the tax amounts for reporting purposes at tax decimal positions - especially at the detail level which might help explain to some why details tax amounts don't always match the total tax amounts which should always be rounded to the currency decimal (even if it's displayed with the tax decimals).  But if you decide to use the currency tax decimal positions in the sale and summary totals that would work for me too.

**Comment by daN4cat** [comment] 2017-07-11 22:04
All the reward, table, tax category config don't work properly. You can add but not remove or it gets removed but not added. It's a common error that needs to be fixed and replicated in all the save config functions.

**Comment by SteveIreland** [comment] 2017-07-12 03:54
Thanks for updating master with the  pull requests.  I was surprised when you mentioned that tax categories were not updated properly.  So I just now downloaded the latest master and tested it.   Tax category removal is working but not the additions.  I'll have it fixed by tomorrow night, I had the  category maintenance working on adds but it looks like my changes to fix the removals broke the adds and I forgot to come back and test that.   As Home Simpson would say Duh-Oh!

**Comment by SteveIreland** [comment] 2017-07-12 04:01
At least the success notification is popping up now.  Thanks!

**Comment by daN4cat** [comment] 2017-07-12 21:40
Now all the add entries in config allow to add, rename and etc. but not delete.
Quite some mistakes but the root cause of delete is unclear. Also the ajax call to refresh the table might play a role... not sure that's doing the right thing here. It might not actually

**Comment by SteveIreland** [comment] 2017-07-13 01:46
I implemented the delete functionality by make sure that the array of key values to be saved was updated with the actual value of the record that was just added (it changes due to the AUTO_INCREMENT functionality but I see that code was refactored out.

If you  restore that (within the context of the changes you made) then hopefully the delete functionality will be restored.

**Comment by daN4cat** [comment] 2017-07-13 05:49
The problem was that the old was throwing an exception so I reused the same approach as the other similar pieces of functionality. However I will check what you did and restore the basic logic.

**Comment by daN4cat** [comment] 2017-07-13 21:48
OK, add and remove of entries in Rewards, Location, Table and Tax category in Store Config is now working fine. Took a while to get what the problem was but I don't think the original code was ever right or at least working for all the cases.

**Comment by daN4cat** [comment] 2017-07-13 22:04
@jekkos can you please now resync all the language stuff?

I'm going on holidays for two weeks, so hopefully we get the last couple of fixes in and the translations too. Some more testing and we should be good to release 3.1.0 at the end of the month.

But please guys let's try to give this last push before jumping on 3.2.0 boat :-)

**Comment by daN4cat** [comment] 2017-07-28 21:17
@jekkos probably another resync of language is required given the latest additions/amendments.... never ending story

**Comment by daN4cat** [comment] 2017-08-13 16:25
@jekkos we need a final language sync and hopefully we get Weblate translations back before we can finally release this 3.1.0. I aim to release it in two weeks time, just some more testing and translation contributions.

**Comment by saruban** [comment] 2017-08-29 09:36
Hope it will be released before this week end

**Comment by daN4cat** [comment] 2017-08-29 10:01
I'm waiting for @jekkos to sort out the en_gb translation issue. I probably need to check if anything else is left open. If not we should be good to release after a bit of notes write up.

**Comment by jekkos** [comment] 2017-08-29 10:01
It will be released when it's done.. there's currently still a couple of issues open that need investigation / fixing

**Comment by saruban** [comment] 2017-08-29 14:10
Great.  Thanks for making the ospos more and more best

**Comment by SteveIreland** [comment] 2017-08-29 14:12
Surely there will be a 3.1.1 release the following week ... right?   :-)

**Comment by daN4cat** [comment] 2017-09-02 10:11
@jekkos all 3.1.0 issues are closed. I believe we are good to release as I didn't hear any major complaints in recent time.

Please @odiea @SteveIreland whilst I prepare the release notes, make sure language support is working fine with American English. There is an upgrade line at the end of the 3.0.1 to 3.1.0 database script that should change from en to en_US and I set en_US as default in new installations.

**Comment by saruban** [comment] 2017-09-02 10:53
Great to hear from you @daN4cat 
In future i will try to contribute surely.

**Comment by odiea** [comment] 2017-09-02 11:25
For some reason I get the following error using the db update. Changes lang from en to en-US after I manually changed it in app_config.

UPDATE `ospos_app_config` SET `language_code` = 'en-US' WHERE `language_code` = 'en';
Error
SQL query:
UPDATE `ospos_app_config` SET `language_code` = 'en-US' WHERE `language_code` = 'en'
MySQL said: Documentation

#1054 - Unknown column 'language_code' in 'where clause'

**Comment by daN4cat** [comment] 2017-09-02 11:41
@odiea yes, correct that's a mistake. Fixing

**Comment by daN4cat** [comment] 2017-09-02 11:44
fix in master. thanks for the bug report @odiea

**Comment by odiea** [comment] 2017-09-02 12:01
@daN4cat Works great now.

**Comment by daN4cat** [comment] 2017-09-02 12:03
so, are we good now?

**Comment by daN4cat** [comment] 2017-09-02 12:20
OK, release notes and etc are ready.
I'm just waiting for Travis CI to complete the build and then I take bintray zip file and add to the release.

Once that's done, @jekkos @odiea @SteveIreland are you ok to release 3.1.0?

**Comment by SteveIreland** [comment] 2017-09-02 12:32
Yes please.  I am champing at the bit to start 3.2.

**Comment by jekkos** [comment] 2017-09-02 12:39
@daN4cat thanks for getting it out of the door! Lots of hard work done, thanks to all involved.

**Comment by daN4cat** [comment] 2017-09-02 12:39
Good, so everything is ready. I push the magic button!

**Comment by daN4cat** [comment] 2017-09-02 12:40
Done: it's released! https://github.com/jekkos/opensourcepos/releases/tag/3.1.0

**Closed by daN4cat** 2017-09-02 12:40 UTC
Labels: enhancement

**Comment by SteveIreland** [comment] 2017-09-02 12:48
Awesome!  Thank  you all.  So now are we starting on 3.1.1 or 3.2?  In other words ... how I should name the next database migration script?

**Comment by jekkos** [comment] 2017-09-02 13:12
It depends, I would do one extra minor release as we will probably have more users on 3.1 soon that might reporting bugs we didn't find yet..

**Comment by daN4cat** [comment] 2017-09-02 13:16
@SteveIreland starts with 3.1.0_to_<feature>.sql then we can merge all those upgrade scripts in one.

I agreed with @jekkos that we should wait as we might get a 3.1.1 for some minor issue or even for translation only.

**Comment by daN4cat** [comment] 2017-09-02 13:20
@jekkos any idea why the badge in readme page still shows 3.0.2? I remember having fixed that once... but can't remember what was :-(

**Comment by daN4cat** [comment] 2017-09-02 13:27
I remember, I fixed older tags because we needed to follow the semantic version. The tag is correct 3.1.0, it probably requires a bit of time before it's synchronised (I suppose....)

**Comment by saruban** [comment] 2017-09-03 02:47
What is the different between opensourcepos.20170902121753.3.1.0.52ab4c.zip and 
Source code (zip) in releases.

**Comment by daN4cat** [comment] 2017-09-03 05:41
Long name zip is the full installation

**Comment by saruban** [comment] 2017-09-03 07:56
Thanks.

**Comment by daN4cat** [comment] 2017-09-03 12:54
Readme page badge now reports 3.1.0.
