### ISSUE TITLE
deleted table at sales

### ISSUE THREAD

**Issue by likozhang** [jekkos/opensourcepos#677] opened 2016-06-20 13:23 UTC
index.php/sales/manage
how if staff delete the table, admin want to see, what item will be deleted

**Comment by daN4cat** [comment] 2016-06-21 08:21
You cannot delete a db table.

If you refer to bulk delete then you can always add a log of the delete action in the inventory so you know who did what like when you add an item, change and item and etc.
It would be probably a nice addition to show in the item log that action.

**Comment by odiea** [comment] 2016-06-21 10:25
I think he wants to know how to locate a deleted sales after someone deletes it in Takings.

**Comment by daN4cat** [comment] 2016-06-21 10:37
Indeed, it's sales not items...

**Comment by likozhang** [comment] 2016-06-21 12:14
lol you know what i mean, thanks
can you help me show item filter deleted item like at item?

**Comment by onyema3** [comment] 2016-06-21 18:51
How can one locate a deleted sale after it is deleted from takings??

**Comment by odiea** [comment] 2016-06-21 18:56
Currently the Sale is no longer in the database. So I believe there is no way to view or restore the Sale at the moment.

**Comment by likozhang** [comment] 2016-06-22 16:54
@odiea you mean if staff do delete acton at takings
admin dont know what to do next ?

**Comment by daN4cat** [comment] 2016-06-22 16:57
sales are completely wiped from database, so when they are gone they are gone.

Probably we should adopt a deleted field as for the rest and never really remove a sale, which would make more sense to me.

**Comment by onyema3** [comment] 2016-06-22 23:27
I agree

**Comment by daN4cat** [comment] 2016-06-23 10:04
I close this as duplicate of #682.

**Closed** 2016-06-23 10:04 UTC
Labels: enhancement, needsowner
