### ISSUE TITLE
### Bug - Inventory Reports - Only Exports Current Page

### ISSUE THREAD

**Issue by waynebr76** [jekkos/opensourcepos#1059] opened 2017-01-04 10:25 UTC
### Expected behaviour
On previous versions running and inventory report and exporting exported all of the inventory

### Actual behaviour
In Version 3> exporting from the inventory report only exports the current page

### Steps to reproduce the issue

Select Reports, Inventory Report, then select export

**Comment by jekkos** [comment] 2017-02-12 14:31
Duplicate of #868

**Closed** 2017-02-12 14:39 UTC
