### ISSUE TITLE
Fixed price discount

### ISSUE THREAD

**Issue by wak29** [jekkos/opensourcepos#302] opened 2016-01-25 08:27 UTC
1. can you please help me in changing the discount in % form to be fixed discount entered during sale, instead of percentage 

2.  on the sale screen:
Delete   Item#   Item Name       Price       Qty.  Discount   Total  Edit

change to 

 Delete   Item#   Item Name       Qty.      Price  Discount   Total  Edit

swaping the price and Qty. Positions on sale and on Recipt?

I am new to this and I really appreciate your help.

**Comment by cpl2015** [comment] 2016-01-25 12:11
Ah, more and more users are requesting for 'Per UNIT Flat discount'. I am also feeling the need  for a 2nd discount badly. Problem is I can not do it myself,  @daN4cat   Can you add this feature in 2.4 ?

**Comment by daN4cat** [comment] 2016-01-25 14:20
We need to think about and how to manage the mix cases and so on.

**Comment by jekkos** [comment] 2016-01-25 14:49
Yes maybe add a bounty on this one as I'm not really motivated to do it.

**Comment by jekkos** [comment] 2016-01-25 14:54
I think that this is one that would take some time. I always end up struggling with this part of the app as there's different states and transitions in the sales flow that need to keep track of data (and allow manipulation of the sale). This is also due to the different testing scenarios that derive from settings like tax inclusive pricing, different ways to show the discount on receipt, etc

**Comment by jekkos** [comment] 2016-01-25 20:47
Duplicate of #286 . Maybe try to keep comments in one issue so we don't lose the overview

**Closed by jekkos** 2016-01-25 20:47 UTC
Labels: enhancement

**Comment by wak29** [comment] 2016-01-27 11:39
okay, so I assume its not possible with small fix. you guys totally ignored the 2nd change :( any thoughts about that one? I tried to change the order but but values show wrong 

Price   Qty.
$12      3

Qty.    Price
$12      3

**Comment by cpl2015** [comment] 2016-01-27 13:00
You have swapped only one of the following line. Need to swap both of them in sales/view/receipt 

![800](https://cloud.githubusercontent.com/assets/15803637/12614123/edb44138-c523-11e5-931c-0b17a3ce2436.png)


![900](https://cloud.githubusercontent.com/assets/15803637/12614130/f13131cc-c523-11e5-9804-1b54920eb3cb.png)

**Comment by daN4cat** [comment] 2018-09-03 20:44
See #261, it fixes this problem.
