### ISSUE TITLE
Complete button not available if amount tendered = amount due

### ISSUE THREAD

**Issue by usergroup81** [jekkos/opensourcepos#733] opened 2016-07-11 21:04 UTC
I've come across a few transactions where the radio button is not available if you add the amount tendered = to amount due. 

No "complete" button 
![opensourcepos](https://cloud.githubusercontent.com/assets/20194509/16746530/c05c53be-4788-11e6-9742-2c9029a1d846.PNG)

To show the "complete" button, I had to add one more cent here
![opensourcepos2](https://cloud.githubusercontent.com/assets/20194509/16746542/c83959f6-4788-11e6-98bc-9a85d1e54416.PNG)

Now the button is available
![opensourcepos3](https://cloud.githubusercontent.com/assets/20194509/16746546/cb8a7072-4788-11e6-9787-3aad07149dea.PNG)

Test system info:
Open Source Point Of Sale Version	3.0.0 - 1c4e5093bfbc
Windows 10 32-bit running WAMP 2.4
Apache 2.4.9
MySQL 5.6.17
PHP 5.5.12
English

**Comment by daN4cat** [comment] 2016-07-12 15:53
This must be due to the precision, decimals in the comparison.

**Comment by jekkos** [comment] 2016-07-15 21:01
Can you retest  with latest version?

**Comment by usergroup81** [comment] 2016-07-16 18:21
Tested:
`1 parent 68deca1 commit a66868651bec6182d7d7b702f6a0571c912a1a10 @daN4cat daN4cat committed 23 hours ago`

Still having issues on some transactions not showing complete button:
![ospos_bug733](https://cloud.githubusercontent.com/assets/20194509/16896401/90238f4c-4b60-11e6-8c98-f99fbd2ca151.PNG)

**Comment by daN4cat** [comment] 2016-07-16 19:31
The tax is 15.804, it's the 0.004 the issue. The comparison at the moment is <= 1e-6 but it should be < 0.005 as the smallest amount that can be rounded up (if not the rounding then it should be < 0.01).
But it needs to be properly checked and tested and I don't have the time to do the change now.
If @jekkos cannot do in the next days I'll do when back from my holidays.

**Comment by odiea** [comment] 2016-07-16 20:24
Will it still give you this issue if you change your tax decimal to 2?

**Comment by usergroup81** [comment] 2016-07-17 02:12
@daN4cat no rush. I rolled back to a version not affected by this bug for now. 
@odiea I changed the tax decimal from 3 to 2 but issue still persists.

**Comment by jekkos** [comment] 2016-07-17 12:33
I did a fix for this issue. payments_cover_total now compares the amount due with 0 using the scale set by currency_decimals.

**Comment by jekkos** [comment] 2016-07-17 12:40
In this case I guess all calculations should be done using currency_decimals * tax_decimals for the decimal scale precision. Rounding can then be done in the end by the numberformatter for the configured currency to reduce the final error as much as possible.

**Comment by jekkos** [comment] 2016-07-17 12:43
So if we want to take rounding strategy into account to check if the sale is complete I think we'll need to get the formatted currency from the amount due and compare it with 0 on a currency_decimals scale precision

**Comment by odiea** [comment] 2016-07-17 12:45
After your last commit I now have this issue.
![2016-07-17 06_44_24-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16900715/05516864-4bea-11e6-8858-54b95023d8cc.png)

**Comment by jekkos** [comment] 2016-07-17 12:47
Ok might be better to revert this temporarily and look into the rounding issues first

**Comment by odiea** [comment] 2016-07-17 12:47
Good Idea.

**Comment by jekkos** [comment] 2016-07-20 18:46
OK did a fix for this.. precision for calculations is set to quantity precision * tax. In the end everything is rounded to the configured currency precision. I guess that will be sufficient to avoid any obvious rounding issues.

**Comment by odiea** [comment] 2016-07-20 18:57
Current issue is it is not charging sales tax now.
![2016-07-20 12_51_27-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/16999096/86eca47e-4e79-11e6-9a01-d4b786564d25.png)

**Comment by odiea** [comment] 2016-07-20 20:34
Here is what I get if tax included is checked.
![2016-07-20 14_32_58-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/17002114/1c9bcdee-4e87-11e6-992f-0e45a6b7c2e8.png)

**Comment by jekkos** [comment] 2016-07-20 23:50
Ok this is weird ;. this part seems to work ok here.
![schermafdruk van 2016-07-21 01-50-17](https://cloud.githubusercontent.com/assets/576234/17007011/86dad39a-4ee5-11e6-854f-3a4dda35c36b.png)

**Comment by jekkos** [comment] 2016-07-20 23:51
this screencap was taken after enabling tax inlcusive option
![schermafdruk van 2016-07-21 01-51-05](https://cloud.githubusercontent.com/assets/576234/17007026/a1de1648-4ee5-11e6-8226-403ec2fd10f7.png)

**Comment by odiea** [comment] 2016-07-21 00:27
I just downloaded a fresh copy to see if it was a bad pull. I still have the same issue.
![2016-07-20 18_25_52-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/17007631/9ac9c444-4ea7-11e6-90e4-7f6026edfb67.png)

**Comment by jekkos** [comment] 2016-07-21 10:23
OK Just did some more testing I'll need to look into it later.. will  be off for the rest of the day. I tested this in a local docker setup and was verifying that everything is uptodate. I have recreated the image and still get an ok test.

**Comment by odiea** [comment] 2016-07-21 11:44
I reverted the update and all is fine now.

**Comment by odiea** [comment] 2016-07-21 20:25
It has something to do with removing PRECISION. I cherry picked that commit and it went south after I removed all the PRECISION

**Comment by usergroup81** [comment] 2016-07-22 15:43
Same here, tax is not calculated with commit d8e4bf48d84ac81c9ab20b34d2765028c7cc5415:
![tax_not_calculated_cc5415](https://cloud.githubusercontent.com/assets/20194509/17062570/6ce70ff4-5001-11e6-89f0-3f9b650785c1.PNG)

**Comment by jekkos** [comment] 2016-07-22 20:54
OK indeed I can reproduce now will have a closer look

**Comment by jekkos** [comment] 2016-07-25 16:32
Ok hope we can close this one soon (after having latest validated)

**Comment by usergroup81** [comment] 2016-07-27 23:20
Awesome! Thank you!

**Comment by jekkos** [comment] 2016-07-30 08:21
I found that amount due would sometimes be negative zero (see also your last screenshot). Also when one would decrement the smallest decimal by one for a new payment amount, the sum of amount paid + amount due would sometimes not be correct. This is due to the totals being more precise in the actual amount due calculation in comparison with the user entered amount paid.

I think it'd be better to round this amount due substracting the entered amount paid. This latter amount can never be more precise than the number of set currency decimals. This is needed to make the total sum of amount due + amount paid correct at all times.

I did a patch for this but maybe someone needs to test it first.

**Comment by odiea** [comment] 2016-07-30 12:25
It appeared to be working better before your last update.
![2016-07-30 06_19_13-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/17270355/f7b94cd8-561d-11e6-82dd-71e01b3cc073.png)
This should show the complete sale button.

**Comment by odiea** [comment] 2016-07-30 12:31
Sorry was having GitHub issues. This is what it looks like after pressing the add payment button again.

![2016-07-30 06_19_42-microsoft edge](https://cloud.githubusercontent.com/assets/10962177/17270401/07157fa2-561f-11e6-8421-e997fc6cbb79.png)

**Comment by jekkos** [comment] 2016-07-30 13:50
OK I guess amount due should be zero or negative to show the complete button?

**Comment by odiea** [comment] 2016-07-30 14:00
You can also see in the second image the customer got screwed out of his change due after hitting the last add payment button to show the complete sale button.

**Comment by odiea** [comment] 2016-07-30 14:37
@jekkos  I know it would be extra work but maybe you could consider creating another branch with these updates so they can be tested first before the commits go into Master. I think there could be less issues then.

**Comment by jekkos** [comment] 2016-07-30 15:09
I was in doubt whether to do it in a branch or not, next time I will. Pushed another one hope this is resolved now

**Comment by odiea** [comment] 2016-07-30 19:23
The Register appears to be functioning properly now.

**Closed** 2016-08-01 11:31 UTC
Labels: bug
