### ISSUE TITLE
Takings issue when the same item with a serial number is entered twice.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1134] opened 2017-02-09 22:43 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report

Takings is showing the ticket was over paid.  Detailed Reports looks ok. 

![2017-02-09 15_27_53-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22806185/0e9d12f0-eede-11e6-9e07-f2c5a227dc87.png)
![2017-02-09 15_38_40-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22806252/6a647952-eede-11e6-932f-c2c724167246.png)

**Comment by daN4cat** [comment] 2017-02-13 22:22
@odiea I tried changing serial number on one item, doing transactions with different serial number, same serial number but it all looks fine to me. Taking and Detail Sales look the same.
There must be something different that I'm not able to reproduce this. Please write down a simple test case with exact sequence to reproduce the issue. Thanks.

**Comment by odiea** [comment] 2017-02-13 22:53
All I do is enter the same item number twice. I do not fill out the serial (I did the last time with no changes).
![2017-02-13 15_36_41-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22906960/2cb1cd8e-f204-11e6-99c9-1e181a995984.png)
![2017-02-13 15_37_08-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/22906966/3043dd8e-f204-11e6-91c7-7ba89b1d7a2e.png)

**Comment by odiea** [comment] 2017-02-13 23:11
For some reason it appears that in Takings it is doubling the tax when it displays the info. Thus the increased total.
![2017-02-13 16_06_18-localhost _ 127 0 0 1 _ ospos1 _ ospos_sales_items_taxes _ phpmyadmin 4 5 1 and](https://cloud.githubusercontent.com/assets/10962177/22907511/bc4bd8c0-f206-11e6-9251-77defb89725e.png)

![2017-02-13 16_06_59-localhost _ 127 0 0 1 _ ospos1 _ ospos_sales_payments _ phpmyadmin 4 5 1 and 1 m](https://cloud.githubusercontent.com/assets/10962177/22907514/bfc6f7aa-f206-11e6-9d27-d47089d8f544.png)

**Comment by odiea** [comment] 2017-02-13 23:27
If I had the knowledge to fix this . I would store the tax amount in either Payments or Replace the Sales Tax row with the Tax amount calculated by the Sale. So my assignment is to learn this stuff.

**Comment by daN4cat** [comment] 2017-02-18 22:01
I'm sorry, I'm trying to reproduce but still no luck as it is all fine to me:

![image](https://cloud.githubusercontent.com/assets/636048/23097185/a3434386-f625-11e6-8dd7-d8996a3ea3da.png)

![image](https://cloud.githubusercontent.com/assets/636048/23097200/bf07792a-f625-11e6-97d2-df06d926dc3d.png)

![image](https://cloud.githubusercontent.com/assets/636048/23097203/d9b5bfe8-f625-11e6-80a3-107f4d08ead4.png)

**Comment by daN4cat** [comment] 2017-02-18 22:03
The only thing I can see it's the tax rounding issue, but that's a different story and something for another ticket.

**Comment by odiea** [comment] 2017-02-20 20:01
New Master same issue. I will close this if no one else can reproduce it. Here is what I got on the new master. Normally I do not use both Sales Taxes I will just use a combined Sales Tax.
![2017-02-20 12_56_11-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23140013/8791f9fa-f76c-11e6-9130-1ea0d263cad3.png)

**Comment by daN4cat** [comment] 2017-02-20 23:09
Mhhh the only thing I didn't test and I bet it's the difference here is adding tax not tax included. Here in UK and EU is tax included, in the US is net price + taxes.

**Comment by daN4cat** [comment] 2017-02-26 22:32
I'll fix this together with the double taxation issue.

**Comment by daN4cat** [comment] 2017-02-27 00:03
@odiea can you please check this issue too with latest master and see if you can still reproduce it?

**Comment by odiea** [comment] 2017-02-27 00:48
Sorry. SOS . Will do more testing later. Gotta go get my grandson.

**Comment by odiea** [comment] 2017-02-27 01:27
I don't know if this image will shed any more light on the subject or not. This has a 7.4 and a 3.0 Sales Tax. It appears to me that both Items are showing the total tax and not the tax per Item.
![2017-02-26 18_22_36-wedidit _ powered by ospos 3 1 0](https://cloud.githubusercontent.com/assets/10962177/23345809/cef2f720-fc50-11e6-9447-de88584ac9ca.png)

**Comment by daN4cat** [comment] 2017-02-27 07:13
Ok, clear there is no distinction between the two items at tax calculation level. One more step... to fix.

**Comment by daN4cat** [comment] 2017-03-13 21:12
@SteveIreland are you considering this case of serialised items too?

**Comment by SteveIreland** [comment] 2017-03-13 23:01
I'll go ahead and include a fix for this.  I just need to add the line number to the join criteria..

**Comment by daN4cat** [comment] 2017-03-13 23:04
Yes that needs to happen.

**Comment by daN4cat** [comment] 2017-03-14 07:10
Fixed in #1133

**Comment by daN4cat** [comment] 2017-04-16 08:19
@odiea is this now fixed in master?

**Comment by odiea** [comment] 2017-04-16 11:09
Yes. This issue has  been resolved.

**Comment by daN4cat** [comment] 2017-04-16 18:08
Great. Good job @SteveIreland many thanks!
And thanks @odiea for all the test.

**Closed** 2017-04-16 18:09 UTC
Labels: bug
