### ISSUE TITLE
Expiry Dates

### ISSUE THREAD

**Issue by tenkodoy** [jekkos/opensourcepos#1565] opened 2017-09-08 13:08 UTC
@daN4cat @odiea 
I'm operating a little drug store and the need for me to add expiry dates and notifications have become necessary. If someone can give me brief tutorials maybe I can work it out myself if not I probably would have to make some donations so it could be done for me. Thank you!

**Comment by odiea** [comment] 2017-09-08 13:17
Currently everyone is busy getting this current version out. You may have to find someone to set that up for you then donate it back to OSPOS would be great.

**Comment by tenkodoy** [comment] 2017-09-08 13:32
@odiea Ok I hear. Do you have any contributor in mind that could help with this

**Comment by daN4cat** [comment] 2017-09-08 17:10
Discussed in #1137 and duplicate of #1426, #1215.

I can see that both people asked questions and nobody ever contributed anything.

**Closed** 2017-09-08 17:13 UTC
Labels: duplicate
