### ISSUE TITLE
Discount with Amount instead percentage

### ISSUE THREAD

**Issue by ishtiaquesarwar** [jekkos/opensourcepos#1207] opened 2017-04-01 14:42 UTC
Hello

can any one tell me how to give an amount discount instead percentage 

For example 
X product cost: 950 
discount: 100
actual payable: 850

Currently it has 10%-100% percentage type of thing, but i want like amount discount instead discount with percentage. How to do it please let me know

thanks

**Comment by daN4cat** [comment] 2017-04-01 14:51
Duplicate of #261

**Closed by daN4cat** 2017-04-01 14:51 UTC
