### ISSUE TITLE
Change the store\'s configuration 

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#247] opened 2015-12-10 21:23 UTC
Will someone please change this desc in Modules.Change the store's configuration

**Comment by RyanfaeScotland** [comment] 2015-12-10 22:51
To what? Why? Where does it appear in the front end (I know where it is in the code but can't find it on the front end to test changes)

**Comment by odiea** [comment] 2015-12-10 22:54
It appears on the Home page when you first log into ospos. I believe it is the bottom Item. To me it is just an annoyance but I believe someone else brought it up too.

**Comment by RyanfaeScotland** [comment] 2015-12-10 23:00
Ah yes I see it and see the issue. I never scroll down that far in normal usage, preferring the buttons up top!

That's it fixed on my branch. Just in the middle of trying to get a test merge/review done with some of my work, hopefully this will spur it on. ;)

**Comment by odiea** [comment] 2015-12-10 23:16
Total Customers Wanting Stuff (Ignore the Pound Sign!): $2.00 What does this reference in your comments report?

**Comment by RyanfaeScotland** [comment] 2015-12-10 23:32
Just a count of the customers on the screen. Only the customers with comments are pulled onto the report as we use the comments for customer requests. This report lets us see how many customers are looking for items and what items they are looking for.

The formating of the currency sign is hard coded into the summary so for now I've just marked it as Ignore the Pound Sign (it is dollars in yours) but eventually I want to remove the formatting from the base class and have it render what it is passed.

**Comment by odiea** [comment] 2015-12-10 23:56
Ok. Thanks for the info.

**Comment by RyanfaeScotland** [comment] 2015-12-11 00:01
No worries. If I ever figure out how to get these gh_pages working I'll write this up as I go.

Inventory Facebook is a public ready inventory list. Only shows items that have > 1 quantity along with selling price, category and quantity. Great for copy and pasting to Facebook to let people know what you currently have in stock! (Although I plan on removing category and quantity as they make it a bit messy)

**Closed** 2015-12-11 11:29 UTC
Labels: bug

**Comment by jekkos** [comment] 2015-12-11 11:30
Duplicate of #138
