### ISSUE TITLE
how to set js printset up 

### ISSUE THREAD

**Issue by ravillasri** [jekkos/opensourcepos#189] opened 2015-10-04 08:33 UTC
jekkos gentleman , i want to know about how the js printsetup work  to print the receipt 
i follow some process as follows.
i downloaded jsprintsetup addon in mozilla firefox 
i configure some receipt in the store config some fileld like marfin left top and right. etc.....,
now is it work directly or i need do some  more configs in our files plesase   help me on this issue 
 i connected the some other band printer not epson

**Comment by jekkos** [comment] 2015-10-04 20:37
Did you select a printer from the dropdown list? If the addon is installed ok then a dropdown should appear.

**Comment by ravillasri** [comment] 2015-10-05 06:08
ya sir i selected the printer please the screen shot ticket printer right

On Mon, Oct 5, 2015 at 2:07 AM, jekkos <notifications@github.com> wrote:

> Did you select a printer from the dropdown list? If the addon is installed
> ok then a dropdown should appear.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/189#issuecomment-145385553>
> .
>



-- 
*Thanks&Regards*
*R.Srinivasulu*
*9494686121*

**Comment by ravillasri** [comment] 2015-10-05 07:27
one more issue is after adding items into cart suppose i added same item 3
quantities and then total is given single price qunatit not the  total
quantity please check the image as below pinged
ie... added one item price is 40
and their quantity is 3 toatal is item* qunatity ie..,40*30 ie is 120 but
it is giving 40 only

On Mon, Oct 5, 2015 at 11:38 AM, Srinu Ravilla <srinufresher2015@gmail.com>
wrote:

> ya sir i selected the printer please the screen shot ticket printer right
>
> On Mon, Oct 5, 2015 at 2:07 AM, jekkos <notifications@github.com> wrote:
>
>> Did you select a printer from the dropdown list? If the addon is
>> installed ok then a dropdown should appear.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jekkos/opensourcepos/issues/189#issuecomment-145385553>
>> .
>>
>
>
>
> --
> *Thanks&Regards*
> *R.Srinivasulu*
> *9494686121*
>



-- 
*Thanks&Regards*
*R.Srinivasulu*
*9494686121*

**Comment by glassen** [comment] 2015-10-05 16:12
I have the same issue with line totals as can be read in issue #165. There is a workaround if you press the "Edit Item" button for every line with multiple items. Then your receipt or invoice will be correct.

**Comment by ravillasri** [comment] 2015-10-05 17:34
ya that fine jekkos i also find the that edit item  thanks and what about
 the print setup issue daling

On Mon, Oct 5, 2015 at 9:42 PM, glassen <notifications@github.com> wrote:

> I have the same issue with line totals as can be read in issue #165
> <https://github.com/jekkos/opensourcepos/issues/165>. There is a
> workaround if you press the "Edit Item" button for every line with multiple
> items. Then your receipt or invoice will be correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jekkos/opensourcepos/issues/189#issuecomment-145585399>
> .
>



-- 
*Thanks&Regards*
*R.Srinivasulu*
*9494686121*

**Comment by jekkos** [comment] 2015-10-09 12:06
Duplicate of #165, will close.

**Closed by jekkos** 2015-10-09 12:06 UTC
