### ISSUE TITLE
Deleted spaces when searching items

### ISSUE THREAD

**Issue by petercstevenson** [jekkos/opensourcepos#838] opened 2016-09-05 02:29 UTC
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [ ] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [x] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [ ] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Installation information

Web installation

### Expected behaviour

When searching for items in "Items" screen text should show up as typed

### Actual behaviour

Spaces get deleted if not typing very quickly. Also, there are frequently missing digits when using barcode scanner (which I assume is the same issue, but it could be a separate bug)

### Steps to reproduce the issue

When searching for an item, type a word. Then press the space bar. After about a half of a second the space disappears.

**Comment by jekkos** [comment] 2016-09-05 15:02
Just tried to type really slow and can't reproduce. The whitespace stays where it is.

**Comment by jekkos** [comment] 2016-09-05 15:03
Is this occuring on the latest version in master (I changed something in that js to fix the scan error)

**Comment by odiea** [comment] 2016-09-05 16:33
On current version this appears to be happening in Items search only. It looks like when the Items search results show it backspaces to the blank space in the Item name.

**Comment by petercstevenson** [comment] 2016-09-05 23:27
I tried redeploying and now I can't log in. It says "Incorrect username or password"

**Comment by odiea** [comment] 2016-09-05 23:30
Please read #832.

**Comment by petercstevenson** [comment] 2016-09-05 23:33
Thank you, odiea. How do I run that script via the Docker Cloud?

**Comment by odiea** [comment] 2016-09-05 23:34
Sorry but that is a @jekkos thing. I have no clue.

**Comment by petercstevenson** [comment] 2016-09-06 02:59
OK, I logged into my mysql database using MySQL Workbench. At first I tried executing the three lines of code from @daN4cat under --upgrade employees table. I still couldn't log in. Then I tried executing the tables.sql file. I still can't log in. I am very new to MySQL; what am I doing wrong?

**Comment by daN4cat** [comment] 2016-09-06 06:03
@jekkos is the default name and password still working after the switch to bcrypt?

**Comment by jekkos** [comment] 2016-09-06 06:25
Default login should work without a hitch.
 @petercstevenson you will need to run the script against the docker MySQL using docker cloud cli tool

**Comment by petercstevenson** [comment] 2016-09-07 03:14
@jekkos Would that be done through ssh into the Digital Ocean server?

**Comment by jekkos** [comment] 2016-09-07 07:06
You will need to use docker cli 
https://docs.docker.com/docker-cloud/installing-cli/

then you can list the containers in the cloud and open a shell on those.. I hope that the mysql image contains an mysql client as well

**Comment by jekkos** [comment] 2016-09-07 07:21
@petercstevenson You should just create a small .sql file with the code you want to execute. Then you need to copy that file to the mysql docker containe using cloud-cli (docker-cp command). In this case you will need to copy that sql file into the /docker-entrypoint-initdb.d/ directory of that container. You wi!ll need to commit the container and then it will be executed when the container restarts.

**Comment by freemail624** [comment] 2016-09-07 07:34
I found that the deleted spaces when searching happens in all modules except sales register and receiving ,also happen with  [bootstrap tables examples](http://bootstrap-table.wenzhixin.net.cn/examples/)

**Comment by jekkos** [comment] 2016-09-07 08:21
This one is fixed in composer branch now

**Comment by petercstevenson** [comment] 2016-09-07 14:10
@jekkos Sorry for being dense. I have docker and docker-cloud installed on my own computer. The container is hosted on a Digital Ocean server. Do I use the locally-installed docker software to access the cloud-based databased? I tried to log in using the tcp address that I found as the MYSQL_PORT variable as host (docker -H tcp://xx.x.x.x:3306 login) but I received a timeout error.

**Comment by daN4cat** [comment] 2016-09-07 16:13
Fix in master now. Please test.

**Comment by jekkos** [comment] 2016-09-07 16:30
@petercstevenson Getting a little off topic here but if you want to login into your container you have to do a `docker login` first. Next list running containers using `docker-cloud container ps`. Then you can drop a shell on your mysql container using `docker-cloud exec 'mysql-container-name'  /bin/bash'

Then you can run the mysql client that's available within the mysql container.

**Comment by petercstevenson** [comment] 2016-09-07 23:43
@jekkos Thank you for all your help. I think that I am almost there. Just to confirm - the script that I should be using is tables.sql?

**Comment by petercstevenson** [comment] 2016-09-08 01:42
@jekkos I tried following all of your instructions and it still doesn't work:
1. Logged into Digital Ocean console
2. Logged into Docker
3. wget https://raw.githubusercontent.com/jekkos/opensourcepos/master/database/tables.sql
4. docker cp tables.sql into /docker-entrypoint-initdb.d/ of the mysql container
5. docker commit container_name
6. Redeploy container using Docker web interface
7. I still can't log into OSPOS

What did I do wrong?

BTW, if it is better to correspond privately by email, you can reach me at petercstevenson at telus dot net

**Comment by daN4cat** [comment] 2016-09-08 07:13
@jekkos @petercstevenson can you please open a new issue, this is getting confusing now.

**Comment by daN4cat** [comment] 2016-09-08 07:14
With regards to space in search box, I noticed that as soon as you type a space it's removed and you need to type twice a space in order to get it accepted.

**Comment by jekkos** [comment] 2016-09-08 11:05
So you mean that it's nog solved yet?

**Comment by daN4cat** [comment] 2016-09-08 11:15
I can't retest now because I messed up with composer. But yesterday when I tried master version in Items I needed to type space twice or once and wait for the carriage to go back, and then typed again.

We should test more before closing it. I'm using Chrome by the way.

**Comment by petercstevenson** [comment] 2016-09-08 14:08
I was finally able to get ospos working again - thank you @jekkos for all your help. The space issue seems like it is working properly now. I will double-check the barcode scanner later this morning and let you know how that fares.

**Comment by daN4cat** [comment] 2016-09-08 15:08
Does it work fine even in Items search box? That's where I noticed an issue but it might have been my setup.

**Comment by daN4cat** [comment] 2016-09-08 17:17
Now that I got composer to work I re-tested and it's indeed fine.

I close as it's fixed.

**Closed by daN4cat** 2016-09-08 17:17 UTC
Labels: bug
