### ISSUE TITLE
Receivings price calculation bug with products with more than one receiving quantity

### ISSUE THREAD

**Issue by haisum** [jekkos/opensourcepos#78] opened 2015-05-14 19:14 UTC
![selection_103](https://cloud.githubusercontent.com/assets/911409/7639668/177518c4-fa97-11e4-9b17-e72f1068cf54.png)
![selection_104](https://cloud.githubusercontent.com/assets/911409/7639671/1d595a48-fa97-11e4-8116-6aa340d593f3.png)
![selection_105](https://cloud.githubusercontent.com/assets/911409/7639680/323afaa2-fa97-11e4-8bae-85eb488db62d.png)
![selection_106](https://cloud.githubusercontent.com/assets/911409/7639681/3247adf6-fa97-11e4-9521-803f45f79b9d.png)
![selection_107](https://cloud.githubusercontent.com/assets/911409/7639676/23962382-fa97-11e4-8c28-6fca4fe605de.png)
![selection_108](https://cloud.githubusercontent.com/assets/911409/7639682/324cd29a-fa97-11e4-9c89-965767e5ae18.png)

**Comment by odiea** [comment] 2015-05-14 21:13
Receiving Qty is a multiplier. Say you get a case of soda and it contains 12 cans, you would then use 12 in receiving and 12 in qty stocked. If you don't want to use that multiplier than just place 1 in receiving qty. and 12 in qty stock. When you go into receiving qty you would just receive 1 and that would update your stock qty by 12. Hope this give you a better understanding of receiving qty.

**Comment by haisum** [comment] 2015-05-15 06:03
@odiea I know what receiving quantity is and  I did use it often but something wrong is happening now look at screenshot of first receipt it shows total as 10 then why it changes to 100 in report?  Considering your example I buy a 10 can soda box for $10. system first makes correct invoice of $10 and later in reports changes that amount to $100 which is inconsistent

**Comment by odiea** [comment] 2015-05-15 11:09
The error is on the initial Receiving screen and receipt. 10 x 1x10 = 100. I am sure jekko will correct this problem.

**Comment by haisum** [comment] 2015-05-15 12:14
Pardon me, I would disagree to that @odiea . Receiving quantity is just a number to display, it shouldn't be used in multiplication for quantity or to calculate price. Therefore, bug is in detail report and receipt, not in initial screen and receiving confirmation screen. It used to work that way earlier. 2.3.2 has done something wrong. To test this behaviour I switched to older version of ospos (2.3.1) and tried same test case. It works as I expect it to. Here are screenshots.


![selection_109](https://cloud.githubusercontent.com/assets/911409/7652403/aba8e122-fb25-11e4-9e18-16b073af6c87.png)

![selection_110](https://cloud.githubusercontent.com/assets/911409/7652402/ab84195a-fb25-11e4-8389-6d2254ee22ce.png)

2.3.2 sows hundred in this report (that is wrong!). 2.3.1 used to show 10 which was correct behavior.

![selection_111](https://cloud.githubusercontent.com/assets/911409/7652401/ab822b7c-fb25-11e4-922c-99a84f1d147d.png)

![selection_112](https://cloud.githubusercontent.com/assets/911409/7652400/ab472eaa-fb25-11e4-91e7-c4c2f5da6fa2.png)

**Comment by haisum** [comment] 2015-05-15 12:38
digged in, found commit 9b98f15f693390205ee5c87794888f8d1d4d3bd1 to be the culprit. I think @jekkos  can elaborate on what exactly receiving quantity is. When I used older version of this software I assumed it worked correctly. Now after this change, everything is messed up in receivings calculations.

My usecase was: I buy 10 can soda box for $10. So I put cost price as $10 for "1 soda box" and put receiving quantity as 10. Note: I said for 1 soda box not 1 can. I always sell soda box, not individual cans. Receiving quantity indicated "x 10" in receipt to indicate to customer that Qty 1 of soda box represents "10 cans" and it  would cost them $10. So they always buy cans in multiples of 10. If I had purchased 10 soda boxes  in receiving it meant I invested 100$ in pos. Now after this change suddenly all such investment has been multiplied by 10 so my investment shows up to be $1000 and even though I just have 10 soda boxes (as entered earlier) system suddenly shows I have 100 soda boxes with $10 being price of each individual can rather than whole box of 10.

**Comment by odiea** [comment] 2015-05-15 13:00
I am basing my findings on Inventory increases. After you enter the item in Receiving go back to Items and see what changes are made to you current stock.

**Comment by haisum** [comment] 2015-05-15 13:20
In older version, it increased 1 if I purchase 1x10 item. In new version it increases 10 if I purchase 1x10 item.

**Comment by odiea** [comment] 2015-05-15 13:40
In the newer version you would enter your case of soda as 1. If you break up that case of soda and change the cost price and retail price  the receiving quantity would be 10.

**Comment by haisum** [comment] 2015-05-15 14:08
But why would that?? Imagine doing it for 1000 products? ? Why is jekkos
introducing such a big backward compatibility breaking change

**Comment by odiea** [comment] 2015-05-15 14:23
I know Jekko has spent countless hours of his time (free hours for us) to correct problems that were originally introduced in this program. I believe he has corrected  the program to show what or how it was originally intended to be used.

**Comment by jekkos** [comment] 2015-05-18 10:57
Receiving quantity was meant to multiply the received quantity with a configured number, while keeping the price for the received item constant. This means that when the receiving quantity is larger than 1, the final quantity and stock quantity are multiplied with the given factor. It was requested to ease stocktaking of bundled items.

I noticed some time ago that the quantity in receivings was not multiplied with the receiving_quantity and corrected that. As a side effect the price is multiplied as well in the reports now. This is indeed a regression introduced by that fix and should be corrected.

**Comment by jekkos** [comment] 2015-05-19 07:43
I think the only way to fix this properly is to add a receiving_quantity column to the receivings_items table. We have to know what the value was at that very moment the receiving was done, as the one in items can change any time, and if we jsut use that one than receiving history will become incorrect.

So instead of multiplying quantity it might be better to separate them. Still the stock will be incremented with the product of quantity * receiving_quantity just like before.

Let me know if this makes sense to you.

**Comment by haisum** [comment] 2015-05-19 07:58
Makes sense. 

This multiplication should also be reflected on receivings form and confirmation after receivings finish.

**Comment by jekkos** [comment] 2015-06-20 13:21
Fixed in 46b5c18aca269071673064616ab47d07b824e525

**Closed by jekkos** 2015-06-20 13:21 UTC
Labels: bug
