### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by ebenezery4** [jekkos/opensourcepos#1201] opened 2017-03-26 10:45 UTC
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information
I have tried to install this application several times but unable to do so unlike the older versions that has the index.php page just outside the main directory but this version i find it difficult to locate where to go and what to do after editing the config file and renaming the database.php file to reflect my configuration onmy local server i try to follow the installation instruction on the main page by locating the public folder but all i got is a black page and if i tried to use the bin directory and call the installation.php script from my browser i got an htaccess error. i need help on what to do

### Steps to reproduce the issue

**Comment by daN4cat** [comment] 2017-03-26 12:09
Yet you are not caring about reading what's asked in the template. I must be honest here, it's quite annoying and I close this one too.

**Comment by daN4cat** [comment] 2017-03-26 12:10
I'm doing that because I'm tired to ask people the same questions again and again.

**Closed by daN4cat** 2017-03-26 12:10 UTC

**Comment by daN4cat** [comment] 2017-03-26 17:41
Duplicate of #1200
