### ISSUE TITLE
Issue on sale and possibility to edit a sale

### ISSUE THREAD

**Issue by palomita15binaria** [jekkos/opensourcepos#605] opened 2016-05-29 14:34 UTC
2 issues:

1.- When I hit enter in the modal to edit a sale (The Invoice Number by example or the payment) shows the JSON
![ff0234923c430465066a8831f2eb9779](https://cloud.githubusercontent.com/assets/19568889/15634038/fe3084ca-25ba-11e6-9a59-acba82f31d31.png) 
(I edit the JSON message) Is there any way to hide this message?

2.- I need to edit a complete sale, editing all the items that I sell to a customer, not the payment or the date, complete POS if cab be possible and how? I saw other posts but I don't understand why is not implemented

**Comment by daN4cat** [comment] 2016-05-29 17:35
Version?

**Comment by palomita15binaria** [comment] 2016-05-29 19:03
Lastest, download 5 hours ago

**Comment by daN4cat** [comment] 2016-05-29 21:09
I just tested from Takings and Report Detailed Sales:
* edit one sale
* change the payment type
* unfocus the dropdown (otherwise enter reopens the dropdown)
* type enter
* modal closes
* data is save

everything works fine.

**Comment by daN4cat** [comment] 2016-05-29 21:11
Re point 2. it's no because fiscally is not correct. You can implement in your fork but what can be edited of the sales is editable.

**Comment by daN4cat** [comment] 2016-05-29 21:16
By the way, have you changed the code or is it the original one from master?

**Comment by jekkos** [comment] 2016-05-29 21:19
@palomita15binaria find my answer on editing sales in the other issue #542

**Comment by palomita15binaria** [comment] 2016-05-29 21:35
@daN4cat 1.- The enter issue is not a problem for me, but was a little annoying

2- but where is implemented? You mean the button to edit a sale in the summary sales, right?

-------

@jekkos Yeah, I checked out.
Maybe we can donate for a specific module because there is a small business that needs that implemented. 
Instead, there is any code that any user or any old version that has that?

**Comment by daN4cat** [comment] 2016-05-29 21:50
So there is no issue with that JSON message or no? Not sure I understand.

**Comment by palomita15binaria** [comment] 2016-05-30 08:23
@daN4cat It seems that is not solved, If I hit enter in the Edit Modal, shows the JSON message

**Comment by jekkos** [comment] 2016-05-30 10:51
Looks like the code was changed. Can't help you on this one. I see you're using an outdated json reply message structure, this won't work with bootstrap tables.

**Comment by jekkos** [comment] 2016-05-30 10:53
The id you return isn't correct so this and @daN4cat can't reproduce so I'm closing this issue.

**Closed** 2016-05-30 10:53 UTC
Labels: pending
