### ISSUE TITLE
blank page if no internet connection

### ISSUE THREAD

**Issue by chandrawg** [jekkos/opensourcepos#833] opened 2016-09-02 07:38 UTC
how to use point of sale 3.0 without internet connection ? after login only white screen. this is my error log and console.

![consolechrome](https://cloud.githubusercontent.com/assets/21230424/18196293/30a95996-7123-11e6-85a2-a94382a91a06.jpg)
![error log](https://cloud.githubusercontent.com/assets/21230424/18196294/30b90ec2-7123-11e6-800e-90b384870e8a.jpg)

**Comment by daN4cat** [comment] 2016-09-02 08:51
Something to look into.

**Comment by onyema3** [comment] 2016-09-02 09:51
Yeah, i just turned off my wifi and after login a blank page comes up

**Comment by jekkos** [comment] 2016-09-02 11:17
Think we need some kind of circuit breaker around the sockets addon

**Comment by daN4cat** [comment] 2016-09-02 12:50
@jekkos yep

**Comment by daN4cat** [comment] 2016-09-03 09:25
Fixed, @onyema3 please test with wifi switched off.

**Comment by onyema3** [comment] 2016-09-03 09:29
on it

**Comment by onyema3** [comment] 2016-09-03 09:31
Great.. fixed

**Comment by daN4cat** [comment] 2016-09-04 16:33
@onyema3 I fixed in a different way the issue. Would you mind to test again with the latest code in master? I cannot reproduce the issue you have and that's why I'm asking for you to test. Thanks.

**Comment by onyema3** [comment] 2016-09-04 17:59
i'm on it

**Comment by onyema3** [comment] 2016-09-04 18:02
Working without internet.

**Comment by daN4cat** [comment] 2016-09-04 20:39
Perfect! Thank you for the help with the testing.

**Closed** 2016-09-04 20:40 UTC
Labels: bug

**Comment by onyema3** [comment] 2016-09-04 20:50
You're always welcome!
