### ISSUE TITLE
Store config hanging

### ISSUE THREAD

**Issue by prineshan** [jekkos/opensourcepos#1112] opened 2017-02-02 08:07 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

Hi. When i click on store config , the page opens but stays black. Its been hanging for a while now.

**Comment by daN4cat** [comment] 2017-02-02 11:07
Read the FAQ?

**Comment by jekkos** [comment] 2017-02-03 09:53
Is this a duplicate of #1109? Has anyone been able to reproduce this? There was a fix by @RamkrishnaMondal not so long ago in this part of the code, maybe something went wrong.

**Comment by RamkrishnaMondal** [comment] 2017-02-03 10:05
@jekkos  can not reproduce the issue. I guess some php module missing in his setup, probably php-intl.

**Closed** 2017-02-05 21:38 UTC
Labels: pending
