### ISSUE TITLE
Composer version First look

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#807] opened 2016-08-13 14:03 UTC
Before submitting an issue please make sure you tick (add a x between the square brakets) and agree all the following check boxes:

- [ ] Checked the current issues database and no similar issue was already discussed
- [ ] Read the README, WHATS_NEW and UPGRADE
- [ ] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas
- [ ] Reporting an issue of an unmodified OSPOS installation
- [ ] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [ ] PHP version is at least 5.5 and not 7.x
- [ ] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [ ] Know the name and version of OS, Web server and MySQL and will add to my issue report

IMPORTANT: If you remove the template when submitting an issue your issue will be closed.

### Actual behaviour
I get this when I first login to a new install. When I go to the public folder so far all seems ok.
![2016-08-13 08_00_25-start](https://cloud.githubusercontent.com/assets/10962177/17643601/47e98074-612c-11e6-888f-3cf996476e73.png)

### Steps to reproduce the issue

**Comment by jekkos** [comment] 2016-08-14 10:01
Ok in this case the project root shouldn't be served by apache no more, but it might indeed be better to keep the .htaccess in case someone installs it wrongly.

I have rebased now with latest master and adapted the Dockerfile to include php socket extension, last thing to do is the language loading fix.

**Comment by jekkos** [comment] 2016-08-14 10:02
It's the public directory's content that should be mapped into public_html.. the other project files can stay underneath it (thus making them inaccessible by the browser)

**Comment by daN4cat** [comment] 2016-08-14 10:17
So in a subdomain case we need to point to public

**Comment by odiea** [comment] 2016-08-14 10:23
Now receiving this after public login.
![2016-08-14 04_22_01-photos](https://cloud.githubusercontent.com/assets/10962177/17648545/c94452c0-61d6-11e6-8b4c-99f649567c75.png)

**Comment by daN4cat** [comment] 2016-08-14 10:30
@odiea in the config `--enable-sockets`

**Comment by odiea** [comment] 2016-08-14 11:35
@daN4cat  Sorry I think you need to be  more specific where this --enable-sockets is. I don't see it anywhere in ospos.

**Comment by daN4cat** [comment] 2016-08-14 11:57
@odiea I meant in your PHP.

**Comment by odiea** [comment] 2016-08-14 12:07
Found it. More hoops to jump through. The average used would not like this OOBE.

**Comment by daN4cat** [comment] 2016-08-14 12:09
@odiea could you please write an hello email to francesco(dot)lodolo(dot)uk(at)gmail(dot)com? I'll explain over there why I'm asking this to you.

**Comment by odiea** [comment] 2016-08-14 12:38
Done.

**Comment by odiea** [comment] 2016-08-14 17:55
I just did a pull today and that finally showed in all versions.

**Comment by daN4cat** [comment] 2016-08-14 19:18
Sockets support will be required when integrating MailChimp and similar type functionalities in 3.1.

**Comment by odiea** [comment] 2016-08-14 19:20
Thanks for the heads up on this Sockets support.

**Comment by daN4cat** [comment] 2016-08-15 18:08
I close this as it's a duplicate of #624

**Closed by daN4cat** 2016-08-15 18:08 UTC
Labels: enhancement
