### ISSUE TITLE
Legacy jQuery cleanup

### ISSUE THREAD

**Issue by jekkos** [jekkos/opensourcepos#328] opened 2016-02-13 12:14 UTC
Just opening this issue as a followup for the jQuery 1.8+ migration. Following is still TBD

* Update or replace plugins that use legacy jQuery functionality. Currently these are jquery-autocomplete and thickbox (according to jquery-migrate)
* Remove jquery-migrate if the above here is done.

**Comment by jekkos** [comment] 2016-02-13 13:44
Items form is using bootstrap modal dialog now. Known issues

* Currently no waiting animation 
* Flakey behavior as sometimes you need to click twice to open it properly

WIl have a further look when I find the time (maybe this weekend)

**Comment by daN4cat** [comment] 2016-02-13 14:09
Maybe typeahead will do for autocomplete? Just a thought... I'll look into that later too. But once I finished with the datetimepicker.

**Comment by jekkos** [comment] 2016-02-14 09:10
The plugin for autocomplete that we're using now has been abandoned. Would be better to move to jquery-ui autocompletion, but that means that the syntax to use it will change as well.

**Comment by daN4cat** [comment] 2016-02-14 13:20
I think the bootstrap one I gave above works fine and supports ajax to fetch from remote.

**Comment by jekkos** [comment] 2016-02-15 10:03
For the modal dialogs it will be easier to use yet another js abstraction (BootstrapDialog) to avoid adding too much bootstrap specific boilerplate code to the project. WIll first try to finish the build improvement and see if I can add it using bower easily.

**Comment by jekkos** [comment] 2016-02-16 08:34
OK I've got the items set up with bootstrapdialog now. Not sure if I still want to fix the thickbox in my latest branch as we'll remove it anyway?

**Comment by jekkos** [comment] 2016-02-16 08:36
If you want then you can merge the feature/bower+grunt in bootstrapUI, but only if you can live with the fact that item forms might not be working at this moment. If not then I'll merge once I have them all replaced.

**Comment by daN4cat** [comment] 2016-02-16 09:28
@jekkos is bower+grunt breaking only forms or more than that? I would like to finish the datetimepicker part and the image loading before I can move to the next. If your branch doesn't break that it's fine but by memory I've read there was some issue with the tables.js?

**Comment by jekkos** [comment] 2016-02-16 09:42
datetimepicker seemed to be working, that's one quick test I did yesterday. Is it the image loading in upload you mean here?

btw if you want to install new libraries you can just go as follows in the branch

bower install <libraryname>
grunt

this should work fine if the library has a main property in it's bower.json file specified. This should be the case for most modern libraries these days.

**Comment by daN4cat** [comment] 2016-02-16 11:12
Ok, I'll have a look next day after I fixed the datetimepicker locale story.

With image upload I meant the company logo in config. It's working but not finished yet. It uses jasny widget. I want to finish off that as well.

**Comment by daN4cat** [comment] 2016-02-16 11:14
Btw thanks a lot for the work on all the automation. I know I'm not spending too much time on this stuff and focus on functionality mainly, but all that stuff is really important and highly valued it.

**Comment by jekkos** [comment] 2016-02-16 22:48
Items form is using bootstrap now. Also found an easy way to convert most thickbox forms to bootrstrap modal. Fun part is over now it's a matter of replacing all of the existing thickbox links.

**Comment by jekkos** [comment] 2016-02-18 08:02
Most forms should be working again. Might be time to merge branches?

**Comment by jekkos** [comment] 2016-02-18 09:32
Following needs finishing: 

* Add extra button in items form to keep the dialog open
* Finish employees form
* Migrate config tabs to bootstrap form

**Comment by daN4cat** [comment] 2016-02-18 22:32
After my commit I merged in my local your changes, there are just a couple of conflicts due to my changes in sales/register and receiving, but it's just a trivial rename of thickbox to modal-dlg.

However things are not fine. The layout is completely broken because all the css files disappeared.
How is supposed to work without bootstrap.css?

**Comment by daN4cat** [comment] 2016-02-18 22:33
Also grunt doesn't work and complains that it cannot find load-grunt-tasks

**Comment by jekkos** [comment] 2016-02-18 22:56
I merged my branch with your latest changes. It works on my machine!

I guess you will need to install the css files using bower.. just hit

    npm install bower -g && bower install

and all should be good.

**Comment by daN4cat** [comment] 2016-02-18 22:57
Not sure, I would expect to have a working setup in github.... why is not like that?

**Comment by daN4cat** [comment] 2016-02-18 22:58
I mean, why do I need to care about running bower?

**Comment by jekkos** [comment] 2016-02-19 07:34
Yes I will only commit minified CSS + js but for now only the latter is done.  The grunt task needs to be adapter to do the former as well. I forgot to do this part. You will need to run a npm install again for now to fetch the newly added grunt plugins.

**Comment by daN4cat** [comment] 2016-02-19 09:37
What's left of legacy js now? The autocomplete?

**Comment by jekkos** [comment] 2016-02-19 11:53
Yes autocomplete is kind of the last one that has warnings in jquery migrate. Would be nice to have a more bootstrap native style of suggestion.

**Comment by daN4cat** [comment] 2016-02-19 11:55
As said ealier I think this one: https://github.com/biggora/bootstrap-ajax-typeahead could do.

**Comment by jekkos** [comment] 2016-02-19 12:19
Ok when looking for packages I mostly grade them by number of stars and activity in the repo's. This might tell whether they will have updates in the future. IN that respect maybe this repo might be a better option

https://github.com/bassjobsen/Bootstrap-3-Typeahead

**Comment by daN4cat** [comment] 2016-02-19 12:57
Does it come with ajax support? I mean you would need to pull the data from the controller. Maybe it's all fine with your one, I didn't check.

**Comment by daN4cat** [comment] 2016-02-21 20:03
NOTE: above commits are related to #329 not #328.

**Comment by daN4cat** [comment] 2016-02-21 22:45
It looks like autocomplete uses .browser which is not available anymore.
However there is a potential workaround using https://github.com/gabceb/jquery-browser-plugin amd chaging browser.opera to be browser.webkit.

**Comment by daN4cat** [comment] 2016-02-22 10:56
I checked better and I found that autocomplete is part of jQueryUI: http://jqueryui.com/autocomplete/#remote 

What would be the problem to use that? We don't need to hack stuff with extra plug-ins.

**Comment by daN4cat** [comment] 2016-02-23 18:46
I gave a quick try to the /jquery-browser-plugin and it doesn't work properly because it doesn't detect Opera browser as opera but opr, and if you change in autocomplete opera to be opr it does affect the key functionality in chrome as well.

Maybe the best is to change the autocomplete js.
.size() can be replaced with length and that seems to work.
The issue is that the .browser has no direct replacements as it should be by browser feature not browser itself that things are detected.

Maybe switching to jQueryUI autocomplete could do, but having done a quick try doesn't work easily. Setting in source the url for the partial search flags an error. Not a trivial change

**Comment by jekkos** [comment] 2016-03-02 12:32
Wil try to integrate jquery-ui now. I've found a bootstrap theme for it. Think it's the most compatible and straightforward way to go.

http://www.learningjquery.com/2010/06/autocomplete-migration-guide

**Comment by daN4cat** [comment] 2016-03-02 15:22
I tried that move of the URL from function param to source: option, but it didn't go right in the sense that it couldn't address the method in the controller. An error was reported.
But it was a quick one and maybe I set it wrongly in the code or something else.

**Comment by daN4cat** [comment] 2016-03-02 15:23
OK now I read, probably the data format from the controller was not right and needs a change.

**Comment by jekkos** [comment] 2016-03-02 15:33
Yes indeed the formatting functions are obsolete now.. Good thing is that one can use key value pairs which required some ugly workarounds in the past.

**Comment by daN4cat** [comment] 2016-03-02 17:21
I guess controller methods should return JSON as standard format going forward.
I will try to understand this part beside your change on autocomplete.
I believe even bootstrap-table will require data in JSON format to function, if we switch to that.

**Comment by daN4cat** [comment] 2016-03-02 18:11
But maybe it's better to use this: http://plugins.upbootstrap.com/bootstrap-ajax-typeahead/#docs it comes with ajax customisable functionality.

**Comment by jekkos** [comment] 2016-03-02 22:26
I've been playing with the jquery ui autocomplete and it's quite customizable as well. I've almost got it working for item search (and tables in general)

main problem is that most of the plugins don't support post as default. I've found a nice workaround (better than the one I did for the old plugin) to do this anyway. Also we have the choice to make the controllers return json or just keep things the way they are. If we chose the latter then I'll add a custom function to the default autocomplete response handler in manage_tables.js. Advantage here is that most of the tables use the same piece of code so this part can be migrated quickly.

the jquery ui widget isn't really that fancier than the original one we have in the code. Only problem is that it's not maintained anymore and thus causing issues if we chose to go to jQuery 2.

**Comment by jekkos** [comment] 2016-03-02 22:29
Maybe I'd like to stick with jquery ui as it's the one that will probably have the bigger community in the future.

**Comment by daN4cat** [comment] 2016-03-03 06:31
Ok

**Comment by jekkos** [comment] 2016-03-04 11:16
Ok I've done some work on this change already. I've found quite some similar methods in the models that fetch data to show autocomplete suggestions. Most of the time there's one function fetching labels only, and one fetching both. Or one that returns different attributes instead of just one with the result's main attribute.

I propose to modify that model code a bit to take one extra parameter which is  a 'unique' flag. If this is set to true then additional attributes will show up in the suggestion box. This will lead to multiple search results and is only usable in the entity's table itself. In case eg giftcard dialog uses customer lookup, only unique results should be returned (as only one can be selected).

I'll also try to get rid of the id|name format in giftcard and sales forms by hiding the selected id in a hidden input field.

**Comment by daN4cat** [comment] 2016-03-04 12:38
Yes model methods are sometime duplicated. I reduced some around the searching a while back when I introduced the filters array concept to make the interface generic, and I know more refactoring was required but you need to check all the cases before changing something. Hence I agree with your proposal.

Yes the id|name story is annoying to be honest.

**Comment by jekkos** [comment] 2016-03-07 20:42
Ok I've removed the old autocomplete plugin. According to jquery migrate there's no real outstanding issues to upgrade further now.

I've cleaned up most of the search code and did some simplifications, removed duplicated code (also for the custom suggestions) and tried to make the whole more consistent across controllers / models. I did have some issues integrating the jquery ui css which is a themed one at this moment. For some reason I couldn't get it minified in the standard way so I solved it as it's done for bootstrap css now. Might want to improve that later in #329.

One thing that I need to review tomorrow is the nominatim address lookup code in person form, which isn't working anymore (code was a little too complex). All other search should be good. (some test feedback would be nice)

**Comment by daN4cat** [comment] 2016-03-07 20:52
Please run bower update because you seem to downgrade some js (e.g. Moments.js).

I'll test the changes and then upgrade the js.

**Comment by jekkos** [comment] 2016-03-07 20:54
Ok I didn't notice any change in bower.json after merging..

**Comment by daN4cat** [comment] 2016-03-07 20:56
it's a dependency from datarangepicker. Maybe you can give a try and update bower.json whilst I test your changes?

There is even a newer version of tablesorter.

How do you update and make the bower.json up to date?

**Comment by jekkos** [comment] 2016-03-07 20:58
yes I have run the update. Didn't know bower had this feature.

**Comment by jekkos** [comment] 2016-03-07 21:01
Looks like's there still an issue in item kits form and sales form.

**Comment by daN4cat** [comment] 2016-03-07 21:07
Testing... font of the drop down is too big :-)

**Comment by jekkos** [comment] 2016-03-07 21:08
Ye

**Comment by daN4cat** [comment] 2016-03-07 21:10
is there anything applying bootstrap styling to it off-the-shelf?

**Comment by daN4cat** [comment] 2016-03-07 21:13
there are still some jQuery migration issues. They are probably related to tables.
Fill in the table with data and narrow down with a search and you'll see the error.

**Comment by daN4cat** [comment] 2016-03-07 21:16
In Items: search by supplier disappeared

**Comment by daN4cat** [comment] 2016-03-07 21:20
Items: On partial search, type enter but the window doesn't autoclose although the search narrows down table list

**Comment by jekkos** [comment] 2016-03-07 21:32
No there might be a jquery ui bootstrap theme or something, but even then I think the base css is still required.

**Comment by jekkos** [comment] 2016-03-07 21:38
you mean search suggestions for items table? didn't know there were suggestions on supplier as well.

**Comment by daN4cat** [comment] 2016-03-07 21:38
Gift Card: (might be with any view) strange issue, 4 gift card the same but only 3 suggested:

![image](https://cloud.githubusercontent.com/assets/636048/13584111/d64318fa-e4ac-11e5-8502-05d934a3e7e6.png)

**Comment by daN4cat** [comment] 2016-03-07 21:40
Gift card: shortlist, select item or enter partial input and nothing happens

**Comment by daN4cat** [comment] 2016-03-07 21:42
@jekkos yes, in Items there were suggestion for suppliers and categories. Most likely you removed that code....

**Comment by jekkos** [comment] 2016-03-07 21:43
Item search .. I'll check in history. Tried to keep most of the functionality.

**Comment by jekkos** [comment] 2016-03-07 21:45
Pushed a comit that fixes item kits.. Giftcard suggestions seem fine, I can type partially and search, suggest box will be left open but that might be default jquery ui config.

**Comment by daN4cat** [comment] 2016-03-07 21:52
**Gift Card**: not sure what caused the issue but now it seems fine again. However I found another issue. Delete one gift card, type enter in the search box and it will re-appear.

**Comment by daN4cat** [comment] 2016-03-07 22:15
**Items Kits**: still doesn't work to me... nothing pops up as suggestion

**Comment by jekkos** [comment] 2016-03-07 22:23
Another push, should fix item suggestions for supplier + category

**Comment by jekkos** [comment] 2016-03-07 22:23
Item kits works perfectly. Only searches on item name if I'm not mistaken.

**Comment by daN4cat** [comment] 2016-03-07 22:29
I'll take the latest commit and test again, but it does not work here. I'm talking about Item Kits view, not Items Kits form!

Also it used to work with description and item kit name, also number if my memory is right.... but I would need to check against a pure 2.4.

**Comment by jekkos** [comment] 2016-03-07 22:33
OK you're right name suggestions have stopped showing up, will clean that bit later.

**Comment by daN4cat** [comment] 2016-03-07 22:33
**Items Kits form**:  search for an item via suggestion, move arrow down with keyboard and type enter -> the form closes with a submit instead of just selecting the items from the drop down.

**Comment by jekkos** [comment] 2016-03-07 22:34
Yes submit is due to the bootstrap dialog setting I guess..  prolly was an issue already before

**Comment by daN4cat** [comment] 2016-03-07 22:34
ok, enough for tonight.

**Comment by daN4cat** [comment] 2016-03-07 22:42
last extra one... issue with image in searching: `dist/images/ui-bg_glass_75_dadada_1x400.png `
It seems the wrong path to me.

**Comment by daN4cat** [comment] 2016-03-08 09:57
**Gift Cards**: deleted employees are suggested (really weird case I must say...)

**Comment by odiea** [comment] 2016-03-08 11:28
After latest pull I am getting strange results from Items search. I also downloaded the zip and I got the same results. Search suggestions dropdown box extends to the for right of the screen and hints? shows up on the lower left of the screen.
![2016-03-08 03_18_49-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13600459/2d67fc0c-e4e6-11e5-92bb-a0f57e61ee65.png)

**Comment by jekkos** [comment] 2016-03-08 12:24
Looks like jquery ui theme isn't loaded properly. Can you check if it's included in the source of this page? I had this issue as well and after adding the jquery ui theme this was resolved.

**Comment by jekkos** [comment] 2016-03-08 12:27
Regarding employee suggestions, probably another existing bug with the operator precedence in the search query. This bug was prolly there in older versions as well.

**Comment by odiea** [comment] 2016-03-08 12:40
And where in the source page would it be and what exactly am I looking for? There appears to be 5 sets of loaded items.

**Comment by daN4cat** [comment] 2016-03-08 12:53
@odiea are you using the code as it is or your template? You might something in the header if the latter.

@jekkos agreed, that issue was there before. But as in other parts, reshuffling things brings to surface stuff that wasn't in the end properly working. That's why I'm not that keen to keep going with 2.4 as it is and jumped to this version as we are fixing many issues together with the face lifting.

**Comment by odiea** [comment] 2016-03-08 12:56
I am using the code without a template to validate how it works.

**Comment by odiea** [comment] 2016-03-08 13:15
It does the same thing if I use the template or not. Also search suggestions showing bullet in front of it and appears to be in the background.

**Comment by jekkos** [comment] 2016-03-08 13:54
Yes that definitely the jquery.ui-theme.css file missing in your includes. Try ?debug=true in the end. Normally the css include should be there. I first did all of the code changes and then the css yesterday evening to make it finally look good.

Still weird that your browser doesn't load it by default.

**Comment by jekkos** [comment] 2016-03-08 14:03
@daN4cat Actually I'd rather take 2.4 as a replacement for 2.3.5 and keep it as last stable with some occasional cherry picked fixes from newest bootstrapUI. These are mostly issues in php code which still hasn't changed that much with respect to the ancestor version. 

From this point of view I think that it's not too hard to port some smaller fixes (not features) to that 'stable' version and release it a little sooner than our v3. Also I'd like to rename bootstrapUI to 3.0 once we merge 2.4 to master and move forward. I agree that it takes a little more effort to maintain two branches but I don't mind that extra effort.

I think the CI upgrade is something we might want to release separate from all the ui changes and can be considered stable in 2.4. 2.4 is justt 2.3.5 but with latest CI beneath. It shouldn't really be that different and more stable in the end (escpecially with the session support that was redone in CI3). What you think?

**Comment by daN4cat** [comment] 2016-03-08 14:10
Ok, so let's skip 2.3.5 and push 2.4 with CI3. BootstrapUI issues will be retagged as 3. I'll do it later. I just can't keep up with 3 branches.

**Comment by odiea** [comment] 2016-03-08 14:15
@jekkos  I guess when you get a minute go to git hub and see if you can see it in header.php. I can't see it there.

**Comment by jekkos** [comment] 2016-03-08 14:25
@odiea Ok then there's something wrong, I'll check later today.
@daN4cat Great I think it's the best solution. The cherry pick fix this morning couldn't even be fixed in 2.3.5 in the same way as it didn't have the group function in database. I agree that two branches is more than enough for now.

**Comment by daN4cat** [comment] 2016-03-08 14:47
So I mark what was 2.3.5 to be 2.4 and the bootstrap 2.4 to be 3.

**Comment by jekkos** [comment] 2016-03-08 19:49
Did some more cleanup of deprecated jQuery code. Also currently I can't reproduce the employee search bug. I have a deleted employee and it doesn't show up again after deleting

**Comment by daN4cat** [comment] 2016-03-08 19:52
maybe by mistake it was associated to some gift card... I would need to check the database

**Comment by odiea** [comment] 2016-03-08 20:31
@jekkos  Did you locate the missing css file location. All search modules are showing similar results

**Comment by jekkos** [comment] 2016-03-08 20:36
Pretty weird, in the current github version I see both jquery-ui .css files present. So one in the debug part and another one next to the minfied include.

**Comment by odiea** [comment] 2016-03-08 20:40
Lets make sure we are both on the same version. I am referring to feature/bootstrapUI.

**Comment by jekkos** [comment] 2016-03-08 20:42
Yes indeed. Ok the jquery ui css might be missing from dist folder. Will check now.

**Comment by jekkos** [comment] 2016-03-08 20:46
Ok think I got it, pushed the css file in dist/ folder now.

**Comment by odiea** [comment] 2016-03-08 20:55
That finished the appearance.
No search suggestion for Items in Item kits, Items Receivings or Sales register.

**Comment by odiea** [comment] 2016-03-08 21:09
Have things changed since I last tested. I use to be able to dbl click into Sales and all the items would show in a drop down box. Now I have to either enter the item number or some name to get an item to show.

**Comment by daN4cat** [comment] 2016-03-08 22:27
@jekkos there is still something old in the js: `JQMIGRATE: jQuery.fn.load() is deprecated -> manage_tables.js:472` You can see it if you edit an item.

Also when the item is saved there is another issue: `Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

@ais-one I suspect it's due to the saving of the image and ajax change.

**Comment by daN4cat** [comment] 2016-03-09 13:23
@jekkos if I run grunt `jQuery UI CSS Framework 1.9.2` and `jQuery UI Bootstrap 0.2.5` disappear from min.css

Have you added those components to bower.json?

**Comment by jekkos** [comment] 2016-03-09 16:20
@odiea Didn't test double click for sales or items. Will see if this is easy to fix
@daN4cat jquery ui css is in one of the main overrides of bower.json as it wasn't specified in the original attribute. It's copied separately to dist/ folder just like the minified bootstrap css.

**Comment by daN4cat** [comment] 2016-03-09 16:22
@jekkos I don't know, what I know is that if I run grunt I cannot get the same results as you and I risk to remove the styling of the dropdown from the search box.

**Comment by daN4cat** [comment] 2016-03-09 17:14
I committed what I can generate, as said the style of the search dropdown changes but I don't have means to generate the correct files. jquery-ui.css is in dist/ (also in my test website).

**Comment by jekkos** [comment] 2016-03-09 19:08
jquery-ui.css should be copied to dist using bowercopy plugin. At first there was a pattern in .gitignore which casued it to be ignored and thus not in the repo.

**Comment by jekkos** [comment] 2016-03-09 19:13
It's normal that the jquery-ui css in not in the minified version. I deliberately left it out as I faced the same issue we had with bootstrap to get it in the header properly. I also left out the jquery bootstrap theme as it didn't seem to do anything at first (including only that wasn't enough to properly style the dropdowns, it seemed to need at least a base jquery-ui css which isn't included by default with the plain jquery-ui dependency).

**Comment by jekkos** [comment] 2016-03-09 19:16
I have reviewed and fixed some issues for address completion in customer form e175a

Also @odiea I added a dlbclick handler in register to trigger search for the item and customer search field, but I think it's not yet working as you described it was before. This is probably because jquery ui does things a little different behind the scene. Once you have a text field and double click then results will show up just as if you would of have hit the return button.

**Comment by jekkos** [comment] 2016-03-09 19:17
@daN4cat probably one last thing to do for the autocompletes now is look for proper styling?

**Comment by odiea** [comment] 2016-03-09 19:26
I was just getting lazy. 2.4 still has that feature. It's just quicker for me when I am testing sales. No real issues.

**Comment by daN4cat** [comment] 2016-03-13 11:48
autocomplete styling will need an update, it's not in line with the rest.

**Comment by daN4cat** [comment] 2016-03-13 11:50
With regards to bootstrap-table, there might be a problem with Reports/detail sales. I'm not sure bootstrap-table supports nesting of second lines.

@jekkos you need to look into that before going for any change.

Maybe temporary you could fix the last js migration issue and remove the migration plugin?
So at least we have something up to date and still working fine.

**Comment by jekkos** [comment] 2016-03-13 18:25
I think theres an example in the demo's. Last issue is the deprecated live() call in dialogs will fix that. Ill try to finish thuis story tomorrow. Search will probably need rework anyway with bootstrap tables

I also tried to get the bootstrap theme to work but to no avail. Could be due to the image loading

**Comment by jekkos** [comment] 2016-03-14 08:49
I've added a workaround for the jquery load in the bootstrap dialog code to get rid of the deprecated warning. Quite annoying that there did not seem to be a direct best replacement for this specific jQuery.load() method usecase.

Also I did a bower update before running grunt hope all is well now. Haven't found any other warnings up til now so looks like migrate plugin can be removed from code.

**Comment by jekkos** [comment] 2016-03-14 08:51
Also I've noticed another 404 for jasny-bootstrap css map file. This error lead me to an interesting read on [source maps](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/).

**Comment by daN4cat** [comment] 2016-03-14 19:28
I still see jQuery.fn.load() issues in the concole. I'll try to understand where they are coming from.

**Comment by jekkos** [comment] 2016-03-14 22:11
My bad, I accidentally removed the s of the buttons property when I commit my change in the train to work this morning, should be good again now.

**Comment by jekkos** [comment] 2016-03-14 22:11
Just did a quick rewrite of that commit on this branch

**Comment by odiea** [comment] 2016-03-14 22:48
That appears to have fixed the no button in forms issue.

**Comment by jekkos** [comment] 2016-03-15 16:57
I have the impression that the default body font is not applied to text inside textarea. This part of the invoice looks completely different now.

**Comment by jekkos** [comment] 2016-03-15 17:41
I've found one more deprecated version. Did a thorough test of al modules and so far no more warnings spotted. Think it's about time to close this issue?

**Comment by daN4cat** [comment] 2016-03-15 19:19
Not quite completed yet.

Open in Customer the New Customer form, click submit without adding anything and:

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

I didn't test the other forms to see if it repeats.

Also, go to Items, open the filters option and click on Deleted checkbox or other checkboxes and:

`Uncaught TypeError: widget.flushCache is not a function`

**Comment by daN4cat** [comment] 2016-03-15 19:21
Once everything is sorted you should remove the JQMigrate and see if all is fine and close the issue after a bit of test.

**Comment by jekkos** [comment] 2016-03-16 08:00
> Uncaught TypeError: widget.flushCache is not a function

I've cleaned this warning in my latet commit. The xhr warning is not a jquery migration issue. Not exactly sure where it's coming from (I though jquery form at first) and not all browsers give this warning (currently only seen in FF).

Seems to be related to sync handling of XHR,

**Comment by daN4cat** [comment] 2016-03-16 08:01
I can see in Chrome, didn't test with Opera though.

**Comment by daN4cat** [comment] 2016-03-16 08:02
So do you want to remove JQmigrate now and go for some testing?

**Comment by daN4cat** [comment] 2016-03-20 22:29
I removed JQmigrate, run some tests and everything seems to work fine.
I also updated some plugin, so please run bower update.

I close this issue as I believe the jQuery upgrade is completed.
Well done @jekkos and thank you very much for the work put in this application.

P.S.: I'll open a new issue for the XHR warning.

**Closed by daN4cat** 2016-03-20 22:29 UTC
Labels: enhancement

**Comment by daN4cat** [comment] 2016-03-25 21:54
And removed the jqmigrate again.
