### ISSUE TITLE
Can u check the code for Sales. Nothing is showing Error 500

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1247] opened 2017-04-18 12:32 UTC
### IMPORTANT IMPORTANT IMPORTANT

Chose what you want to report: New Feature or Bug.
If you remove the template when submitting a Bug your issue will be closed as we cannot help without basic information.

### New Feature / Enhacement

For New Features or Enhacements please remove all the template text and clearly write your proposal.
It's important to state whether you expect the community to implement it or you will contribute the work.
Please bear in mind that we will implement new features only on the current code, there is no support for old versions.

### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Expected behaviour
Sales register should show. Just a blank page appears after selecting a customer

### Actual behaviour
This Issue now shows after selecting a customer in the Sales register.
This showed after latest merge so I downloaded the current zip and it is there also.
### Steps to reproduce the issue
Go to Register - select a customer-blank page appears

**Comment by odiea** [comment] 2017-04-18 12:48
Working fine after a restart

**Comment by daN4cat** [comment] 2017-04-18 12:52
Read the FAQ, wiki and past issues ☺☺☺

**Comment by odiea** [comment] 2017-04-18 13:12
Should there be brackets for this if statement On line 300 of register.
~~~
<?php if($this->config->item('customer_reward_enable') == TRUE): ?>
				<?php
				if(!empty($customer_rewards) &&  isset($customer_rewards))
				{
				?>
					<tr>
						<th style='width: 55%;'><?php echo $this->lang->line("rewards_package"); ?></th>
						<th style="width: 45%; text-align: right;"><?php echo $customer_rewards['package_name']; ?></th>
					</tr>
					<tr>
						<th style='width: 55%;'><?php echo $this->lang->line("customers_available_points"); ?></th>
						<th style="width: 45%; text-align: right;"><?php echo $customer_rewards['points']; ?></th>
					</tr>
				<?php
				}
				?>
~~~

**Comment by odiea** [comment] 2017-04-18 13:57
New database. Cannot add or update a customer.

**Comment by jekkos** [comment] 2017-04-18 14:09
Must be a  real problem then?

**Comment by daN4cat** [comment] 2017-04-21 05:45
Please check the latest master as the customer issue should be now fixed.

**Comment by odiea** [comment] 2017-04-21 10:15
Customer creation on a new db works fine but no fix for Selecting a customer Name in the Register.

**Comment by odiea** [comment] 2017-04-21 19:28
To show this issue. Go to Sales - Search and Select a Customer from the list and see what happens.

**Comment by SteveIreland** [comment] 2017-04-22 03:20
This appears to be caused by a call in sales.php to a function in Customer called Customer->get_stats() that doesn't exist.  I'm not sure what the purpose was so it's beyond my ability to repair.  It seems to have been introduced in Add only_check filter to takings (#1244)

**Comment by daN4cat** [comment] 2017-04-22 07:33
Ok I'll fix it

**Comment by daN4cat** [comment] 2017-04-22 08:35
Fixed

**Closed by daN4cat** 2017-04-22 08:35 UTC
Labels: bug

**Comment by odiea** [comment] 2017-04-22 09:18
That issue has been corrected but a new one has appeared.
![2017-04-22 03_12_26-photos](https://cloud.githubusercontent.com/assets/10962177/25303154/45a641fe-270a-11e7-89cc-039f63fe1f2c.png)

**Comment by daN4cat** [comment] 2017-04-22 09:28
Fixed
