### ISSUE TITLE
'Default Invoice Comments' & 'Invoice Email Template' can not be edited

### ISSUE THREAD

**Issue by RamkrishnaMondal** [jekkos/opensourcepos#1088] opened 2017-01-27 05:48 UTC
Once saved, these texts disappear from Store Config/Invoice tab.... hence can not be edited.  v3.0.2

![screenshot from 2017-01-27 11 23 30](https://cloud.githubusercontent.com/assets/14151032/22361779/13717cae-e483-11e6-8f58-7b21a82753a9.png)

**Comment by RamkrishnaMondal** [comment] 2017-01-27 07:58
Solved. This is due to 'config_use_invoice_template' checkbox is missing in 3.0.2 master.

**Comment by jekkos** [comment] 2017-01-27 18:43
Can you send a pull request for this fix?

**Comment by RamkrishnaMondal** [comment] 2017-01-27 19:30
will send a PR on Sunday.

**Comment by odiea** [comment] 2017-01-28 18:45
The issue is in views/configs/invoice_config.php
The form shows correctly after this is changed. 
Current settings.
~~~
<div class="form-group form-group-sm">	
				<?php echo form_label($this->lang->line('config_invoice_default_comments'), 'invoice_default_comments', array('class' => 'control-label col-xs-2')); ?>
				<div class='col-xs-5'>
					<?php echo form_textarea(array(
						'name' => 'invoice_default_comments',
						'id' => 'invoice_default_comments',
						'class' => 'form-control input-sm',
						'value ' => $this->config->item('invoice_default_comments')));?>
				</div>
			</div>

			<div class="form-group form-group-sm">	
				<?php echo form_label($this->lang->line('config_invoice_email_message'), 'invoice_email_message', array('class' => 'control-label col-xs-2')); ?>
				<div class='col-xs-5'>
					<?php echo form_textarea(array(
						'name' => 'invoice_email_message',
						'id' => 'invoice_email_message',
						'class' => 'form-control input-sm',
						'value ' => $this->config->item('invoice_email_message')));?>
				</div>
			</div>
~~~
After the space in value was removed it now shows correctly.
~~~
<div class="form-group form-group-sm">	
				<?php echo form_label($this->lang->line('config_invoice_default_comments'), 'invoice_default_comments', array('class' => 'control-label col-xs-2')); ?>
				<div class='col-xs-5'>
					<?php echo form_textarea(array(
						'name' => 'invoice_default_comments',
						'id' => 'invoice_default_comments',
						'class' => 'form-control input-sm',
						'value' => $this->config->item('invoice_default_comments')));?>
				</div>
			</div>

			<div class="form-group form-group-sm">	
				<?php echo form_label($this->lang->line('config_invoice_email_message'), 'invoice_email_message', array('class' => 'control-label col-xs-2')); ?>
				<div class='col-xs-5'>
					<?php echo form_textarea(array(
						'name' => 'invoice_email_message',
						'id' => 'invoice_email_message',
						'class' => 'form-control input-sm',
						'value' => $this->config->item('invoice_email_message')));?>
				</div>
			</div>
~~~
![2017-01-28 11_44_38-wedidit _ powered by ospos 3 0 2](https://cloud.githubusercontent.com/assets/10962177/22398943/35c08d64-e54f-11e6-8fa3-361156e93daf.png)

**Comment by RamkrishnaMondal** [comment] 2017-01-29 05:47
I will fix that along with showing 'Company Name' at the middle of the topbar, later today.

**Comment by RamkrishnaMondal** [comment] 2017-01-29 16:06
Updated....

**Comment by daN4cat** [comment] 2017-01-29 17:16
Fix committed to master.

**Closed** 2017-01-29 18:19 UTC
Labels: bug
