### ISSUE TITLE
Having problem with sales register

### ISSUE THREAD

**Issue by freemail624** [jekkos/opensourcepos#254] opened 2015-12-20 14:01 UTC
If the item name has this  '\' character the program make logout when i tray to add this item in the sales register

**Comment by daN4cat** [comment] 2015-12-29 16:00
I need to check this

**Comment by daN4cat** [comment] 2015-12-29 17:06
The issue is after you add an item containing '/' to sale and go for the payment that it logs out.

**Comment by daN4cat** [comment] 2015-12-29 17:24
The same issue affects even sale suspend

**Comment by daN4cat** [comment] 2015-12-29 20:50
This is not obvious at first glance. Could be something with the view part, because the Controller is not invoked in cases like "Takings" as it's just a page jump.

**Comment by odiea** [comment] 2015-12-29 20:54
I found that if you add the \ it kicks you out when you make a payment but / works ok?

**Comment by daN4cat** [comment] 2015-12-29 21:05
Yes with / works. With \ it doesn't work with any button you click. Try even "Takings / Overview" and you are logged out.

**Comment by odiea** [comment] 2015-12-29 21:09
Same issue in Receivings

**Comment by jekkos** [comment] 2015-12-30 06:38
Probably due to the fact that the item name is stored in the CI session. Think this will be some kind of escaping problem.

**Comment by jekkos** [comment] 2015-12-30 06:39
http://stackoverflow.com/questions/9439844/ci-cart-session-is-dropped-because-of-character

**Comment by jekkos** [comment] 2015-12-30 07:19
Should be fixed in the latest and greatest.

**Comment by daN4cat** [comment] 2015-12-30 13:28
Good, I checked views, js script and couldn't spot anything. Forgot about CI bits and bobs :-)

BTW, is there any risk to reach 5kB cookie limit now?
I never checked the cookie part in the code, so not sure what's really stored in it.

**Comment by daN4cat** [comment] 2015-12-30 14:22
I tested a bit and it seems now fine to me. So if the originator or somebody else could test we can then close this bug.

I found an unrelated bug tough and filed a bug report.

**Comment by jekkos** [comment] 2016-01-01 16:17
Well the 4kb limit was a common CI problem some time ago. Ospos suffered from spurious logout issues because of that. I tackled that by clearing out session state on regular intervals. This was more of a framework problem and I hope they finally fixed that in CI 3.

For some reason ci repeated the set-cookie header even when cookie data was already set,  there's a method in the base controller that checks and removes this duplicated data. But indeed if you configure CI to save session data in the cookie, then chances are that you'll run into trouble soon when doing big sale or receiving orders.

**Closed** 2016-01-02 11:36 UTC
Labels: bug
