### ISSUE TITLE
Calculation of sub total in sales

### ISSUE THREAD

**Issue by brentmeade** [jekkos/opensourcepos#767] opened 2016-07-28 23:29 UTC
I am using version 3.0.  When generating a sale in the sales window and i enter a product with a value of for example $2.75, in the check out window it is rounding off the value to $2.00.  Any item where there is a decimal value, it is rounding down the value.  If i have 10 items with varying quantities, the value is correct in the total on one side of the page but incorrect in the sub total field on the other side of the page.  
![screen shot 2016-07-28 at 7 28 06 pm](https://cloud.githubusercontent.com/assets/20567514/17232907/8a738cbc-54f9-11e6-840d-359f84c31de6.png)

Any one else have this problem as my sales revenue is being understated.

**Comment by odiea** [comment] 2016-07-28 23:41
You need to download the most current version. That issue has been fixed.

**Comment by brentmeade** [comment] 2016-07-28 23:57
Thanks for the response.  I am using Open Source Point Of Sale Version	3.0.0 - 1c4e5093bfbc.  I installed this late last week.  Is there a newer version, and if yes, what files do i change on my server and keep my data and configs?

**Comment by odiea** [comment] 2016-07-29 01:53
You appear to be using the most current version. The only thing I can suggest is download and create a program with a different name then attach your current database and see if the issue is gone. Other wise you will have to wait for the more experienced programmers to wake up and notice this issue.

**Comment by jekkos** [comment] 2016-07-29 06:52
Don't mind the version string it might be wrong at this point. Did you try a redownload of the latest today?

**Comment by jekkos** [comment] 2016-07-29 09:35
Actually the commit hash is just unique for the given file, in this case config.php. It is not equal to the revision info. This is something I need to look into.

**Comment by daN4cat** [comment] 2016-08-01 07:40
Is this an issue or no?

**Comment by jekkos** [comment] 2016-08-01 10:53
I can't reproduce it. It might have been a bug a few days ago.

**Comment by daN4cat** [comment] 2016-08-01 12:37
@brentmeade can you take the latest code from master and test again? If no issue or answer by end of the week we close this.

**Comment by brentmeade** [comment] 2016-08-01 22:50
The issue has been resolved. The sales lib code was not correct in the
latest download.  Thanks for the help.

On Aug 1, 2016 08:37, "FrancescoUK" <notifications@github.com> wrote:

@brentmeade <https://github.com/brentmeade> can you take the latest code
from master and test again? If no issue or answer by end of the week we
close this.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jekkos/opensourcepos/issues/767#issuecomment-236569017>,
or mute the thread

**Closed** 2016-08-02 05:33 UTC
Labels: pending
