### ISSUE TITLE
Discount Not Updating in Bill

### ISSUE THREAD

**Issue by paulirish01** [jekkos/opensourcepos#766] opened 2016-07-28 10:17 UTC
![discount](https://cloud.githubusercontent.com/assets/20701072/17209402/4d8936e4-54d6-11e6-9fcd-c7ca009716c8.PNG)

**Comment by jekkos** [comment] 2016-07-29 06:53
When did you download this exact version?

**Comment by jekkos** [comment] 2016-07-30 08:15
I've tested this and this seems not to be present in latest version

**Comment by chandrawg** [comment] 2016-08-25 07:59
same with me. discount is not updating. xampp v3.2.2, windows 7, ospos v3. please help. thanks

**Comment by daN4cat** [comment] 2016-08-25 10:24
@chandrawg can you please write down how to reproduce this, what you exactly see and what you would expect to see?

**Comment by chandrawg** [comment] 2016-08-25 10:48
same with above screen. and when i taking receipt for print, discount is not counting too. total must be price - discount.

**Comment by daN4cat** [comment] 2016-08-25 10:53
But if you don't give us all the precise information about how to reproduce it we are not able to understand what's wrong.

Please tell us what is your configuration in Store Config for language, currency and etc.
What item we need to create, prices and etc. might be relevant.

Because if I test everything is fine:

![image](https://cloud.githubusercontent.com/assets/636048/17966625/69005796-6aba-11e6-9a73-32e6d11efc00.png)

**Comment by daN4cat** [comment] 2016-08-25 10:56
I just tried even adding a big number with thousand separator and it seems fine to me:

![image](https://cloud.githubusercontent.com/assets/636048/17966734/00deb6ac-6abb-11e6-8c74-abf6ddeab629.png)

**Comment by chandrawg** [comment] 2016-08-25 11:05
![untitled-2](https://cloud.githubusercontent.com/assets/21230424/17966910/d2dc26e0-6af6-11e6-86e5-d854e9ff31b6.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/21230424/17966913/d4a4207c-6af6-11e6-86a7-f143ae98e84e.jpg)
language Indonesia and currency Rp.

**Comment by onyema3** [comment] 2016-08-25 11:15
@daN4cat I seem to be having the same issue
I'm using the current masters

**Comment by onyema3** [comment] 2016-08-25 11:18
My local settings

​

**Comment by onyema3** [comment] 2016-08-25 11:18
No modifications

**Comment by daN4cat** [comment] 2016-08-25 12:02
I'll refresh later my setup to make sure I have the same files from master and retest.

**Comment by odiea** [comment] 2016-08-25 12:14
I downloaded the master yesterday and I am having no issues .
![2016-08-25 06_13_30-wedidit _ powered by ospos 3 0 0](https://cloud.githubusercontent.com/assets/10962177/17968648/2edde1de-6a8b-11e6-8e5f-a68fed13328b.png)

**Comment by daN4cat** [comment] 2016-08-25 12:18
@chandrawg @onyema3 can you please tell us how you configure other type of discounts? Have you set something in the Store Config about that?

**Comment by chandrawg** [comment] 2016-08-25 12:21
@daN4cat i don't configure any discount in store config. only discount on sale.

**Comment by onyema3** [comment] 2016-08-25 12:23
See my settings

​

**Comment by daN4cat** [comment] 2016-08-25 12:31
@onyema3 there is nothing in your comments. Please post directly in GitHub because I'm afraid email doesn't work equally well.

**Comment by onyema3** [comment] 2016-08-25 12:36
ok

**Comment by daN4cat** [comment] 2016-08-25 13:33
@chandrawg @onyema3 and you sure you have the latest files in dist/ dir as well?

**Comment by onyema3** [comment] 2016-08-25 13:53
Infact i had to download the latest masters again to be sure and same error
not updating discount

**Comment by onyema3** [comment] 2016-08-25 14:00
![untitled](https://cloud.githubusercontent.com/assets/12876751/17971883/8def9dea-6ad4-11e6-86cd-b348b099fccb.jpg)

**Comment by chandrawg** [comment] 2016-08-25 14:08
@daN4cat yes i sure. i download yesterday for update from 2.4

**Comment by daN4cat** [comment] 2016-08-25 15:15
And both of you have run the database upgrade scripts, the latest. Correct?

**Comment by onyema3** [comment] 2016-08-25 15:17
Yes

**Comment by onyema3** [comment] 2016-08-25 15:18
Mine is a clean 3.0.0 install

**Comment by daN4cat** [comment] 2016-08-25 19:49
I tried the latest code from master with Chrome and Firefox and all works fine here.

Could you please open the console (Inspector or Firebug) and see if any error is displayed?
I really don't know what else it could be as I cannot really reproduce it.

**Comment by onyema3** [comment] 2016-08-25 20:21
Nothing is showing up here. I configured 5% tax and that also is not updating. I'm not sure if it has anything to do with this

**Comment by onyema3** [comment] 2016-08-25 20:23
![sales](https://cloud.githubusercontent.com/assets/12876751/17984666/25385d9c-6b0a-11e6-8cf5-fceb969af16b.png)

**Comment by odiea** [comment] 2016-08-25 22:21
@jekkos @daN4cat  Have either of you ran the register with ?debug=true. I don't know if this should be happening or not. This is the current master.
![2016-08-25 16_18_49-new notification](https://cloud.githubusercontent.com/assets/10962177/17987891/eefd6c56-6adf-11e6-8ab7-fdfa962d9fd1.png)

**Comment by odiea** [comment] 2016-08-25 22:32
All of the Bower components are flagged as not found?

**Comment by chandrawg** [comment] 2016-08-25 23:12
i tried with firefox, chrome, ie still not update discount. already run database upgrade script 2.4_to_3.0.sql.

**Comment by onyema3** [comment] 2016-08-27 05:57
Any update on this?

**Comment by daN4cat** [comment] 2016-08-27 08:04
I cannot reproduce. Please open Inspector in Chrome and see if there is any error. Use F12 to open the inspector window console. Also please check if error_log is reporting something. I hope pho math libraries are installed properly.

**Comment by chandrawg** [comment] 2016-08-27 08:30
no error_log in root directory and this is what i see in inspector
![untitled](https://cloud.githubusercontent.com/assets/21230424/18026263/6e1ce7e8-6c73-11e6-9f2d-4dee15257b3d.png)

**Comment by daN4cat** [comment] 2016-08-27 09:28
Console please.

**Comment by onyema3** [comment] 2016-08-27 10:36
[25-Aug-2016 21:02:39] PHP Fatal error:  Can't use method return value in write context in /Applications/MAMP/htdocs/opensourcepos-master/application/helpers/locale_helper.php on line 67
[25-Aug-2016 21:02:39] PHP Fatal error:  Call to undefined function error_get_last() in /Applications/MAMP/htdocs/opensourcepos-master/system/core/Common.php on line 688

**Comment by onyema3** [comment] 2016-08-27 10:36
Error Log

**Comment by chandrawg** [comment] 2016-08-27 12:01
no error in my console 
![untitled](https://cloud.githubusercontent.com/assets/21230424/18027219/f97f9cfa-6c90-11e6-8a64-846e892999c0.png)

**Comment by onyema3** [comment] 2016-08-27 13:54
@jekkos and @daN4cat I think the code need to be looked at again. I installed an older 3.0.0 with this hash tag 1c4e5093bfbc and this issue is not present.
There must be something causing it in the code
![new](https://cloud.githubusercontent.com/assets/12876751/18027851/2c14e4f2-6c66-11e6-9e73-edacfcc5811c.png)

**Comment by onyema3** [comment] 2016-08-27 14:30
5.5.26

**Comment by daN4cat** [comment] 2016-08-28 10:05
@onyema3 thank you for the tip, could you please tell me the date of that commit as I cannot trace back the hash to a commit in the last 2 months?

**Comment by onyema3** [comment] 2016-08-28 10:26
@daN4cat i'm not exactly sure of the date but i know it was before the licence tab in store config was added and when the giftcard issue was resolved (giftcard without a customer attached)

**Comment by daN4cat** [comment] 2016-08-28 10:53
OK, license change has nothing to do with this stuff. Other parts that changed, going by memory, are the locale support and even the decimal precision.

I really need to replicate your locale setting. Could you please tell me what you set in terms of currency, separator, locale and etc. All is set in your locale tab.
If you have a special currency symbol please copy and paste it here otherwise I won't know how to type it.

The first thing is to reproduce the test case.

**Comment by onyema3** [comment] 2016-08-28 10:59
Around June 22nd

**Comment by onyema3** [comment] 2016-08-28 11:00
My local settings

![untitled](https://cloud.githubusercontent.com/assets/12876751/18033263/087d8574-6d17-11e6-9d82-474ebec5d89f.jpg)

**Comment by onyema3** [comment] 2016-08-28 11:01
₦

**Comment by onyema3** [comment] 2016-08-28 11:02
Even with usd it doesn't work

**Comment by chandrawg** [comment] 2016-08-28 11:15
this is my locale setting 
![untitled-1](https://cloud.githubusercontent.com/assets/21230424/18033317/d1a883f4-6d53-11e6-83d1-bb56b14a20a2.jpg)

**Comment by daN4cat** [comment] 2016-08-28 11:22
OK, I see. You both have 0 for all the decimals. I bet it's that particular configuration.

**Comment by onyema3** [comment] 2016-08-28 11:24
what should be there??

**Comment by onyema3** [comment] 2016-08-28 11:26
@daN4cat True, i just changed the tax decimal to 2 and like a charm it worked

**Comment by onyema3** [comment] 2016-08-28 11:27
Is that normal?

**Comment by daN4cat** [comment] 2016-08-28 11:27
No, that's the issue. So we found the condition that breaks things.

**Comment by chandrawg** [comment] 2016-08-28 11:31
same with me. worked after changed decimal value.

**Comment by daN4cat** [comment] 2016-08-28 11:39
So it's the tax decimal the issue.

**Comment by onyema3** [comment] 2016-08-28 11:49
Exactly

**Comment by jekkos** [comment] 2016-09-01 16:17
Did a fix for this issue, can someone test?

**Comment by onyema3** [comment] 2016-09-01 16:33
Lemme check

**Comment by onyema3** [comment] 2016-09-01 16:37
Fixed!.. Thanks jekkos

**Closed** 2016-09-01 17:25 UTC
Labels: bug

**Comment by daN4cat** [comment] 2016-09-01 21:30
Confirmed that it's all fine now.
