### ISSUE TITLE
Barcode Problem 

### ISSUE THREAD

**Issue by mehedi01813** [jekkos/opensourcepos#704] opened 2016-06-28 09:59 UTC
Dear, When I scan any bar code from sales button It's automatically log out. I used your update version software. Please give me a solution.

**Comment by jekkos** [comment] 2016-06-28 10:07
Which version exactly? Don't really understand what you did. Barcode from sales button?

**Comment by mehedi01813** [comment] 2016-06-28 10:15
I generate barcodes and it's print now goes to sales option and when i scan my barcode software automatically log out. Software version 3.0.0

**Comment by jekkos** [comment] 2016-06-28 11:01
Can you post what text is exactly contained in the barcode? I rememnber that we had this problem before and that it was due to the cookie size being too large or having special characters encoded in the barcode.

**Comment by daN4cat** [comment] 2016-06-28 11:16
Have you upgraded the code from a previous version of the database?

If yes please make sure you run the 2.4 to 3.0 database upgrade script.

**Comment by odiea** [comment] 2016-06-28 12:42
Not knowing what his settings are I tried different names s
![2016-06-28 06_40_35-settings](https://cloud.githubusercontent.com/assets/10962177/16415634/73112bda-3cfb-11e6-808a-65ae6755cd20.png)
imilar or identical to his and I got no issues.

**Comment by mehedi01813** [comment] 2016-06-28 16:11
Here is my barcode setting <a href='https://postimg.org/image/7vnl43ew1/' target='_blank'><img src='https://s32.postimg.org/7vnl43ew1/barcode.jpg' border='0' alt='postimage'/></a>
Have you upgraded the code from a previous version of the database?
No i don't update the code i direct install version 3.o

**Comment by mehedi01813** [comment] 2016-06-28 16:18
I also face this problem :

A Database Error Occurred

Error Number: 1062

Duplicate entry '491618557752d28c04ec2becf6480b1d25d89ff6' for key 'PRIMARY'

INSERT INTO `ospos_sessions` (`id`, `ip_address`, `timestamp`, `data`) VALUES ('491618557752d28c04ec2becf6480b1d25d89ff6', '123.108.244.208', 1467130641, 'V836Hhy1R_AgfqxD_9EmgbkmUzurtQchGUcv90qg9n521Jhn-jeJLw4Vt_5UJyWLJFWuLYW5JPpk8xYBuBRDrw..')

Filename: libraries/Session/drivers/Session_database_driver.php

Line Number: 233

**Comment by mehedi01813** [comment] 2016-06-28 17:08
Any body solve me this problem via skype i will pay you.

**Comment by mehedi01813** [comment] 2016-06-28 18:19
My skype name : mehedi01813 yes remote desktop enable you also use tremviwer. add me skype please.

**Comment by odiea** [comment] 2016-06-28 20:03
If you have never used ospos before then you would use the database.sql. If you are upgrading from a different version then you should try 2.4_to_3.0.sql

**Comment by odiea** [comment] 2016-06-28 20:10
As a test you could create a new database call it ospos1 with the database.sql. Change your config database to ospos1 then try some entries and see if you get the same issues.

**Comment by mehedi01813** [comment] 2016-06-29 11:16
@odiea today i try 2.4 to 3.0 sql but same issues. Maybe my barcode scanner problem.  give me suggestion which barcode scanner are good for this script?

**Comment by odiea** [comment] 2016-06-29 11:20
Does it work when you manually enter the item id?

**Comment by jekkos** [comment] 2016-06-29 11:24
Yes it does.. it's his barcode scanner that appends some weird characters after the item id..

**Comment by jekkos** [comment] 2016-06-29 11:25
But I haven't been able to reproduce it locally either

**Comment by odiea** [comment] 2016-06-29 11:27
I would believe most of the modern usb scanners should work.

**Comment by daN4cat** [comment] 2016-06-29 11:56
Scanner issue has nothing to do with OSPOS <any version>.

I would close this issue if you don't mind.

**Closed** 2016-06-29 12:11 UTC
Labels: pending, question

**Comment by jekkos** [comment] 2016-06-29 12:53
Well yes it's kind of vague as the scanner outputted a tab character after the regular item id number.. this did cause the application to log out in one way or another. But I tried to reproduce this manually to no avail.

**Comment by jekkos** [comment] 2016-06-29 13:04
I guess a user can never input such a character  Nevertheless I think the session shouldn't drop even if a weird character is used.

**Comment by odiea** [comment] 2016-06-29 13:06
This appears to be the first occurrence of this happening. Should you dwell on this as a real issue?

**Comment by jekkos** [comment] 2016-06-29 13:41
Well as it isn't reproducable I would currently just ignore

**Comment by daN4cat** [comment] 2016-06-29 13:48
Can you please ask the guy to scan a barcode in a text pad and post the text file here?

**Comment by jekkos** [comment] 2016-06-29 13:50
Well yes that's what I asked him.. He scanned the text to notepad++ . I saw that after the regular item id there was an invisible tab character + cr nl

I have tried to copy paste this text and enter into the search field but everything keeps working as expected. It only occured when he scanned directly in the field.

**Comment by jekkos** [comment] 2016-06-29 13:51
So I guess best way for him is to read the scanner manual to get rid of this invisible character to make it work.

**Comment by daN4cat** [comment] 2016-06-29 14:03
Can you please share that text file?

We should even dump it in hex format as there could be some ESC code.
Maybe a filtering on the client side of non alphanumeric chars would help to increase the robustness anyway.

**Comment by odiea** [comment] 2016-06-29 14:12
I remember years back the old style serial or parallel scanners were quite tricky to setup.

**Comment by jekkos** [comment] 2016-06-29 21:10
@mehedi01813 Can you scan code in notepad++ , save and post this file here?

**Comment by mehedi01813** [comment] 2016-06-30 17:08
I scan code notepad and i give you link here : https://www.mediafire.com/?qjcmtwm483af1zp

**Comment by mehedi01813** [comment] 2016-06-30 17:09
I scan code notepad and i give you link here : https://www.mediafire.com/?qjcmtwm483af1zp

**Comment by mehedi01813** [comment] 2016-06-30 17:09
I scan code notepad and i give you link here : https://www.mediafire.com/?qjcmtwm483af1zp

**Comment by odiea** [comment] 2016-06-30 18:22
Re: programmatically remove carriage return from data input

Dec 22, 2006 02:13 PM|LINK

Thanks you both for your efforts, I have been able to reconfigure scanner to not have a terminator.

Certainly a lot easier than trying to trap cr/lf

**Comment by daN4cat** [comment] 2016-06-30 20:10
It's simply a tab but trying the code in OSPOS 3 it does nothing.
It's very strange....

**Comment by odiea** [comment] 2016-06-30 20:15
I know. I tried various versions I could find of CR/LF and it works just fine. I could even get the same Item to show on 2 rows. He must be using a really old scanner that has issues.

**Comment by odiea** [comment] 2016-06-30 21:23
@mehedi01813 How is the scanner installed. The serial port or the keyboard?

**Comment by mehedi01813** [comment] 2016-07-01 08:55
I can't install this device auto install and this scanner port usb.
