### ISSUE TITLE
Here is the completed Customer Sales Info. It contains the information for US could be adapted for other countries.

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#335] opened 2016-02-17 19:25 UTC
if(isset($customer))
	{
		$customer_id = $this->sale_lib->get_customer();
$cust_info = $this->Customer->get_info($customer_id);
$data['customer'] = $cust_info->first_name.' '.$cust_info->last_name;
$data['company'] = $cust_info->company_name;
$data['customer_address_1'] = $cust_info->address_1;
$data['customer_address_2'] = $cust_info->address_2;
$data['customer_location'] = $cust_info->city ;
$data['customer_state'] = $cust_info->state. ', ' .$cust_info->zip;
$data['account_number'] = $cust_info->account_number;
$data['phone_number'] = $cust_info->phone_number;
$data['email'] = $cust_info->email;
$data['comments'] = $cust_info->comments;
    echo $this->lang->line("sales_customer").' : <b>'.$customer. ' :  '.$this->lang->line("customers_account_number").' : '.$cust_info->account_number.'</b><br />';
    echo $this->lang->line("customers_company_name").' : '.$data['company'].'</b><br />';
	echo $this->lang->line('common_phone_number').' : <b>' .$data['phone_number']. '</b><br />'; 
	echo $this->lang->line("common_address_1").' : <b>'.$data['customer_address_1']. '</b><br />';
    echo $this->lang->line("common_address_2").' : <b>'.$data['customer_address_2']. '</b><br />';
	echo $this->lang->line("common_city").' : <b>'.$data['customer_location']. '</b><br />';
    echo $this->lang->line("common_state").' : <b>'.$data['customer_state']. '</b><br />';
   echo $this->lang->line('common_email').' : <b>'.$data['email']. '</b><br />'; 
   echo $this->lang->line("common_comments").' : <b>'.$data['comments']. '</b><br />';
   echo anchor("sales/remove_customer",'['.$this->lang->line('common_remove').' '.$this->lang->line('customers_customer').']');
	}
	else

**Comment by daN4cat** [comment] 2016-02-27 10:36
It sounds like after the current PR we might have another one here.

Just wait for the current integration to finish and then you can work on this one next.

**Comment by daN4cat** [comment] 2016-03-13 09:36
Duplicate of #369 now and targetting 3.0 (something already implemented).

**Closed by daN4cat** 2016-03-13 09:36 UTC
Labels: enhancement
