### ISSUE TITLE
Multi Store Support

### ISSUE THREAD

**Issue by innovaerp** [jekkos/opensourcepos#1113] opened 2017-02-02 18:23 UTC
Hi
Is ospos supports multi store / multi location sales can be monitored centrally from one deployment. so that senior management can get a clear cut view of the store wise sales, performance in real time. How it can be implemented and if it is there already, then how to get benefit of it

thanks
ishtiaque

**Comment by daN4cat** [comment] 2017-02-02 19:38
Duplicate of #150

**Closed by daN4cat** 2017-02-02 19:38 UTC
