### ISSUE TITLE
Problem show  store config

### ISSUE THREAD

**Issue by Jose191** [jekkos/opensourcepos#362] opened 2016-02-25 18:57 UTC
Hello , I have a problem when trying to click deserts sections:
Items , Receivings , Sales and Store config .

just says server error 500 .

within my localhost works perfectly but host it on my host does not work.

**Comment by daN4cat** [comment] 2016-02-26 06:56
Version please

**Comment by jekkos** [comment] 2016-02-26 10:24
Has anyone been able to reproduce this?

**Comment by odiea** [comment] 2016-02-26 10:26
No and not much info to support it.

**Comment by daN4cat** [comment] 2016-02-26 12:11
I feel most of the issues raise are config problems or people hacking with stuff and not telling us the full story.

Same story as the guy with AdminLTE changes and feedback_bar, no clue of what he was talking about and title "feedback_bar doesn't work".

**Comment by Jose191** [comment] 2016-02-26 14:10
I will not change code or assign its code and have no problem with paying what they ask for donation because it is their job and they have well deserved . but I would like to see it working online in my own private server. I vercion 2.3.4 .

I configured the database.php.tmpl and
database.php as stated in the installation manual , also DB_driver.php with my personal data.

thus configured operates without problem in my localhost WAMP , but ftp upload files to my server ixwebhosting not show me some sections

**Comment by ais-one** [comment] 2016-02-27 11:46
It may be some configuration on your hosting that is causing the problem. I tried mine on digitalocean, their ubuntu 14.04 LAMP install, seems ok.

**Comment by daN4cat** [comment] 2016-02-27 11:54
@Jose191 just to make sure we clear the doubt about a known issue, please take the last fix in master.
It's a change in database config from mysqli to mysql.
Make sure you have that and try again. I don't see why it should not work.

**Comment by Jose191** [comment] 2016-02-29 17:29
I provide the domain where the website 'm staying .

deleonasesores.com
user: admin
Password : Mkr45912

**Comment by daN4cat** [comment] 2016-02-29 17:50
Is database.pho with "mysql" and not "mysqli"?

**Comment by daN4cat** [comment] 2016-03-01 09:26
I can see the issue, but I will check it better later.

**Comment by Jose191** [comment] 2016-03-01 19:26
I have made changes but still not achieve it work.


WANT thing which need to remain at their orders .

Thanks for the support.

**Comment by daN4cat** [comment] 2016-03-01 20:08
you sure you don't have a permission issue with some of the directories? It might that.

Also please check your .htaccess for any strange thing. Or maybe just rename it temporary and give a try.

Also I hope you didn't change anything in the config files.

Please check the above and let me know. This looks a configuration issue with your server.

**Comment by odiea** [comment] 2016-03-01 20:20
I saw this error when opening a form if it helps anyone.
A PHP Error was encountered

Severity: Warning

Message: parse_url(/item_kits/view/-1/width:400/random:1456863481074): Unable to parse URL

Filename: core/URI.php

Line Number: 219

**Comment by daN4cat** [comment] 2016-03-01 20:46
error_log in ospos root should say something about what's going.

**Comment by daN4cat** [comment] 2016-03-04 07:10
Ok, this issues is reported in #375 too and gives finally a clue.

**Comment by jekkos** [comment] 2016-03-04 11:01
Also reference #39

**Comment by daN4cat** [comment] 2016-03-13 09:35
Duplicate of #374.

**Closed by daN4cat** 2016-03-13 09:35 UTC
Labels: bug
