### ISSUE TITLE
Item name / serial number not shown on invoice template

### ISSUE THREAD

**Issue by sgr1875** [jekkos/opensourcepos#405] opened 2016-03-18 13:32 UTC
When a product is enabled with serial number that product name is not visible in the invoice template. but receipt template show its correctly.
![invoice_template_issue](https://cloud.githubusercontent.com/assets/17928628/13879158/e60c24f6-ed3b-11e5-99c8-47614728c2cd.png)

**Comment by daN4cat** [comment] 2016-03-18 14:01
Version?

**Comment by sgr1875** [comment] 2016-03-18 14:04
2.3.4

**Comment by jekkos** [comment] 2016-03-18 15:47
Ok this must be an inconsistency between receipt and invoice behavior. WIll look into this later.

**Comment by jekkos** [comment] 2016-03-18 17:45
Ok did a quick fix for this one. Probably wasn't working due to missing parentheses in the echo statement.

**Comment by odiea** [comment] 2016-03-18 18:18
The Invoice still has issues. The item is an apple computer and it has a serial number.
![2016-03-18 12_00_20-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13887839/8f3cd568-ed03-11e5-84d7-e65f6f40dd03.png)

**Comment by odiea** [comment] 2016-03-18 19:02
Feature/bootstrap/UI has the same issue.

**Comment by ais-one** [comment] 2016-03-20 10:04
Tested on the BootstrapUI version, I can see the serial number on the invoice as well as product name.

**Comment by odiea** [comment] 2016-03-20 11:47
@ais-one Are you using the Invoice template?

**Comment by ais-one** [comment] 2016-03-20 12:28
I think it should be the invoice template.

I clicked on sales -> takings

the rows with invoice entries when I click to view, I see the product name and serial number (or ISBN or EAN). The serial number is the very first column correct?

**Comment by odiea** [comment] 2016-03-20 12:31
Do you have use invoice template checked in store config receipt. If you do please post a screen image because it appears by design it will either show item name properly or comment and serial number.

**Comment by ais-one** [comment] 2016-03-20 12:42
The serial number and product description are as per what I key in, maybe you give me your product & serial number and I try it out as well.

![invoice](https://cloud.githubusercontent.com/assets/4284574/13904448/1c6bc06e-eedc-11e5-9ae4-20d8e6556aec.png)

**Comment by ais-one** [comment] 2016-03-20 12:43
my store config has invoice template checked in the receipt tab

**Comment by odiea** [comment] 2016-03-20 13:56
What I am assuming is that the user is expecting the template version(1st image) to show the same info as the receipt (2nd image).
![2016-03-20 07_53_07-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13904770/015b32e8-ee71-11e5-81e9-216ed257b675.png)
![2016-03-20 07_53_44-ugly sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13904774/0642800e-ee71-11e5-92eb-541fae59182c.png)

**Comment by ais-one** [comment] 2016-03-20 14:20
I see. The receipt I can see item description but not serial number.

So maybe should add a serial number to the receipt view as well. perhaps in the same column as description first to see?

btw, the invoice looks confusing, shouldn't Item # be indicative of number of line items in the invoice instead? and serial number should have a seperate column or be in the Item Name column below item description, e.g.

iPad 64GB
ABC12345

**Comment by odiea** [comment] 2016-03-20 14:55
On the receipt the description is below the item name and the serial number is below the Qty

**Comment by daN4cat** [comment] 2016-03-20 22:44
Would be nice to get the last two 2.4 issues sorted and release 2.4 by Easter (an Easter Egg :-) )

**Comment by ais-one** [comment] 2016-03-21 00:24
looking at it now...

**Comment by ais-one** [comment] 2016-03-21 01:23
Hi,

FYI only.

I notice that if the description is created during edit (and not create), it will only appear in the ospos_sales_items for sales after the edit is done.

**Comment by ais-one** [comment] 2016-03-21 02:16
in sales_lib.php $serialnumber is null, so need to see what is wrong there

**Comment by daN4cat** [comment] 2016-03-21 09:20
I would need to check if there is an issue with this->post(..) result.

**Comment by sgr1875** [comment] 2016-03-21 09:39
It means it will be resolved in next issue or did i do something wrong?

**Comment by ais-one** [comment] 2016-03-21 09:43
I wanted to look at this today, but had to go to data center, some stupid emergency...

@sgr1875 I think you did not do anything wrong, the code needs to be looked at a bit more as serial number is null even though there is, we need to trace.

I would have dug further if not for the emergency...

**Comment by sgr1875** [comment] 2016-03-21 09:46
Its not urgent, just curious i am using ospos for almost 2 years and really happy. we just added mobile devices also to our products, this is when it showed up. i can run without the serial number option.

thanks a ton guys

**Comment by jekkos** [comment] 2016-03-22 07:11
@ais-one could you perhaps have a further look and propose something to improve this? thanks.

**Comment by ais-one** [comment] 2016-03-22 14:18
I start looking into this again, looks like a but though as the controller did not get the serial number

**Comment by jekkos** [comment] 2016-03-23 15:45
Layout is a bit different for both but baiscally same information is shown (but in different places). So in this case one would like to see the item name + description?

For me it's desirable to replace the name with a description in some cases. Maybe we should add this as an option to the config.

**Comment by jekkos** [comment] 2016-03-23 15:46
For example when selling a generic item from stock, custom description might want to be displayed without showing the original name.

**Comment by jekkos** [comment] 2016-03-23 17:46
Fields now show properly on invoice. serial number show beneath qty and description beneath item name. Both fields are editable.

Can someone verify so we can close?

**Comment by ais-one** [comment] 2016-03-23 18:00
I do not see the serial number. Just downloaded master

**Comment by ais-one** [comment] 2016-03-23 18:03
the item # column looks like the serial number...

**Comment by ais-one** [comment] 2016-03-23 18:08
ospos_items.item_number (EAN / ISBN, etc.) is populating ospos_sales_items.serialnumber correct?

if it is wrong then my two comments above are wrong and I do not know where is the source input for ospos_sales_items.serialnumber

**Comment by odiea** [comment] 2016-03-23 19:16
Winter weather I keep losing power. I will search for other js errors.
So here is how it looks now.1st Invoice template. 2nd Receipt.
![2016-03-23 13_12_39-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13997735/1dcec7fc-f0f9-11e5-8bf9-88dde3640a92.png)
![2016-03-23 13_13_09-christmas sweater store -- powered by os point of sale](https://cloud.githubusercontent.com/assets/10962177/13997739/265b36ee-f0f9-11e5-9592-ee47312d8063.png)

**Comment by odiea** [comment] 2016-03-23 20:43
The serial number is under qty and the desc is under item name

**Comment by ais-one** [comment] 2016-03-23 23:59
I changed item to one that requires serial number.

During sale I key in the serial number.

If I click add payment, the serial number disappears and I need to type it in again.

When I complete the sale, serial number does not show and it does not appear in the oppos_sales_items table

**Comment by jekkos** [comment] 2016-03-24 08:15
Guess you forgot to click edit item after entering the serial number. Quite annoying I know.

**Comment by ais-one** [comment] 2016-03-24 09:09
I see the serial number now. Would it be better to rename Edit Item as Update Item?

Receipt is ok.

But invoice looks wierd, should be...
Line 1: Item Name
Line 2: Description

But I Get...
Line 1: Description
Line 2: Description

**Comment by daN4cat** [comment] 2016-03-24 09:15
Yes, makes sense to call it Update Item or simply Update on the button.

**Comment by daN4cat** [comment] 2016-03-24 11:56
I will fix in in bootstrap side at least next days.

**Comment by daN4cat** [comment] 2016-03-25 23:01
Changed to be Update in bootstrap UI branch

**Comment by daN4cat** [comment] 2016-03-26 15:28
Is this OK in 2.4 beside the edit/update? It's just a matter of taste, I wouldn't change in 2.4 because it has always been "edit".
With 3.0 the UI is different and people will have a different impact/expectation. Moreover Glyphicons are in 3.0/bootstrap only.

If no update in a couple of days I'll close this.

**Comment by ais-one** [comment] 2016-03-26 15:41
"Update" made more sense, from me who has not read much user documentation, especially in the case of entering serial number

**Comment by odiea** [comment] 2016-03-26 17:03
There really isn't a lot of user documentation available on OSPOS.

**Comment by daN4cat** [comment] 2016-03-26 17:57
Yes, see my change in boostrap UI. But in 2.4 I would leave the same old design. But if somebody is in love with update instead of edit, it's just a matter of translating it differently.
To be honest I just want to see this 2.4 being release and we focus on 3. Personally I want to jump to 3 and we are close to an first cut.

**Closed** 2016-03-26 22:59 UTC
Labels: bug
