### ISSUE TITLE
Can I set store location  in 2.3.4?

### ISSUE THREAD

**Issue by ramiznazir** [jekkos/opensourcepos#358] opened 2016-02-25 04:37 UTC
Can I set store location and only that specific store items,sale should be shown there.

**Comment by odiea** [comment] 2016-02-25 12:04
Currently a OSPOS does not support multi-store locations. I think the only way around this is if you setup 2 stock locations and  give employees at store 1 location 1 and employees at store 2 store 2 location 2  but all the Sales will still show at both locations..

**Comment by jekkos** [comment] 2016-02-26 10:18
Will close this one for now, you might want to check out #150  as well.

**Comment by daN4cat** [comment] 2016-02-26 12:13
No the issue is there. I just checked with my 2.3.4.

Similar to the one I got rid when I removed the autobackup on logout.

Maybe this is a regression, needs investigation.

**Comment by odiea** [comment] 2016-02-26 12:18
What issue are you referring to?

**Comment by daN4cat** [comment] 2016-02-26 12:28
Go in config and push the backup button at the end of the first tab.
I get an error.

**Comment by odiea** [comment] 2016-02-26 12:38
Yes I see that issue. The version I have online doesn't have that issue.

**Closed** 2016-02-26 13:05 UTC
Labels: question

**Comment by arkgnan** [comment] 2016-03-15 08:36
if the stock location use as branch or other store location, What changed?
