### ISSUE TITLE
Return sale item suggestion does not work correctly

### ISSUE THREAD

**Issue by donangil** [jekkos/opensourcepos#606] opened 2016-05-29 17:23 UTC
When i type in the barcode of an item there is no problem. but when i start to type in barcode and select from dropdown, it brings a different item.

**Comment by daN4cat** [comment] 2016-05-29 17:33
Version?

**Comment by donangil** [comment] 2016-05-29 17:39
Version 3.0.0

**Comment by RamkrishnaMondal** [comment] 2016-05-29 18:05
Yea, sales return has an issue of  item selection, i can reproduce.

**Comment by odiea** [comment] 2016-05-29 19:05
Yes it does. I think when I first started testing I suggested that Item should only be returned with a proper receipt. Too many people were pulling tags off of clothing then trying to return the item.

**Comment by daN4cat** [comment] 2016-05-29 21:04
I cannot reproduce. I just tested with the latest master and I just type the first 4 numbers of a 13 long UPC code, then from a list of 15 I select one and it's the correct item either in sale or return.

**Comment by jzonetan** [comment] 2016-05-30 00:45
NEver had issue on return function too. it goes smooth though

**Comment by odiea** [comment] 2016-05-30 22:09
The problem shows in Return when you enter an item name or just a letter then select it from the list. When you enter an item name or letter in sales a dropdown list displays then you can select the item and it shows that item correctly.

**Comment by daN4cat** [comment] 2016-05-31 05:36
Ok, the issue mentioned barcode. I'll check this again.

**Comment by jekkos** [comment] 2016-06-02 06:54
Shouldn't we just disable random item return and stick to returning only receipt numbers or invoices?

**Comment by daN4cat** [comment] 2016-06-02 09:55
I would say no, sometimes you just get one out of 20 returned and you don't have the time to return all and delete 19 items. So let's not remove what is there already.

**Comment by jekkos** [comment] 2016-06-02 10:18
OK I just didn't know there was a usecase for it.

**Comment by daN4cat** [comment] 2016-06-02 16:55
@oidea I tested the return case typing only one letter and selecting an item and what is picked up is what I selected.

I'm afraid I still cannot reproduce this issue.

**Comment by odiea** [comment] 2016-06-02 20:38
@daN4cat Just so you don't think I am crazy. Please try  http://ospos.25u.com:8080 to see the issue. I also have the performa setup after You insert a customer name. After viewing the performa you can go back to Register and Suspend or Cancel.

**Comment by odiea** [comment] 2016-06-02 20:47
In Return if I enter 1 as an Item number it returns POS 58 in Sales it works fine.

**Comment by daN4cat** [comment] 2016-06-03 17:06
OK, now I can see the problem. Just typing 1 in return mode suggests a POS xx, just typing 2 suggests another POS yy.

**Comment by daN4cat** [comment] 2016-06-03 17:32
That happens because it interprets that number as the invoice one.
It's in `Sale_lib`, see `is_valid_receipt`.

**Comment by odiea** [comment] 2016-06-03 17:41
Do you think there will be a fix for this issue?

**Comment by daN4cat** [comment] 2016-06-03 17:42
It's not an issue, it's a feature. @jekkos what's your view?

**Comment by odiea** [comment] 2016-06-03 17:43
I was just curious why some have the issue and others do not.

**Comment by daN4cat** [comment] 2016-06-03 17:44
It depends on the invoice number, it suggest the POS that have an invoice with that number. Please countercheck.

**Comment by daN4cat** [comment] 2016-06-03 17:54
I'm going to disable it if the invoice feature is disabled from the Store Config, but beside that it stays unless @jekkos wants to remove it.
What I would suggest is to use a smart way of numbering the invoices and avoid simple number like those.

**Comment by daN4cat** [comment] 2016-06-03 17:56
BTW, it would be good to have a bit of a different logic and show invoice and the rest not only the invoice.

**Comment by odiea** [comment] 2016-06-03 18:06
Yes pos 58 has invoice#1. But why will the item name search not pull up the correct Item? Same issue maybe?

**Comment by daN4cat** [comment] 2016-06-03 18:07
Sorry, I don't get. What is the other problem?

**Comment by odiea** [comment] 2016-06-03 18:16
The problem shows in Return when you enter an item name or just a letter a drop down list displays then select it from the list, the item selected by name does not show correctly. When you enter an item name or letter in sales a drop down list displays then you can select the item and it shows that item correctly.

**Comment by daN4cat** [comment] 2016-06-03 18:19
I tested that case it works fine with me. I said that already at the beginning.

**Comment by odiea** [comment] 2016-06-03 18:20
Have you tried it on my server? It is different than yours.

**Comment by daN4cat** [comment] 2016-06-03 18:29
You sure you don't have a category, description or supplier name that conflicts?
That search goes through all of those together with item name & number.

BTW, I fixed the search to do not only show the invoice receipt number if found but other suggestions too.

**Comment by daN4cat** [comment] 2016-06-03 18:30
I consider this closed because there seems to be no other unusual case.

**Closed** 2016-06-03 18:33 UTC
Labels: bug

**Comment by odiea** [comment] 2016-06-04 17:52
When I comment out the following in Sale_lib it pulls up the receipt and item by number with no issues.

/*else if($this->CI->config->item('invoice_enable') == TRUE)
		{
			$sale_info = $this->CI->Sale->get_sale_by_invoice_number($receipt_sale_id);
			if($sale_info->num_rows() > 0)
			{
				$receipt_sale_id = 'POS ' . $sale_info->row()->sale_id;

				return TRUE;
			}
		}*/

**Comment by daN4cat** [comment] 2016-06-04 21:09
What that code does is just to lookup invoices based on the typed input.

**Comment by odiea** [comment] 2016-06-04 22:02
Removing that code cleared up all my issues.

**Comment by jekkos** [comment] 2016-06-05 07:50
As @daN4cat suggested it's indeed a feature and not a bug. If you're using just numbers for invoices then the behavior might look a little weird. Perhaps add a config flag for this functionality?

**Comment by odiea** [comment] 2016-06-05 10:30
Yes I have been testing with only numbers for the test Invoices. Maybe it should be searched similar to the 'pos' using 'inv' instead. With little or no help files I would imagine that OOBE of OSPOS is not too great.

**Comment by odiea** [comment] 2016-06-05 11:58
You might also consider if Invoicing is enabled then any delete button should be disabled. Invoicing is a nice feature for many companies and I believe these issues should be ironed out.
