### ISSUE TITLE
Add unit feature 

### ISSUE THREAD

**Issue by salikur** [jekkos/opensourcepos#140] opened 2015-09-10 13:36 UTC
Can add unit feature in item? Like Kg (kilograms),pcs,bottle etc. User can set unit name for item. Thanks

**Comment by jekkos** [comment] 2015-09-10 15:32
Yes there's a private branch that will allow you to do that.

**Comment by asadjaved63** [comment] 2015-09-10 15:34
It's paid version? Which allows us do that?

**Comment by jekkos** [comment] 2015-09-10 19:05
Currently unreleased, will need some polishing probably for a fee in return. It has integration with serial for using scale devices. I could setup a demo for you so you can see the added features.

**Comment by daN4cat** [comment] 2016-04-03 21:40
This is probably a duplicate of #68 or at least they cover the same.

**Comment by daN4cat** [comment] 2017-03-18 10:46
Close to keep just #68 open as this is just a use case.

**Closed by daN4cat** 2017-03-18 10:46 UTC
Labels: question
