### ISSUE TITLE
cannot add customer because of new column sales_tax_code

### ISSUE THREAD

**Issue by Aravindhanari** [jekkos/opensourcepos#1250] opened 2017-04-19 12:45 UTC
### Issue / Question / Bug

Before submitting an issue please make sure you remove the first section of the template and you tick (add a x between the square brakets) and agree with all the following check boxes:

- [x] Checked the current issues database and no similar issue was already discussed
- [x] Read the README, WHATS_NEW and UPGRADE
- [x] Read the FAQ (https://github.com/jekkos/opensourcepos#faq) for any known install and/or upgrade gotchas (in specific PHP has php5-gd, php-intl and sockets installed)
- [x] Reporting an issue of an unmodified OSPOS installation
- [x] PHP version is at least 5.5 and not 7.x
- [x] MySQL version is 5.5 or 5.6 and not 5.7
- [x] Ran any database upgrade scripts (e.g. database/2.4_to_3.0.sql)
- [x] Know the version of OSPOS and git commit hash (check the footer of your OSPOS) and will add to my issue report
- [x] Know the name and version of OS, Web server and MySQL and will add to my issue report

### Installation information

version information:
Open Source Point Of Sale Version 3.1.0 - 4f5ad57 
php: 5.6.25
mysql: 5.6
database used: database.sql

### Expected behaviour
Adding an new customer

### Actual behaviour
customer cannot added, throwing error log
ERROR - 2017-04-19 07:06:55 --> Query error: Column 'sales_tax_code' cannot be null - Invalid query: INSERT INTO `ospos_customers` (`account_number`, `company_name`, `discount_percent`, `package_id`, `taxable`, `sales_tax_code`, `person_id`) VALUES (NULL, NULL, 0, NULL, 1, NULL, 43)

### Steps to reproduce the issue
just try to add the new customer.

**Comment by RamkrishnaMondal** [comment] 2017-04-19 15:32
Duplicate of #1247 ???

**Comment by daN4cat** [comment] 2017-04-19 16:14
Yes but this tells us what's exactly wrong.

@SteveIreland it might be due to your addition.

**Comment by victorlclopes** [comment] 2017-04-19 18:39
Hello!

This is exactly what is happening with me. I was about to raise another issue when I found this new one. And also the #1247 describes the problem, I can't add a new customer and if I import some (using a .csv) I can't select them during sales operations.

I've been trying to install OSPOS since last week, this is such a nice software and I'm really looking forward to seeing it working here in my environment!
Tried installing it on an Ubuntu 16.04 system, using nginx/mariadb/php7.0, tried a regular LAMP stack and now I have a Debian Jessie with php5 and the problem is always the same. Please advise!

I have all required PHP extensions, I can add suppliers, items, employees, and all goes smoothly. Just can't add customers. Is there a workaround for now? Is there something I can do to help?

Thank you so much,

Victor.

![ospos_add_customer_error](https://cloud.githubusercontent.com/assets/27737616/25196093/f3d200a2-2515-11e7-819d-138a659e8359.png)

[current system info.txt](https://github.com/jekkos/opensourcepos/files/937229/current.system.info.txt)

**Comment by odiea** [comment] 2017-04-19 19:00
@daN4cat  I downloaded steves master this morning and it is giving me no issues.but it is 20 commits behind.
![2017-04-19 12_55_40-ruledomain_opensourcepos_ ruledomain_opensourcepos is a fork from jekkos_opensou](https://cloud.githubusercontent.com/assets/10962177/25197129/2f4431b6-2500-11e7-8110-c542b5c718a3.png)

**Comment by odiea** [comment] 2017-04-19 19:41
Ok His master is also giving issues with adding  a new customer in a new database.

**Comment by daN4cat** [comment] 2017-04-19 19:47
@victorlclopes current master is not a final 3.1.0 as it's work in progress. So we are working on this and with the help of people doing the test we spot the issue to fix. When all works fine then it's time to release 3.1.0 😊

**Comment by odiea** [comment] 2017-04-19 20:26
Currently you cannot add a new customer until Customer Sales Tax Support is enabled. Then after you successfully add a New Customer it will not work in the Register.

**Comment by victorlclopes** [comment] 2017-04-19 20:27
I see, thanks @daN4cat ! I just downloaded an earlier version from the tree, in which this customer error is not up yet, and it worked OK, as you suggested. 
I think this is a great project, I'll try to find a working version to evaluate here. My needs are simple, just need to control stock/supply flow. We're a small business trying to find some tools to help out, but If we move this to production, I'll make sure to convince my boss to pay you guys at least a couple of beers :)

Thank you so much,

Victor.

**Comment by daN4cat** [comment] 2017-04-20 00:38
@victorlclopes download version 3.0.2 for your demo. Hopefully we get 3.1.0 issue sorted soon.

**Comment by SteveIreland** [comment] 2017-04-20 15:49
I'll take another look at that issue.  I know it was working at one (or two) points in the development cycle.

**Comment by daN4cat** [comment] 2017-04-21 05:44
Please check the latest master as the customer issue should be now fixed. Thanks @SteveIreland

**Comment by daN4cat** [comment] 2017-04-22 11:22
I believe this is fixed, therefore I close.

**Closed by daN4cat** 2017-04-22 11:22 UTC
Labels: bug
