### ISSUE TITLE
Docker update

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#284] opened 2016-01-13 14:49 UTC
So I installed docker on the ubuntu server and here is what I get when I run the command.
> docker build -t me/ospos git://github.com/jekkos/opensourcepos.git
time="2016-01-13T07:47:21-07:00" level=fatal msg="Error trying to use git: exit status 128 (Cloning into '/tmp/docker-build-git512207154'...\nfatal: unable to connect to github.com:\ngithub.com: No address associated with hostname\n\n)"

**Comment by jekkos** [comment] 2016-01-13 16:45
should be https://github.com/jekkos/opensourcepos.git as command?

**Comment by jekkos** [comment] 2016-01-13 16:49
Also repo names should be similar. 

    docker build -t me/ospos https://github.com/jekkos/opensourcepos.git
    docker run -d me/ospos -p 80:80

**Comment by jekkos** [comment] 2016-01-13 16:54
Currently the Dockerfile is cloning ospos into the container. For development this could be mounted from outside. Advantage is that versions of php, mysql can be perfectly controlled.

**Comment by odiea** [comment] 2016-01-13 20:00
I am still getting this error. Do I need to run it as sudo?
> docker build -t me/ospos https://github.com/jekkos/opensourcepos.git
time="2016-01-13T12:57:16-07:00" level=fatal msg="Error trying to use git: exit status 128 (Cloning into '/tmp/docker-build-git002171098'...\nfatal: unable to access 'https://github.com/jekkos/opensourcepos.git/': Could not resolve host: github.com\n)"

**Comment by odiea** [comment] 2016-01-13 21:19
If I use lubuntu or Mint I get the following error.
odie@odie-virtual-machine ~ $ docker build -t me/ospos https://github.com/jekkos/opensourcepos.git
FATA[0000] Post http:///var/run/docker.sock/v1.18/build?cpusetcpus=&cpushares=0&dockerfile=&memory=0&memswap=0&remote=https%3A%2F%2Fgithub.com%2Fjekkos%2Fopensourcepos.git&rm=1&t=me%2Fospos: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?

**Comment by jekkos** [comment] 2016-01-13 21:46
Looks like it's having some trouble connecting to the github site. Will check if I can reproduce that here.

**Comment by jekkos** [comment] 2016-01-13 21:48
Seems to work fine here. Weird stuff.

**Comment by odiea** [comment] 2016-01-13 22:12
My procedure was on all 3 distros  apt-get install docker. Were there any other settings for docker?

**Comment by odiea** [comment] 2016-01-13 23:16
In the ubuntu repository there are 2 dockers. Docker and Docker.io. It appears it requires the Docker.io to work.

**Comment by daN4cat** [comment] 2016-01-14 10:11
Out of curiosity, why are you using Dockers(.io)?

Is it to run different Apache server/php configuration to test OSPOS?

Or do you want to isolate OSPOS server from any other web services for some security reason?

**Comment by jekkos** [comment] 2016-01-14 10:36
Docker is a bit of a hype these days. It will allow users to install and run ospos without too much hassle. Also it will offers some possibilities for running CI tests, all the setup is contained in one or two scripts which means that the application can be setup in any environment in an isolated way. Having it isiolated means you won't have to deal with dependency conflicts of php versions or the like.

**Comment by daN4cat** [comment] 2016-01-14 10:44
Yep, config as expect and I understand you get the deployment part. Good to know, not that I need to play with this.

Yes I know, Dockers is a hype, like node.js and Angularjs, etc. Sometimes I feel that people love to have a new buzzword/toy just to sound a bit cool :-) I don't want to sound like criticizing it's just that everyday there is a new one and you wonder if you really need it...

**Comment by odiea** [comment] 2016-01-14 17:47
Have you thought of any other solutions for me to be able to connect?

**Comment by odiea** [comment] 2016-01-14 18:45
This is appearing to need a lot of unnecessary installations of other packages for the end user. It may not be beneficial after all. You will have to see what additional packages you have installed to find out what all is needed.

**Comment by daN4cat** [comment] 2016-01-14 19:31
Welcome to Linux world :-)

**Comment by odiea** [comment] 2016-01-14 21:38
Step 1 You must be running a 64 bit system.
Step 2 You must use sudo a lot.
Step 3 I finally got the container built.
Step 4 I cant get to the ip address that docker supplies.
Step 5 It's not worth the effort unless a complete setup guide for Docker is included. Such as how to change their ridiculous ip addresses.

**Comment by odiea** [comment] 2016-01-15 01:59
I installed ubuntu 64. I install docker-engine I created the ospos container. Now how do I log into this new container. It appears going to localhost does nothing.This will be my last attempt unless I get further info.

**Comment by jekkos** [comment] 2016-01-15 09:10
hmm ok did you manage to execute the docker run command? if that succeeds then you should be able to load ospos from port 80. If you type docker ps then you can see the mapped ports to the host system and if the container is actually running.

Maybe you're right to say that docker is not really helping to make it easier. However there's still some advantages in using it as travis-ci is moving towards this kind of setup.

**Comment by odiea** [comment] 2016-01-15 12:44
Step 1 You must be running a 64 bit system.
 Step 2 You must use sudo .
 Step 3 I finally got the container built.
 Step 4 I cant get to the ip address that docker supplies. 
 Step 5 It's not worth the effort unless a complete setup guide for Docker is included. Such as how to change their ridiculous ip addresses.
Step 6 Ip addresses are not a concern?
Step 7 Opened firefox. went to localhost showed it had a web page. typed in localhost/index.php and the program showed. Has database error on exit. This feauture not supported.

**Comment by odiea** [comment] 2016-01-15 19:25
When it works it does not show a receipt. Backup fails. Most of the time finding a docker stop clause doesn't work. When I do shut it down by closing ubuntu nothing is saved in Items or receipt.

**Comment by odiea** [comment] 2016-01-15 19:56
I am using the current version docker-machine. I believe dosker ls should show the containers list. Here is what response I get. I would shit-can this idea.
odie@odie-virtual-machine:~$ sudo docker ls
[sudo] password for odie: 
docker: 'ls' is not a docker command.
See 'docker --help'.
odie@odie-virtual-machine:~$ sudo docker-machine ls
sudo: docker-machine: command not found

**Comment by odiea** [comment] 2016-01-16 12:07
@jekkos  Can you add a different php version to see if that's the no-receipt problem? It would be nice to see a functioning ospos version.

**Comment by odiea** [comment] 2016-01-17 18:12
I see now this is for testing purposes only. @jekkos have you found a solution for receipts not showing within your container?

**Comment by jekkos** [comment] 2016-01-18 08:46
Not yet, will have a look later today. The fact that the database is empty again is probably due to the fact that the mysql data is inside the container and that docker doesn't persist that data unless you run a docker commit after stopping it. Not sure whether this is a best practice when composing containers.

**Comment by jekkos** [comment] 2016-01-18 19:27
I found the culprit for this pagination bug. The page counter is sent using a POST and then set manually in intialize_pagination in each controller. I had to debug the internal CI3 library to see why it became invalid and was eventually set back to 0. 

CI3 is currently giving two options to determine the current page on screen

* Use a query string HTTP GET and manually configure the named parameter that carries the page number
* Use a regular URI with HTTP GET and configure the uri segment that contains the page's parameter

So there seems to be a breaking change in comparison with older versions as it used to be allowed to set this variable manually. In CI3 this isn't possible anymore as in case it's not a query string, the library will check for the uri segment (even if it's undefined) and fallback to the default page if does not encounter a valid integer type.

I think I will go and make an issue in their bug tracker to discuss why this change was done. It's indeed a fact that POST has other problems, especially when it comes to using the back button in the browser. But in this case it would have been better to check for an externally defined value first before defaulting back to that first page.

**Comment by daN4cat** [comment] 2016-01-18 19:30
Many thanks, but you posted fix and comment against the wrong issue. I renamed the commit to be 120 and maybe you can repost this to 120 to keep all in the right discussion thread.

284 is about dockers :-)

That said, I'll test now.

**Comment by jekkos** [comment] 2016-01-19 22:28
The receipt problem is due to the cookies being duplicated once again. I did an upgrade of the container to php 5.5 and I get exactly the same behavior. Pretty weird as there's nothing in the error logs even when I enable the php display_erorr setting.

Think this issue might be related to #158 and #275. CI3 has a rewrite of the session library which should solve this issue anyway.

**Comment by daN4cat** [comment] 2016-01-19 22:55
So time to switch to CI3 😊

**Comment by odiea** [comment] 2016-01-19 23:08
I just tried to create a new database from ospos ci3 version and I got the following error
Error

SQL query: 


-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 08, 2011 at 04:27 PM
-- Server version: 5.1.54
-- PHP Version: 5.3.3

--
-- Database: `pos`
--

SOURCE tables.sql;



MySQL said: Documentation 
 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SOURCE tables.sql' at line 14

**Comment by odiea** [comment] 2016-01-19 23:18
Then after creating the database just using the 2 required sql files I got this error.

A Database Error Occurred

Error Number: 1054

Unknown column 'data' in 'field list'

SELECT `data` FROM `ospos_sessions` WHERE `id` = '41f857dc8110fbca0dd6af2e590300c07083dc09'

Filename: libraries/Session/drivers/Session_database_driver.php

Line Number: 166

**Comment by odiea** [comment] 2016-01-19 23:35
I created another database with a different name using the 2 files and now it connects ok

**Comment by odiea** [comment] 2016-01-20 00:25
The only way I could get this new database installation to work was creating 1 file containing tables and constraints. Like the way it use to be.

**Comment by jekkos** [comment] 2016-01-20 09:57
I had another look at the duplicate cookie problem. At first sight the issue could be that the patched up method is concatenating the set-cookie header contents into one header, which makes it exceed the 4kb limit and so the end user will see a white page in the end

As @daN4cat said I will try this setup with CI3 and see if the issue persists. If it doesn't then maybe we might consider to release the CI3 branch within 2.3.4 instead of including it in 2.4.

Users often report deployment problems similar to this and I must admit that my users often get kicked out of the application as well. This is a long standing issue and I would finally like to get rid of it. Also this brings an opportunity to remove the hackish code that was supposed to solve these problems.

**Comment by daN4cat** [comment] 2016-01-20 12:01
@odiea the issue you had earlier looked like you were using an old tables.sql, or the file was not present at all.

With regards sql files structure, I can't comment. I never tried it but if it's not working properly we should change.

@jekkos not sure we need to make CI3 part of 2.3.4, but I don't have strong feelings. We can merge it back to 2.3.4 but in general changes like those are quite relevant to up the minor counter (MM.mm.pp -> Major, Minor, Patch). So if you ask me what's your preference I would say, let's push out 2.4 with CI3 and maybe drop 2.3.4. Bootstrap UI can be a 2.4.1, although the logic would be to get 2.5 because that's another major change.

Unless we focus on bet Bootstrap UI sorted in 2.4 and then issue 2.4. with CI3 + Bootstrap UI. Maybe that's doable? Just some wondering here...

**Comment by odiea** [comment] 2016-01-20 12:10
I think its time to go back to combining the 2 sql files into 1. Ospos has that same issue with installing from database. All 3 files were in the same database location  so I don't know why it cant find the other 2 files..

**Comment by daN4cat** [comment] 2016-01-20 12:41
Yes, there was a similar issue in #289.

@jekkos should I move everything in database.sql or should we add something to the wiki explaining how to?

**Comment by jekkos** [comment] 2016-01-20 17:33
I will make a grunt task to concat the database.sql from tables and constraints.sql. So it'll be auto generated.

Then we can keep clean separation for both and have the migration script reuse those parts as well.

**Comment by jekkos** [comment] 2016-01-20 17:51
Both migration and database.sql scripts will now be generated by grunt, use 

     grunt concat

to regen once changes are done. Maybe I should add this to the wiki.

**Comment by odiea** [comment] 2016-01-20 19:48
I don't think that everyone that's using this is going to be a computer geek! I think a simple install is the  better idea.

**Comment by daN4cat** [comment] 2016-01-21 08:54
@odiea that grunt script needs to be run only when we change something in the db schema. It's like with javascript and minimise, you run a grunt script. So nothing you need to worry at installation time as database.sql will be one all inclusive.

**Comment by odiea** [comment] 2016-01-21 11:44
So are we talking containers install  using this or non-container install using this?

**Comment by daN4cat** [comment] 2016-01-21 13:28
I'm afraid we are talking about two different things.

My point was confined to the database.sql & tables.sql + cosntraint.sqp story. Nothing to do with dockers.

I know, this conversation got a bit convoluted.

**Comment by odiea** [comment] 2016-01-21 13:36
Thanks @daN4cat for the clarification. I used the latest docker release and all went good. I guess I overreacted with the initial install. No receipts yet .

**Comment by jekkos** [comment] 2016-01-21 17:32
Receipts working now. on 2.3.3 I adapted the scripts to work with both branches, 2.3.3 and 2.4. 
Reason why it didn't work was the absence of the php5-gd package. I added it to the Dockerfile.

**Comment by jekkos** [comment] 2016-01-21 17:33
Also I moved the docker scripts into docker/ folder. This commit can be merged with 2.4.

**Comment by daN4cat** [comment] 2016-01-21 18:40
Merged in 2.4. 

Please note that I reran `grunt concat` because in 2.4 we need the new sessions table.

**Comment by odiea** [comment] 2016-01-21 20:23
I just reran it an now receipts are showing. It appears you came across the reason some people complain about no receipts showing. Good work!

**Comment by jekkos** [comment] 2016-01-22 09:58
Yes the reason is the missing package. Was kind of hard to fix it as there were no errors in the log even after enabling error logging in apache.

**Comment by daN4cat** [comment] 2016-01-22 11:32
Marged the latest changes from 2.3.4 into develop/2.4 and touched the version in package.json to be 2.4

**Comment by odiea** [comment] 2016-01-26 10:45
It appears the latest docker is not creating receipts. I will include a screen shot of possible issue?
![2016-01-26 03_41_39-lubuntu 64 - vmware player non-commercial use only](https://cloud.githubusercontent.com/assets/10962177/12578600/2c4606a2-c3df-11e5-927c-cfc743bdcc9c.png)

**Comment by jekkos** [comment] 2016-01-26 11:14
Did you rebuild the image from the repository? I'm a little surprised as it should include php-gd. Maybe check the log for php-gd library (can't see it in this screenshot)

**Comment by odiea** [comment] 2016-01-26 11:18
docker build -t me/ospos https://github.com/jekkos/opensourcepos.git is the command I used this morning.

**Comment by odiea** [comment] 2016-01-26 12:17
I tried it in a different version of ubuntu. It took 5 times longer to create the container but everything is working now. I guess removing the containers and then recreating them doesn't really change much.

**Comment by odiea** [comment] 2016-01-26 14:25
I found that you build your container. Then you run your container. Add info stop container then issue docker start "Container id" and all your info will be there. I read that run actually creates a new container each time. To find the container id docker ps -a. I also now start terminal with sudo bash.

**Comment by jekkos** [comment] 2016-01-26 15:19
Yes indeed. You get a new container instance everytime you hit run. However if you don't reuse the build command, then the starting point is the same. If you want to save changes in a running container, you can use docker commit. Then next time you run that container, you will start with the latest state at that point.

**Comment by daN4cat** [comment] 2016-01-31 16:51
Is this sorted and can be closed?

**Comment by jekkos** [comment] 2016-02-02 16:14
Not completely .. There's one issue left with the db setup that I have to look into. I'll close this one once I have it sorted out.

**Closed** 2016-02-03 16:56 UTC
Labels: question

**Comment by daN4cat** [comment] 2016-02-03 18:17
The last commit `Use grep and wait for mysql to come up properly` seems to be submitted only in develop/2.4. Is that on purpose should it be in master too?

**Comment by jekkos** [comment] 2016-02-03 19:53
It's in master as well but under a different commit.

**Comment by daN4cat** [comment] 2016-02-03 20:04
ok, got it
