### ISSUE TITLE
New zip repository

### ISSUE THREAD

**Issue by odiea** [jekkos/opensourcepos#1448] opened 2017-08-06 14:47 UTC
How in the heck do we tell which one of these is the 3.1.0 Version.

![2017-08-06 08_44_38-jekkos_opensourcepos](https://user-images.githubusercontent.com/10962177/29004379-d21627cc-7a83-11e7-9d20-4c7aad34557a.png)

**Comment by daN4cat** [comment] 2017-08-06 15:08
Take the latest as that is the last build from master

**Comment by daN4cat** [comment] 2017-08-06 15:09
It's created after a commit. Might take a while to generate.

**Comment by odiea** [comment] 2017-08-06 15:13
You are correct about not liking this. But that's the way it is. Is there a way the github download button can pull from the new repo. If not can u remove it?

**Comment by daN4cat** [comment] 2017-08-06 16:06
Well I said yesterday evening that you and Steve might not like. If really not fine I can revert and resubmit the whole code to Github and we fix better when @jekkos is back.

**Comment by odiea** [comment] 2017-08-06 16:11
You 2 have already done too much work to revert back. You may be getting more issues if the github repository can be downloaded.

**Comment by daN4cat** [comment] 2017-08-06 16:12
No I would not revert everything just one simple thing to resubmit the code. It's not a big job

**Comment by odiea** [comment] 2017-08-06 16:21
I just found out I could Update the one I have been working on and place it's application folder into the new release and all works ok so far.

**Comment by daN4cat** [comment] 2017-08-06 17:51
I submitted to my Github repo the full code and it's the latest master.
I can keep up my personal one in that way, it's just a matter of changing .gitignore file.

**Comment by jekkos** [comment] 2017-08-06 22:43
Hmm I know it's not so convenient but keeping source and binary distribution separate is just best practice in software dev?

**Comment by jekkos** [comment] 2017-08-06 22:46
There are other args like not having to merge minified files once versions come together. now one has to decide whether to do proper development with a full setup or just use the application build as it is..

 @SteveIreland any opinion on this?

**Comment by jekkos** [comment] 2017-08-06 22:47
Also I think this way we can make users more aware of the difference between stable and dev builds which are not for the faint of heart ;)

**Comment by SteveIreland** [comment] 2017-08-06 23:30
I hate to admit this, but I have no clue what the issue is.  Maybe I don't see it because I'm not a collaborator.    I always go to the Clone or Download button and click on Download zip file and always get the latest.   Now I do have a dozen versions of OSPOS on my system but that's no one's fault but my own.

When I download release 3.0.2  I simply went to the bottom of the page and downloaded the release that I assumed was built from the last 3.0.2 commit.

Is that not how it's going to be seen from the end user's perspective for the 3.1.0 release?

**Comment by odiea** [comment] 2017-08-07 00:35
The only issue I had with this was if you do a merge with the current github You may get the following error after you try to run it as a normal build.
Your system folder path does not appear to be set correctly. Please open the following file and correct this: index.php . But I found a way around that and @daN4cat also has helped out for us who usually only test for issues.

**Comment by SteveIreland** [comment] 2017-08-07 02:46
Okay.  I have never seen the list of zip files that you started off this thread with so I thought that was the issue. I merged the latest master with my local repository and pushed it back up to my fork with no problems.  I also rebased my branches onto the new master - no issues.

**Comment by daN4cat** [comment] 2017-08-07 06:17
Steve, most likely you'll see the problem when we change something to composer packages. Unless you install it locally or download the bintray you'll miss it.

**Comment by SteveIreland** [comment] 2017-08-07 14:02
Yep.  Got it. I added that guzzlehttp to my composer.json.  When I tried to rebase that then all hell broke loose.  I assumed that I was doing something wrong.  So I recovered by "replaying my work" on a new branch.

**Comment by daN4cat** [comment] 2017-08-07 15:11
Use bin/devinstall.sh script

**Comment by SteveIreland** [comment] 2017-08-08 01:25
Okay, I have FINALLY caught up with everyone else and have experienced nearly all of the issues.  So now I know what everyone is talking about.  Bin tray wasn't working for awhile so that added to my confusion.  It was telling me I had reached a "dark spot".  Now is that not a helpful message?!?!  It's good to be the last guy on the trail as the trail blazers have already cleared the way.

**Comment by daN4cat** [comment] 2017-08-08 08:08
Welcome onboard :-)

**Comment by daN4cat** [comment] 2017-08-13 18:07
@jekkos this zip file story needs some tidy up. Maybe add branch name and commit hash to the zipfile name? Official release could be market with the release tag when available.
Some ideas, I know it's some work to do...

**Comment by odiea** [comment] 2017-08-13 19:09
Also it appears the the Zip finder in Customers no longer functions.
![2017-08-13 13_07_41-wedidit _ powered by ospos 3 1 0](https://user-images.githubusercontent.com/10962177/29252673-a6311e96-8028-11e7-8815-47bffa10ed68.png)

**Comment by daN4cat** [comment] 2017-08-13 20:47
@odiea I would create a new bug, because that has nothing to do with the zip story

**Closed** 2017-08-29 09:58 UTC
Labels: enhancement

**Comment by odiea** [comment] 2017-09-14 10:21
Any idea why bintray is not updating the code. Zips are 4 days old.

**Comment by daN4cat** [comment] 2017-09-14 10:53
@jekkos?

**Comment by jekkos** [comment] 2017-09-14 11:24
Ok needed to link travis to the new repo.. should be done now I'm running a build.

**Comment by daN4cat** [comment] 2017-09-14 20:54
Yep, build works again.
